# DROP V7.9 — Concept → Web Research Portfolio

این نسخه مسیر Idea چندمرحله‌ای DROP را حفظ می‌کند و بعد از تأیید Concept یک **Research Portfolio واحد** می‌سازد:

- **Music:** فقط Web Research؛ هیچ MusicBrainz/embedding retrieval برای recommendation وجود ندارد.
- **Genius:** یک audit جدا روی ۱۰ قطعهٔ provisional.
- **Film / Series:** چند اثر روایی که proposition انسانی Concept را حمل می‌کنند.
- **Artworks:** نقاشی، مجسمه، عکس، installation، performance و سایر آثار هنری مرتبط.
- **Readings:** منابع **علمی/دانشگاهی** و متن‌های **هنری/نقد/essay** مرتبط.
- **Final Critic:** همهٔ حوزه‌ها را دوباره نسبت به همان Approved Concept و Brief می‌سنجد.
- خروجی نهایی یک artifact واحد است: Concept + Music + Screen + Art + Scientific/Artistic Readings.
- Logging، token/cost accounting و Progress Monitor حفظ شده‌اند.
- Auto Mode همچنان فقط API key می‌گیرد و کل مسیر را تا Portfolio نهایی اجرا می‌کند.

In [1]:
# Colab: dependencies are usually present. Uncomment only if needed.
# !pip -q install requests jsonschema pandas
# Optional local malformed-JSON repair helper (not required by V7.6 architecture):
# !pip -q install json-repair

In [2]:
import os
import json
import re
import time
import uuid
from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime, timezone
from getpass import getpass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests
from jsonschema import validate as jsonschema_validate
from jsonschema.exceptions import ValidationError

try:
    import pandas as pd
except Exception:
    pd = None

from IPython.display import display, HTML, clear_output

try:
    import ipywidgets as widgets
    WIDGETS_AVAILABLE = True
except Exception:
    widgets = None
    WIDGETS_AVAILABLE = False

# Colab sometimes needs the custom widget manager explicitly enabled.
try:
    from google.colab import output as _colab_output
    _colab_output.enable_custom_widget_manager()
except Exception:
    pass

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_MODELS_URL = "https://openrouter.ai/api/v1/models"

# ---------- Quality / cost knobs ----------
POOL_SIZE = 6                 # Original board used 8. 6 is the lean default; set 8 for strict exploration depth.
MIN_TERRITORY_TYPES = 5
MIN_FINAL_CARDS = 3
MAX_FINAL_CARDS = 5
MAX_USER_ROUNDS = 3
MAX_AUTO_REPAIR_TARGETS = 2
ENABLE_AUTO_REPAIR = True

# Input/output caps keep accidental verbosity expensive only up to a known bound.
MAX_TOKENS = {
    "brief_compiler": 1800,
    "concept_studio": 4800,
    "concept_gate": 2800,
    "candidate_repair": 3200,
}

# Exact OpenRouter model slugs verified for this V7 build (2026-09-07).
MODEL_STRATEGY = {
    "compiler": [
        "openai/gpt-5.6-luna",
        "google/gemini-3.6-flash",
        "openai/gpt-5.6-terra",
    ],
    # Round 1: Claude generates, GPT judges.
    "round_1": {
        "generator": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "openai/gpt-5.6-terra"],
        "validator": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "openai/gpt-5.6-terra"],
        "repair": ["anthropic/claude-opus-5", "openai/gpt-5.6-sol", "anthropic/claude-sonnet-5"],
    },
    # Round 2 deliberately swaps model families after a rejected/failed round.
    "round_2": {
        "generator": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.6-flash"],
        "validator": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "openai/gpt-5.6-terra"],
        "repair": ["anthropic/claude-opus-5", "openai/gpt-5.6-sol", "anthropic/claude-sonnet-5"],
    },
    # Round 3 is a premium escalation, used only after two unsuccessful rounds.
    "round_3": {
        "generator": ["anthropic/claude-opus-5", "anthropic/claude-sonnet-5", "openai/gpt-5.6-sol"],
        "validator": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "openai/gpt-5.6-terra"],
        "repair": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "openai/gpt-5.6-terra"],
    },
}

# Fallback estimates only. Actual cost returned by OpenRouter usage is preferred and logged.
FALLBACK_PRICE_USD_PER_M = {
    "openai/gpt-5.6-luna": (0.20, 1.20),
    "openai/gpt-5.6-terra": (2.00, 12.00),
    "openai/gpt-5.6-sol": (2.00, 10.00),
    "anthropic/claude-sonnet-5": (2.00, 10.00),
    "anthropic/claude-opus-5": (5.00, 25.00),
    "google/gemini-3.6-flash": (0.75, 3.75),
}

RUN_ROOT = Path("drop_idea_runs")
RUN_ROOT.mkdir(exist_ok=True)

TERRITORY_TYPES = {
    "HUMAN_BEHAVIOR", "EMOTIONAL", "SOCIAL", "CULTURAL", "TEMPORAL",
    "RITUAL", "MATERIAL", "ATTENTION", "MEMORY", "PHILOSOPHICAL", "OTHER"
}

## Logging + token/cost accounting

هر فراخوانی موفق یا ناموفق یک رکورد JSONL دارد. برای call موفق، موارد زیر ثبت می‌شود:
`stage`, `round`, `requested_model`, `actual_model`, prompt، raw output، parsed JSON، latency، input/output/reasoning/cached/total tokens و cost.

در پایان نیز summary به تفکیک stage و model ذخیره می‌شود.

In [3]:
def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def compact_json(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))


class RunLogger:
    def __init__(self, run_id: Optional[str] = None, project_id: str = "unknown", root: Path = RUN_ROOT):
        self.project_id = project_id or "unknown"
        self.run_id = run_id or (datetime.now().strftime("%Y%m%d_%H%M%S") + "_" + uuid.uuid4().hex[:8])
        self.dir = root / self.run_id
        self.dir.mkdir(parents=True, exist_ok=True)
        self.jsonl_path = self.dir / "model_calls.jsonl"
        self.summary_path = self.dir / "usage_summary.json"
        self.records: List[Dict[str, Any]] = []

    def log(self, record: Dict[str, Any]):
        record = deepcopy(record)
        record.setdefault("project_id", self.project_id)
        record.setdefault("run_id", self.run_id)
        record.setdefault("timestamp_utc", utc_now_iso())
        self.records.append(record)
        with self.jsonl_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(record, ensure_ascii=False) + "\n")

    def save_artifact(self, name: str, obj: Any) -> Path:
        path = self.dir / name
        with path.open("w", encoding="utf-8") as f:
            json.dump(obj, f, ensure_ascii=False, indent=2)
        return path

    @staticmethod
    def _is_billed_record(r: Dict[str, Any]) -> bool:
        u = r.get("usage") or {}
        return bool(int(u.get("total_tokens") or 0) > 0 or float(u.get("cost_usd") or 0.0) > 0)

    def summary(self) -> Dict[str, Any]:
        ok = [r for r in self.records if r.get("status") == "ok"]
        errors = [r for r in self.records if r.get("status") == "error"]
        billed = [r for r in self.records if self._is_billed_record(r)]
        failed_billed = [r for r in errors if self._is_billed_record(r)]

        def sums(items):
            return {
                "calls": len(items),
                "prompt_tokens": sum(int(x.get("usage", {}).get("prompt_tokens") or 0) for x in items),
                "completion_tokens": sum(int(x.get("usage", {}).get("completion_tokens") or 0) for x in items),
                "reasoning_tokens": sum(int(x.get("usage", {}).get("reasoning_tokens") or 0) for x in items),
                "cached_tokens": sum(int(x.get("usage", {}).get("cached_tokens") or 0) for x in items),
                "total_tokens": sum(int(x.get("usage", {}).get("total_tokens") or 0) for x in items),
                "cost_usd": round(sum(float(x.get("usage", {}).get("cost_usd") or 0.0) for x in items), 6),
                "web_search_requests": sum(int(x.get("usage", {}).get("web_search_requests") or 0) for x in items),
                "web_fetch_requests": sum(int(x.get("usage", {}).get("web_fetch_requests") or 0) for x in items),
            }

        by_stage, by_model = {}, {}
        for stage in sorted({x.get("stage") for x in billed if x.get("stage")}):
            by_stage[stage] = sums([x for x in billed if x.get("stage") == stage])
        for model in sorted({x.get("actual_model") or x.get("requested_model") for x in billed if (x.get("actual_model") or x.get("requested_model"))}):
            by_model[model] = sums([x for x in billed if (x.get("actual_model") or x.get("requested_model")) == model])

        result = {
            "project_id": self.project_id,
            "run_id": self.run_id,
            "successful_calls": len(ok),
            "failed_attempts": len(errors),
            "billed_attempts": len(billed),
            # Authoritative run total must include HTTP-success attempts that were billed even if local parsing later failed.
            "totals": sums(billed),
            "successful_only_totals": sums(ok),
            "failed_billed_totals": sums(failed_billed),
            "by_stage": by_stage,
            "by_model": by_model,
            "log_file": str(self.jsonl_path),
        }
        with self.summary_path.open("w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        return result

    def print_summary(self):
        s = self.summary(); t = s["totals"]
        print("\n=== DROP TOKEN / COST SUMMARY ===")
        print("Project:", s["project_id"])
        print("Run:", s["run_id"])
        print("Successful model calls:", s["successful_calls"])
        print("Failed attempts:", s["failed_attempts"], "| billed attempts:", s["billed_attempts"])
        print("Input tokens (all billed attempts):", t["prompt_tokens"])
        print("OUTPUT tokens (all billed attempts):", t["completion_tokens"])
        print("Reasoning tokens:", t["reasoning_tokens"])
        print("Total tokens:", t["total_tokens"])
        print("Cached input tokens:", t["cached_tokens"])
        print("Cost USD (all billed attempts):", t["cost_usd"])
        if s["failed_billed_totals"]["calls"]:
            print("Cost from failed-but-billed attempts USD:", s["failed_billed_totals"]["cost_usd"])
        print("Log:", s["log_file"])
        if pd is not None and s["by_stage"]:
            display(pd.DataFrame(s["by_stage"]).T)
        return s

## OpenRouter client — structured JSON, retries, model fallback

- `usage.include=true` برای token/cost واقعی.
- ابتدا `json_schema`، سپس `json_object` fallback.
- اگر یک model/endpoint fail شود، model بعدی در chain امتحان می‌شود و تمام failureها در log ثبت می‌شوند.
- API key هرگز log نمی‌شود.

In [4]:
def _extract_json_text(text: str) -> str:
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
        text = re.sub(r"\s*```$", "", text)
    try:
        json.loads(text)
        return text
    except Exception:
        a, b = text.find("{"), text.rfind("}")
        if a >= 0 and b > a:
            candidate = text[a:b+1]
            json.loads(candidate)
            return candidate
    raise ValueError("No valid JSON object in model response")


def _message_text(message: Dict[str, Any]) -> str:
    content = message.get("content", "")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        pieces = []
        for item in content:
            if isinstance(item, dict) and item.get("type") in {"text", "output_text"}:
                pieces.append(item.get("text", ""))
        return "".join(pieces)
    return str(content or "")


def _usage_from_response(data: Dict[str, Any], requested_model: str) -> Dict[str, Any]:
    u = data.get("usage") or {}
    pdet = u.get("prompt_tokens_details") or {}
    cdet = u.get("completion_tokens_details") or {}
    prompt = int(u.get("prompt_tokens") or 0)
    completion = int(u.get("completion_tokens") or 0)
    total = int(u.get("total_tokens") or (prompt + completion))
    cost = u.get("cost")
    cost_source = "openrouter_usage" if cost is not None else "fallback_estimate"
    if cost is None:
        inp, out = FALLBACK_PRICE_USD_PER_M.get(requested_model, (0.0, 0.0))
        cost = prompt * inp / 1_000_000 + completion * out / 1_000_000
    return {
        "prompt_tokens": prompt,
        "completion_tokens": completion,
        "total_tokens": total,
        "reasoning_tokens": int(cdet.get("reasoning_tokens") or 0),
        "cached_tokens": int(pdet.get("cached_tokens") or 0),
        "cost_usd": float(cost or 0.0),
        "cost_source": cost_source,
    }


class OpenRouterClient:
    def __init__(self, api_key: str, logger: RunLogger, timeout: int = 300,
                 app_title: str = "DROP Idea Engine V7"):
        self.api_key = api_key
        self.logger = logger
        self.timeout = timeout
        self.app_title = app_title
        self._available_models: Optional[set] = None

    @property
    def headers(self):
        return {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "X-Title": self.app_title,
        }

    def available_models(self) -> set:
        if self._available_models is not None:
            return self._available_models
        try:
            r = requests.get(OPENROUTER_MODELS_URL, headers=self.headers, timeout=60)
            r.raise_for_status()
            self._available_models = {m.get("id") for m in r.json().get("data", []) if m.get("id")}
        except Exception:
            # Catalog availability must not block generation; API call fallbacks remain active.
            self._available_models = set()
        return self._available_models

    def _schema_response_format(self, schema_name: str, schema: Dict[str, Any]):
        return {
            "type": "json_schema",
            "json_schema": {"name": schema_name, "strict": True, "schema": schema},
        }

    def chat_json(self, *, stage: str, round_index: int, system_prompt: str,
                  user_payload: Dict[str, Any], model_chain: List[str],
                  schema: Dict[str, Any], temperature: float,
                  max_tokens: int, agent_goal: str = "") -> Tuple[Dict[str, Any], Dict[str, Any]]:
        user_text = compact_json(user_payload)
        catalog = self.available_models()
        chain = [m for m in model_chain if (not catalog or m in catalog)] or model_chain
        errors = []

        for model in chain:
            for format_mode in ("json_schema", "json_object"):
                payload = {
                    "model": model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_text},
                    ],
                    "max_tokens": max_tokens,
                    "usage": {"include": True},
                }
                if temperature is not None and not model.startswith("openai/gpt-5.6"):
                    payload["temperature"] = temperature
                if format_mode == "json_schema":
                    payload["response_format"] = self._schema_response_format(stage.replace("-", "_"), schema)
                    # Do not silently route strict-schema calls to providers that ignore response_format.
                    payload["provider"] = {"require_parameters": True}
                else:
                    payload["response_format"] = {"type": "json_object"}

                started = time.perf_counter(); data = None; text = None
                try:
                    r = requests.post(OPENROUTER_URL, headers=self.headers, json=payload, timeout=self.timeout)
                    r.raise_for_status(); data = r.json()
                    text = _message_text(data["choices"][0]["message"])
                    parsed = json.loads(_extract_json_text(text))
                    jsonschema_validate(parsed, schema)
                    usage = _usage_from_response(data, model)
                    actual_model = data.get("model") or model
                    rec = {
                        "status": "ok", "stage": stage, "agent_goal": agent_goal,
                        "round": round_index, "requested_model": model, "actual_model": actual_model,
                        "format_mode": format_mode,
                        "latency_seconds": round(time.perf_counter() - started, 3),
                        "system_prompt": system_prompt, "user_payload": user_payload,
                        "raw_output": text, "parsed_output": parsed, "usage": usage,
                        "generation_id": data.get("id"),
                    }
                    self.logger.log(rec); return parsed, rec
                except Exception as e:
                    # Critical V7.6 accounting fix: if the HTTP response arrived, capture its usage/cost
                    # even when local JSON parsing or schema validation failed afterwards.
                    usage = _usage_from_response(data, model) if data else {
                        "prompt_tokens":0,"completion_tokens":0,"total_tokens":0,
                        "reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0,"cost_source":"none"
                    }
                    err = {
                        "status": "error", "stage": stage, "agent_goal": agent_goal,
                        "round": round_index, "requested_model": model,
                        "actual_model": (data or {}).get("model") or model,
                        "format_mode": format_mode,
                        "latency_seconds": round(time.perf_counter() - started, 3),
                        "error": f"{type(e).__name__}: {e}",
                        "raw_output": text,
                        "usage": usage,
                        "generation_id": (data or {}).get("id"),
                    }
                    self.logger.log(err); errors.append(err["error"])

        raise RuntimeError(f"{stage} failed across model/format fallbacks:\n" + "\n---\n".join(errors[-8:]))

## Compact artifact schemas

Schemas فقط چیزهایی را نگه می‌دارند که downstream واقعاً برای lineage، quality و انتخاب لازم دارد. `project_brief` در Python state می‌ماند و در هر artifact دوباره تکثیر نمی‌شود.

In [5]:
STR_ARR = {"type": "array", "items": {"type": "string"}}
NULL_STR = {"type": ["string", "null"]}

ANCHOR_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": ["request_summary","occasion","host_intention","audience","social_situation",
                 "facts","constraints","explicit_references","desired_feelings","desired_atmosphere",
                 "known_dislikes","core_subjects","core_human_questions","core_emotions","core_tensions",
                 "cultural_or_thematic_territories","must_preserve","must_avoid",
                 "allowed_creative_distance","assumptions","unknowns"],
    "properties": {
        "request_summary": {"type": "string"},
        "occasion": NULL_STR, "host_intention": NULL_STR, "audience": NULL_STR, "social_situation": NULL_STR,
        "facts": STR_ARR, "constraints": STR_ARR, "explicit_references": STR_ARR,
        "desired_feelings": STR_ARR, "desired_atmosphere": STR_ARR, "known_dislikes": STR_ARR,
        "core_subjects": STR_ARR, "core_human_questions": STR_ARR, "core_emotions": STR_ARR,
        "core_tensions": STR_ARR, "cultural_or_thematic_territories": STR_ARR,
        "must_preserve": STR_ARR, "must_avoid": STR_ARR,
        "allowed_creative_distance": {"enum": ["CLOSE","MODERATE","OPEN","UNKNOWN"]},
        "assumptions": STR_ARR, "unknowns": STR_ARR,
    },
}

WHY_SCHEMA = {
    "type": "array", "minItems": 1, "maxItems": 3,
    "items": {
        "type": "object", "additionalProperties": False,
        "required": ["field","connection"],
        "properties": {"field": {"type": "string"}, "connection": {"type": "string"}},
    }
}

DOMAIN_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["music","menu","media","art","article"],
    "properties": {k: {"type": "string"} for k in ["music","menu","media","art","article"]}
}

CANDIDATE_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["candidate_id","territory_type","territory_proposition","core_observation","title","one_line",
                 "human_truth","central_idea","guest_takeaway","why_from_anchor","conceptual_territory",
                 "tone","multi_domain_potential","must_preserve","must_avoid","conceptual_boundaries"],
    "properties": {
        "candidate_id": {"type": "string"},
        "territory_type": {"enum": sorted(TERRITORY_TYPES)},
        "territory_proposition": {"type": "string"}, "core_observation": {"type": "string"},
        "title": {"type": "string"}, "one_line": {"type": "string"},
        "human_truth": {"type": "string"}, "central_idea": {"type": "string"},
        "guest_takeaway": {"type": "string"}, "why_from_anchor": WHY_SCHEMA,
        "conceptual_territory": STR_ARR, "tone": STR_ARR,
        "multi_domain_potential": DOMAIN_SCHEMA,
        "must_preserve": STR_ARR, "must_avoid": STR_ARR, "conceptual_boundaries": STR_ARR,
    },
}

CANDIDATE_BATCH_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["candidates"],
    "properties": {"candidates": {"type": "array", "items": CANDIDATE_SCHEMA}},
}

REVIEW_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["candidate_id","status","abstraction_level","survives_execution_removal","anchor_score",
                 "user_recognition","works_if_opted_out","works_if_not_understood","multi_domain_capable",
                 "pressure_risk","insider_code_risk","failure_codes","anchor_fields","scores","reason"],
    "properties": {
        "candidate_id": {"type": "string"},
        "status": {"enum": ["PASS","REPAIR","DROP"]},
        "abstraction_level": {"enum": ["CONCEPT","BORDERLINE","EXECUTION_MECHANISM","TACTIC","THEME"]},
        "survives_execution_removal": {"type": "boolean"},
        "anchor_score": {"type": "integer", "minimum": 0, "maximum": 5},
        "user_recognition": {"type": "boolean"},
        "works_if_opted_out": {"type": "boolean"},
        "works_if_not_understood": {"type": "boolean"},
        "multi_domain_capable": {"type": "boolean"},
        "pressure_risk": {"enum": ["NONE","LOW","MEDIUM","HIGH"]},
        "insider_code_risk": {"enum": ["NONE","LOW","MEDIUM","HIGH"]},
        "failure_codes": STR_ARR, "anchor_fields": STR_ARR,
        "scores": {
            "type": "object", "additionalProperties": False,
            "required": ["human_truth","conceptual_strength","generativity","guest_usability","distinctness"],
            "properties": {k: {"type": "integer", "minimum": 0, "maximum": 5}
                           for k in ["human_truth","conceptual_strength","generativity","guest_usability","distinctness"]}
        },
        "reason": {"type": "string"},
    },
}

GATE_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["batch_status","reviews","selected_ids","portfolio_note","unregistered_risks"],
    "properties": {
        "batch_status": {"enum": ["PASS","NEEDS_REPAIR","INSUFFICIENT"]},
        "reviews": {"type": "array", "items": REVIEW_SCHEMA},
        "selected_ids": {"type": "array", "items": {"type": "string"}, "maxItems": MAX_FINAL_CARDS},
        "portfolio_note": {"type": "string"},
        "unregistered_risks": {
            "type": "array",
            "items": {
                "type": "object", "additionalProperties": False,
                "required": ["candidate_id","type","severity","evidence"],
                "properties": {
                    "candidate_id": {"type": "string"}, "type": {"type": "string"},
                    "severity": {"enum": ["LOW","MEDIUM","HIGH"]}, "evidence": {"type": "string"}
                }
            }
        },
    },
}

REPAIR_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["repaired"],
    "properties": {
        "repaired": {
            "type": "array",
            "items": {
                "type": "object", "additionalProperties": False,
                "required": ["candidate_id","changed_fields","candidate"],
                "properties": {
                    "candidate_id": {"type": "string"},
                    "changed_fields": STR_ARR,
                    "candidate": CANDIDATE_SCHEMA,
                }
            }
        }
    }
}

## Prompts

سه prompt اصلی، همان منطق 11-board را در سه مسئولیت روشن فشرده می‌کنند. Gate حق تولید Concept جدید ندارد؛ فقط diagnosis/filter می‌کند.

In [6]:
BRIEF_COMPILER_PROMPT = r"""
You are the DROP Brief Compiler. Combine Context Framing and Brief Anchoring in one grounded pass.
R0: no web. Sources may include PROJECT_BRIEF, INITIAL_CONTEXT, DESIRED_FEELING and SEED. Empty optional sources mean nothing; never fill them in. Extract and tightly synthesize; never invent facts or hidden psychology.
Facts, interpretations and assumptions are different. Unsupported fields stay null/[]/UNKNOWN.
Every explicit constraint/dislike/preservation remains visible. Synthesis is allowed only when directly supported by the brief.
core_human_questions/core_tensions may be empty; never manufacture depth.
allowed_creative_distance is UNKNOWN unless the source supports CLOSE/MODERATE/OPEN.
Return concise Persian content in the exact JSON structure. No prose outside JSON.
""".strip()


CONCEPT_STUDIO_PROMPT = r"""
You are the DROP Concept Studio. In ONE pass, do Territory Exploration + Concept Building.
R0: no web. Use only BRIEF_ANCHOR, SEED, PREVIOUS_IDEAS, SESSION_LIKED, SESSION_REJECTED, USER_FEEDBACK and MACHINE_FEEDBACK.
SESSION_LIKED is positive lineage: preserve the qualities the user liked without mechanically copying the card.
SESSION_REJECTED is negative evidence: do not return the same proposition under new wording.
USER_FEEDBACK is the latest explicit creative direction and must materially affect the next round. It may refine preferences but cannot silently erase hard constraints in BRIEF_ANCHOR.
Generate exactly COUNT candidates. Each candidate must originate in a materially different HUMAN/CULTURAL/EMOTIONAL/OBSERVATIONAL proposition territory.
Use at least MIN_TERRITORY_TYPES different territory_type values.

A Concept is a point of view that survives removal of all execution. It must begin from a plausible human truth/observation/relationship/question/ritual understood conceptually.
It must NOT begin from lighting, seating, serving, furniture, objects, signage, guest instructions, games, participation mechanics, or spatial tricks.
Theme/mood/aesthetic alone is not a Concept. Do not force binaries or tensions. Do not invent facts about host/guests/culture.
Differentiate by CENTRAL PROPOSITION and HUMAN TRUTH, not by mechanism.
Target RELEVANT SURPRISE: reinterpret the anchor; never replace it.
Guests who do not understand or participate must still belong; avoid insider hierarchy or concept-performance pressure.

multi_domain_potential is conceptual only, never instructions. Keep each domain phrase <= 14 words.
why_from_anchor must name real BriefAnchor field names. Keep all text fields concise (normally one sentence).
Titles/one_line must be natural Persian and must never be execution instructions.
Return JSON only.
""".strip()


CONCEPT_GATE_PROMPT = r"""
You are the DROP Adversarial Concept Gate. You combine:
Abstraction Validator + Brief Anchor Validator + Guest Usability Validator + Diversity/Portfolio Filter + Independent Critic + lightweight Comparator.
You are a critic/filter, NOT an author. Do not create replacement concepts and do not repair prose here.
R0: no web. Evidence is PROJECT_BRIEF + BRIEF_ANCHOR + ACTIVE_USER_FEEDBACK + SESSION_LIKED + CANDIDATES only.
Latest explicit user feedback is valid session evidence for creative direction; hard source constraints still remain binding.

Per candidate test literally:
1) State mentally the human proposition. If execution is removed, does it still mean something?
2) Is it recognizably derived from the Brief Anchor? score 0..5; 0-1 OFF_BRIEF => DROP; target 3-4, do not reward literalness.
3) Given brief + title + one_line + central_idea, would the user understand why it was returned?
4) Can music, menu, media, art AND article each interpret it conceptually?
5) Is it a point of view rather than theme/tactic/mechanism?
6) Guest usability: opt-out guest still has a complete dignified evening; non-understander belongs fully; no embarrassment/ranking/insider gatekeeping; hospitality before concept performance.

Status:
PASS = concept-level, anchor-connected, recognizable, hospitable, multi-domain.
REPAIR = a real human truth exists underneath but abstraction/recognition/usability has a repairable defect.
DROP = no concept underneath, or off-brief, or blocking guest problem.
Use failure codes when applicable: THEME_AS_CONCEPT, AESTHETIC_AS_CONCEPT, EXECUTION_TACTIC_AS_CONCEPT,
INTERACTION_MECHANIC_AS_CONCEPT, OBJECT_AS_CONCEPT, SPATIAL_LAYOUT_AS_CONCEPT, LIGHTING_TACTIC_AS_CONCEPT,
SERVICE_TACTIC_AS_CONCEPT, COPY_AS_CONCEPT, OFF_BRIEF, USER_RECOGNITION_FAIL, GUEST_PRESSURE, INSIDER_ONLY.

Portfolio selection:
Select 3-5 PASS candidates only, prioritizing difference in this order:
CENTRAL_PROPOSITION > HUMAN_TRUTH > CONCEPTUAL_TERRITORY > EMOTIONAL/CULTURAL territory > GUEST_TAKEAWAY > mechanism.
Do not pad. If fewer than 3 PASS, selected_ids may contain the PASS survivors and batch_status=NEEDS_REPAIR if repairable cards exist, otherwise INSUFFICIENT.
All input candidates must receive exactly one review. Keep reasons concise. Return JSON only.
""".strip()


CANDIDATE_REPAIR_PROMPT = r"""
You are the DROP Candidate Repair Agent. This is the only repair round for these targets.
Repair only the supplied failed candidates, guided by their exact Gate reviews and Brief Anchor.
Do not discard the underlying territory if a human truth exists.
Order: restore human truth -> central proposition -> demote/remove execution mechanism -> restore anchor recognition -> remove social pressure/insider hierarchy -> preserve constraints.
Do not turn a tactic into prettier abstract prose while leaving the tactic central. Do not invent facts.
Keep candidate_id unchanged. Return the full repaired candidate and list changed_fields. JSON only.
""".strip()

## Deterministic checks (free: no model tokens)

In [7]:
EXECUTION_TITLE_PATTERNS = [
    r"\b(table|chair|lighting|light|serve|serving|seat|seating|card|game|write|place|object)\b",
    r"(میز|صندلی|نورپردازی|چراغ|سرو\s|بازی|کارت|بنویس|بنشین|چیدمان)",
]


def require_nonempty_str(obj, key):
    if not isinstance(obj.get(key), str) or not obj[key].strip():
        raise ValueError(f"Missing/non-empty string required: {key}")


def validate_anchor_local(anchor: Dict[str, Any]):
    jsonschema_validate(anchor, ANCHOR_SCHEMA)
    require_nonempty_str(anchor, "request_summary")
    return True


def validate_candidate_batch_local(batch: Dict[str, Any], expected_count: int):
    jsonschema_validate(batch, CANDIDATE_BATCH_SCHEMA)
    cands = batch.get("candidates", [])
    if len(cands) != expected_count:
        raise ValueError(f"Expected exactly {expected_count} candidates, got {len(cands)}")
    ids = [c["candidate_id"] for c in cands]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate candidate_id")
    for c in cands:
        for k in ["title","one_line","human_truth","central_idea","guest_takeaway","territory_proposition"]:
            require_nonempty_str(c, k)
    types = {c["territory_type"] for c in cands}
    if len(types) < min(MIN_TERRITORY_TYPES, expected_count):
        raise ValueError(f"Territory diversity too low: {len(types)} types")
    return True


def validate_gate_local(gate: Dict[str, Any], candidates: List[Dict[str, Any]]):
    jsonschema_validate(gate, GATE_SCHEMA)
    ids = [c["candidate_id"] for c in candidates]
    review_ids = [r["candidate_id"] for r in gate["reviews"]]
    if sorted(ids) != sorted(review_ids):
        raise ValueError("Gate must review every candidate exactly once")
    if len(review_ids) != len(set(review_ids)):
        raise ValueError("Duplicate gate review")
    review_map = {r["candidate_id"]: r for r in gate["reviews"]}
    selected = gate["selected_ids"]
    if len(selected) != len(set(selected)):
        raise ValueError("Duplicate selected_ids")
    if not set(selected).issubset(ids):
        raise ValueError("Gate selected unknown candidate")
    if any(review_map[x]["status"] != "PASS" for x in selected):
        raise ValueError("Gate may select PASS candidates only")
    if gate["batch_status"] == "PASS" and not (MIN_FINAL_CARDS <= len(selected) <= MAX_FINAL_CARDS):
        raise ValueError("PASS batch must hold 3-5 selected cards")
    return True


def title_looks_like_execution(title: str) -> bool:
    t = (title or "").lower()
    return any(re.search(p, t, flags=re.I) for p in EXECUTION_TITLE_PATTERNS)


def compact_history(items: Optional[List[Dict[str, Any]]], limit: int = 8) -> List[Dict[str, Any]]:
    out = []
    for x in (items or [])[-limit:]:
        if isinstance(x, dict):
            out.append({k: x.get(k) for k in ["title","central_idea","human_truth","guest_takeaway"] if x.get(k)})
        else:
            out.append({"title": str(x)})
    return out


def compute_portfolio_score(review: Dict[str, Any]) -> float:
    # Lightweight deterministic comparison: score can never override PASS/DROP gates.
    s = review["scores"]
    value = (
        review["anchor_score"] * 0.25 +
        s["human_truth"] * 0.20 +
        s["conceptual_strength"] * 0.20 +
        s["generativity"] * 0.15 +
        s["guest_usability"] * 0.10 +
        s["distinctness"] * 0.10
    )
    return round(value, 2)

## Idea pipeline functions — internal state for the unified session

In [8]:
@dataclass
class IdeaRunState:
    project_brief: str
    project_id: str = "unknown"
    initial_context: str = ""
    desired_feeling: str = ""
    seed: str = ""
    previous_ideas: List[Dict[str, Any]] = field(default_factory=list)
    anchor: Optional[Dict[str, Any]] = None
    liked_in_session: List[Dict[str, Any]] = field(default_factory=list)
    rejected_in_session: List[Dict[str, Any]] = field(default_factory=list)
    feedback: str = ""


def _ensure_minimum_source(state: IdeaRunState):
    if not any([
        (state.project_brief or "").strip(),
        (state.initial_context or "").strip(),
        (state.desired_feeling or "").strip(),
        (state.seed or "").strip(),
        state.previous_ideas,
    ]):
        raise ValueError("At least one source is required: project_brief, initial_context, desired_feeling, seed, or previous_ideas.")


def compile_brief(client, state: IdeaRunState) -> Dict[str, Any]:
    _ensure_minimum_source(state)
    payload = {
        "PROJECT_BRIEF": (state.project_brief or "").strip(),
        "INITIAL_CONTEXT": (state.initial_context or "").strip(),
        "DESIRED_FEELING": (state.desired_feeling or "").strip(),
        "SEED": (state.seed or "").strip(),
    }
    anchor, _ = client.chat_json(
        stage="brief_compiler", round_index=0,
        system_prompt=BRIEF_COMPILER_PROMPT, user_payload=payload,
        model_chain=MODEL_STRATEGY["compiler"], schema=ANCHOR_SCHEMA,
        temperature=0.15, max_tokens=MAX_TOKENS["brief_compiler"],
        agent_goal="Ground source context and compile the Brief Anchor without inventing facts.",
    )
    validate_anchor_local(anchor)
    state.anchor = anchor
    client.logger.save_artifact("brief_anchor.json", anchor)
    return anchor


def round_profile(round_index: int) -> Dict[str, List[str]]:
    idx = min(max(round_index, 1), 3)
    return MODEL_STRATEGY[f"round_{idx}"]


def generate_candidates(client, state: IdeaRunState, round_index: int,
                        machine_feedback: str = "") -> Dict[str, Any]:
    if state.anchor is None:
        raise ValueError("Brief must be compiled before generation")
    profile = round_profile(round_index)
    payload = {
        "BRIEF_ANCHOR": state.anchor,
        "SEED": state.seed,
        "PREVIOUS_IDEAS": compact_history(state.previous_ideas),
        "SESSION_LIKED": compact_history(state.liked_in_session[-6:]),
        "SESSION_REJECTED": compact_history(state.rejected_in_session[-10:]),
        "USER_FEEDBACK": state.feedback,
        "MACHINE_FEEDBACK_FROM_PRIOR_FAILED_ROUND": machine_feedback,
        "COUNT": POOL_SIZE,
        "MIN_TERRITORY_TYPES": min(MIN_TERRITORY_TYPES, POOL_SIZE),
        "ROUND": round_index,
        "ID_FORMAT": f"r{round_index}_candidate_XX",
    }
    batch, _ = client.chat_json(
        stage="concept_studio", round_index=round_index,
        system_prompt=CONCEPT_STUDIO_PROMPT, user_payload=payload,
        model_chain=profile["generator"], schema=CANDIDATE_BATCH_SCHEMA,
        temperature=0.85 if round_index < 3 else 0.75,
        max_tokens=MAX_TOKENS["concept_studio"],
        agent_goal="Generate concept-level territories/candidates from the anchor and latest user guidance.",
    )
    validate_candidate_batch_local(batch, POOL_SIZE)
    client.logger.save_artifact(f"round_{round_index:02d}_candidates.json", batch)
    return batch


def gate_candidates(client, state: IdeaRunState, batch: Dict[str, Any], round_index: int,
                    pass_name: str = "initial") -> Dict[str, Any]:
    profile = round_profile(round_index)
    payload = {
        "PROJECT_BRIEF": state.project_brief,
        "BRIEF_ANCHOR": state.anchor,
        "ACTIVE_USER_FEEDBACK": state.feedback,
        "SESSION_LIKED": compact_history(state.liked_in_session[-6:]),
        "CANDIDATES": batch["candidates"],
        "MIN_FINAL_CARDS": MIN_FINAL_CARDS,
        "MAX_FINAL_CARDS": MAX_FINAL_CARDS,
    }
    gate, _ = client.chat_json(
        stage="concept_gate", round_index=round_index,
        system_prompt=CONCEPT_GATE_PROMPT, user_payload=payload,
        model_chain=profile["validator"], schema=GATE_SCHEMA,
        temperature=0.10, max_tokens=MAX_TOKENS["concept_gate"],
        agent_goal="Adversarially validate abstraction, brief lineage, guest usability, diversity and portfolio quality.",
    )
    validate_gate_local(gate, batch["candidates"])
    client.logger.save_artifact(f"round_{round_index:02d}_gate_{pass_name}.json", gate)
    return gate


def repair_candidates(client, state: IdeaRunState, batch: Dict[str, Any], gate: Dict[str, Any],
                      round_index: int) -> Tuple[Dict[str, Any], List[str]]:
    profile = round_profile(round_index)
    cand_map = {c["candidate_id"]: c for c in batch["candidates"]}

    repairable = [r for r in gate["reviews"] if r["status"] == "REPAIR"]
    repairable.sort(key=lambda r: (
        r["anchor_score"] + r["scores"]["conceptual_strength"] + r["scores"]["human_truth"]
    ), reverse=True)
    targets = repairable[:MAX_AUTO_REPAIR_TARGETS]
    if not targets:
        return batch, []

    payload = {
        "BRIEF_ANCHOR": state.anchor,
        "ACTIVE_USER_FEEDBACK": state.feedback,
        "SESSION_LIKED": compact_history(state.liked_in_session[-6:]),
        "TARGETS": [
            {"candidate": cand_map[r["candidate_id"]], "gate_review": r}
            for r in targets
        ],
    }
    repaired_obj, _ = client.chat_json(
        stage="candidate_repair", round_index=round_index,
        system_prompt=CANDIDATE_REPAIR_PROMPT, user_payload=payload,
        model_chain=profile["repair"], schema=REPAIR_SCHEMA,
        temperature=0.25, max_tokens=MAX_TOKENS["candidate_repair"],
        agent_goal="Repair only validator-flagged candidates while preserving human truth and brief constraints.",
    )

    repaired_ids = []
    new_batch = deepcopy(batch)
    by_id = {c["candidate_id"]: i for i, c in enumerate(new_batch["candidates"])}
    allowed_ids = {r["candidate_id"] for r in targets}
    for item in repaired_obj["repaired"]:
        cid = item["candidate_id"]
        if cid not in allowed_ids:
            raise ValueError(f"Repair returned non-target candidate: {cid}")
        if item["candidate"]["candidate_id"] != cid:
            raise ValueError("Repair must preserve candidate_id")
        jsonschema_validate(item["candidate"], CANDIDATE_SCHEMA)
        new_batch["candidates"][by_id[cid]] = item["candidate"]
        repaired_ids.append(cid)

    validate_candidate_batch_local(new_batch, POOL_SIZE)
    client.logger.save_artifact(f"round_{round_index:02d}_repaired_candidates.json", new_batch)
    return new_batch, repaired_ids


def materialize_selected_cards(batch: Dict[str, Any], gate: Dict[str, Any]) -> List[Dict[str, Any]]:
    cand_map = {c["candidate_id"]: c for c in batch["candidates"]}
    review_map = {r["candidate_id"]: r for r in gate["reviews"]}
    cards = []
    for cid in gate["selected_ids"]:
        card = deepcopy(cand_map[cid])
        review = review_map[cid]
        card["validation"] = {
            "anchor_score": review["anchor_score"],
            "abstraction_level": review["abstraction_level"],
            "portfolio_score": compute_portfolio_score(review),
            "risks": review["failure_codes"],
            "reason": review["reason"],
        }
        cards.append(card)
    cards.sort(key=lambda x: x["validation"]["portfolio_score"], reverse=True)
    return cards


def gate_feedback_for_regeneration(gate: Dict[str, Any]) -> str:
    bad = []
    for r in gate.get("reviews", []):
        if r.get("status") != "PASS":
            bad.append(f"{r.get('candidate_id')}: {','.join(r.get('failure_codes') or [])} — {r.get('reason','')}")
    return " | ".join(bad[:6])


def run_generation_round(client, state: IdeaRunState, round_index: int,
                         machine_feedback: str = "") -> Dict[str, Any]:
    batch = generate_candidates(client, state, round_index, machine_feedback=machine_feedback)
    gate = gate_candidates(client, state, batch, round_index, pass_name="initial")
    repaired_ids = []

    if gate["batch_status"] != "PASS" and ENABLE_AUTO_REPAIR:
        pass_count = sum(r["status"] == "PASS" for r in gate["reviews"])
        repair_count = sum(r["status"] == "REPAIR" for r in gate["reviews"])
        if repair_count and pass_count + min(repair_count, MAX_AUTO_REPAIR_TARGETS) >= MIN_FINAL_CARDS:
            batch, repaired_ids = repair_candidates(client, state, batch, gate, round_index)
            gate = gate_candidates(client, state, batch, round_index, pass_name="after_repair")

    cards = materialize_selected_cards(batch, gate)
    result = {
        "round": round_index,
        "batch_status": gate["batch_status"],
        "repaired_ids": repaired_ids,
        "cards": cards,
        "gate": gate,
        "machine_feedback": gate_feedback_for_regeneration(gate),
    }
    client.logger.save_artifact(f"round_{round_index:02d}_result.json", result)
    return result

## Internal Idea Human Gate state

در Unified Session کاربر سه انتخاب دارد: **Approve**, **Refine using liked directions**, یا **Reject all**. این کلاس فقط state ایده را نگه می‌دارد؛ UI یکپارچه بعد از Music engine تعریف می‌شود.

In [9]:
def show_cards(cards: List[Dict[str, Any]]):
    if not cards:
        print("هیچ Concept قابل ارائه‌ای باقی نماند.")
        return
    for i, c in enumerate(cards, 1):
        print("=" * 100)
        print(f"{i}) {c['title']}")
        print(c["one_line"])
        print("- Human truth:", c["human_truth"])
        print("- Central idea:", c["central_idea"])
        print("- Guest takeaway:", c["guest_takeaway"])
        print("- Territory:", c["territory_type"], "—", c["territory_proposition"])
        print("- Anchor score:", c["validation"]["anchor_score"],
              "| Portfolio score:", c["validation"]["portfolio_score"])
        if c["validation"]["risks"]:
            print("- Watch:", ", ".join(c["validation"]["risks"]))
        print()


@dataclass
class IdeaSession:
    client: Any
    state: IdeaRunState
    max_rounds: int = MAX_USER_ROUNDS
    round_index: int = 0
    machine_feedback: str = ""
    current_result: Optional[Dict[str, Any]] = None
    final_result: Optional[Dict[str, Any]] = None
    status: str = "NEW"  # NEW | RUNNING | WAITING_FOR_USER | APPROVED | EXHAUSTED

    def _finish_exhausted(self):
        self.status = "EXHAUSTED"
        self.final_result = {
            "status": "NO_APPROVAL_WITHIN_ROUND_BUDGET",
            "project_id": self.state.project_id,
            "run_id": self.client.logger.run_id,
            "brief_anchor": self.state.anchor,
            "feedback": self.state.feedback,
            "rounds_attempted": self.round_index,
        }
        self.client.logger.save_artifact("idea_final_result.json", self.final_result)
        return self.final_result

    def advance_until_user_gate(self):
        if self.status == "APPROVED":
            return self.current_result
        while self.round_index < self.max_rounds:
            self.round_index += 1
            self.status = "RUNNING"
            profile = round_profile(self.round_index)
            print(f"\n### IDEA ROUND {self.round_index}")
            print("Generator primary:", profile["generator"][0])
            print("Validator primary:", profile["validator"][0])
            result = run_generation_round(self.client, self.state, self.round_index, self.machine_feedback)
            self.current_result = result
            self.client.logger.print_summary()
            if result["batch_status"] == "PASS" and len(result["cards"]) >= MIN_FINAL_CARDS:
                self.status = "WAITING_FOR_USER"
                show_cards(result["cards"])
                return result
            self.machine_feedback = result["machine_feedback"]
            print("این Round به portfolio کافی نرسید؛ Round بعد با model strategy متفاوت اجرا می‌شود.")
        self._finish_exhausted()
        return self.current_result

    def approve(self, card_number: int):
        if self.status != "WAITING_FOR_USER" or not self.current_result:
            raise RuntimeError("IdeaSession is not waiting for a user decision.")
        idx = int(card_number) - 1
        cards = self.current_result["cards"]
        if idx < 0 or idx >= len(cards):
            raise ValueError(f"Concept number must be between 1 and {len(cards)}")
        approved = deepcopy(cards[idx])
        self.final_result = {
            "status": "APPROVED_BY_USER",
            "project_id": self.state.project_id,
            "run_id": self.client.logger.run_id,
            "approved_concept": approved,
            "round": self.round_index,
            "brief_anchor": self.state.anchor,
        }
        self.status = "APPROVED"
        self.client.logger.save_artifact("idea_final_result.json", self.final_result)
        return self.final_result

    def refine(self, feedback: str, liked_numbers: Optional[List[int]] = None):
        if self.status != "WAITING_FOR_USER" or not self.current_result:
            raise RuntimeError("IdeaSession is not waiting for a user decision.")
        feedback = (feedback or "").strip()
        if not feedback:
            raise ValueError("Refine/Reject requires explicit user feedback so the next round has a real direction.")
        cards = self.current_result["cards"]
        liked_numbers = liked_numbers or []
        liked_idx = set()
        for n in liked_numbers:
            idx = int(n)-1
            if idx < 0 or idx >= len(cards):
                raise ValueError(f"Liked concept number must be between 1 and {len(cards)}")
            liked_idx.add(idx)
        liked_cards = [deepcopy(c) for i,c in enumerate(cards) if i in liked_idx]
        rejected_cards = [deepcopy(c) for i,c in enumerate(cards) if i not in liked_idx]
        self.state.liked_in_session.extend(liked_cards)
        self.state.rejected_in_session.extend(rejected_cards)
        self.state.feedback = feedback
        self.machine_feedback = self.current_result.get("machine_feedback", "")
        self.status = "RUNNING"
        return self.advance_until_user_gate()

    def reject_all(self, feedback: str):
        return self.refine(feedback=feedback, liked_numbers=[])


def start_idea_session(client, project_brief: str = "", *, initial_context: str = "",
                       desired_feeling: str = "", seed: str = "", project_id: str = "unknown",
                       previous_ideas: Optional[List[Dict[str, Any]]] = None,
                       max_rounds: int = MAX_USER_ROUNDS) -> IdeaSession:
    state = IdeaRunState(
        project_brief=(project_brief or "").strip(), project_id=project_id,
        initial_context=(initial_context or "").strip(),
        desired_feeling=(desired_feeling or "").strip(), seed=(seed or "").strip(),
        previous_ideas=previous_ideas or [],
    )
    session = IdeaSession(client=client, state=state, max_rounds=max_rounds)
    compile_brief(client, state)  # once only, never repeated on user refinement rounds
    session.advance_until_user_gate()
    return session

## Mock client + self-test بدون API و بدون هزینه

این تست مسیرهای زیر را واقعاً اجرا می‌کند:
- compile → generate → gate
- repair conditional → gate دوباره
- schema validation
- token/cost log + summary
- تغییر model strategy بین round 1 و 2

Mock فقط برای تست notebook است؛ در اجرای واقعی استفاده نمی‌شود.

In [10]:
def _mock_anchor():
    return {
        "request_summary": "یک دورهمی کوچک و صمیمی با ایده‌ای انسانی و قابل‌تجربه.",
        "occasion": "دورهمی شبانه", "host_intention": "ساخت تجربه‌ای بافکر و غیرنمایشی",
        "audience": "حدود ۱۲ فرد خلاق", "social_situation": "کوچک، غیررسمی و گفت‌وگومحور",
        "facts": ["حدود ۱۲ مهمان", "دورهمی شبانه"],
        "constraints": ["تجربه نباید نمایشی یا پرزرق‌وبرق شود"],
        "explicit_references": [], "desired_feelings": ["صمیمیت", "کنجکاوی"],
        "desired_atmosphere": ["بافکر", "غیررسمی"], "known_dislikes": ["تظاهر", "زرق‌وبرق"],
        "core_subjects": ["بازگشت", "توجه دوباره"],
        "core_human_questions": ["چرا بعضی چیزها در بازگشت معنای تازه پیدا می‌کنند؟"],
        "core_emotions": ["کشف دوباره"], "core_tensions": [],
        "cultural_or_thematic_territories": ["بازدید دوباره از امر آشنا"],
        "must_preserve": ["صمیمیت", "رابطه با بازگشت و دیدن دوباره"],
        "must_avoid": ["گیمیک", "نمایش‌گری"], "allowed_creative_distance": "MODERATE",
        "assumptions": [], "unknowns": ["مکان دقیق", "ترکیب زبان مهمان‌ها"]
    }


def _mock_candidates(round_index=1):
    types = ["MEMORY","ATTENTION","TEMPORAL","SOCIAL","RITUAL","PHILOSOPHICAL"]
    ideas = [
        ("ردی که می‌ماند", "آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند."),
        ("دیدنِ بار دوم", "آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند."),
        ("فاصله‌ی میان دو دیدار", "معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند."),
        ("زبان مشترکِ کوچک", "چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند."),
        ("بازگشت به یک حرکت ساده", "تکرار یک آیین کوچک می‌تواند معنای رابطه را بدون توضیح حفظ کند."),
        ("همان چیز، آدم دیگر", "بازگشت نشان می‌دهد که ثبات موضوع و تغییر انسان می‌توانند همزمان واقعی باشند."),
    ]
    c=[]
    for i, ((title, truth), tp) in enumerate(zip(ideas, types),1):
        cid=f"r{round_index}_candidate_{i:02d}"
        c.append({
            "candidate_id":cid,"territory_type":tp,
            "territory_proposition":truth,"core_observation":truth,
            "title":title,"one_line":truth,"human_truth":truth,
            "central_idea":truth,"guest_takeaway":"امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.",
            "why_from_anchor":[{"field":"core_subjects","connection":"مستقیماً از بازگشت و توجه دوباره می‌آید."}],
            "conceptual_territory":["بازگشت","توجه"],"tone":["صمیمی","متفکر"],
            "multi_domain_potential":{
                "music":"بازگشت یک موتیف با معنای تازه","menu":"آشنایی که از زاویه تازه دیده می‌شود",
                "media":"بازدید دوباره از تصویر آشنا","art":"رد زمان روی امر آشنا","article":"روان‌شناسی توجه و بازگشت"
            },
            "must_preserve":["صمیمیت"],"must_avoid":["گیمیک"],"conceptual_boundaries":["به تم نوستالژی تقلیل پیدا نکند"]
        })
    return {"candidates":c}


def _mock_gate(candidates, force_repair=False):
    reviews=[]
    for i,c in enumerate(candidates):
        status="PASS"
        failures=[]
        if force_repair and i >= 2:
            status="REPAIR" if i < 4 else "DROP"
            failures=["USER_RECOGNITION_FAIL"] if status=="REPAIR" else ["OFF_BRIEF"]
        reviews.append({
            "candidate_id":c["candidate_id"],"status":status,
            "abstraction_level":"CONCEPT" if status!="DROP" else "BORDERLINE",
            "survives_execution_removal":status!="DROP","anchor_score":4 if status!="DROP" else 1,
            "user_recognition":status=="PASS","works_if_opted_out":True,"works_if_not_understood":True,
            "multi_domain_capable":True,"pressure_risk":"NONE","insider_code_risk":"NONE",
            "failure_codes":failures,"anchor_fields":["core_subjects"],
            "scores":{"human_truth":4,"conceptual_strength":4,"generativity":4,"guest_usability":5,"distinctness":4},
            "reason":"Mock validation"
        })
    pass_ids=[r["candidate_id"] for r in reviews if r["status"]=="PASS"]
    selected=pass_ids[:4]
    status="PASS" if len(selected)>=3 else "NEEDS_REPAIR"
    return {"batch_status":status,"reviews":reviews,"selected_ids":selected,
            "portfolio_note":"Mock portfolio", "unregistered_risks":[]}


class MockOpenRouterClient:
    def __init__(self, logger: RunLogger, force_repair_once=False):
        self.logger=logger
        self.force_repair_once=force_repair_once
        self.gate_calls=0

    def chat_json(self, *, stage, round_index, system_prompt, user_payload, model_chain,
                  schema, temperature, max_tokens, agent_goal=""):

        model=model_chain[0]
        if stage=="brief_compiler": out=_mock_anchor()
        elif stage=="concept_studio": out=_mock_candidates(round_index)
        elif stage=="concept_gate":
            self.gate_calls+=1
            force=self.force_repair_once and self.gate_calls==1
            out=_mock_gate(user_payload["CANDIDATES"], force_repair=force)
        elif stage=="candidate_repair":
            repaired=[]
            for t in user_payload["TARGETS"]:
                cand=deepcopy(t["candidate"])
                cand["one_line"] = cand["human_truth"]
                repaired.append({"candidate_id":cand["candidate_id"],"changed_fields":["one_line"],"candidate":cand})
            out={"repaired":repaired}
        else: raise ValueError(stage)
        jsonschema_validate(out, schema)
        usage={"prompt_tokens":100,"completion_tokens":50,"total_tokens":150,
               "reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.001,"cost_source":"mock"}
        rec={"status":"ok","stage":stage,"agent_goal":agent_goal,"round":round_index,"requested_model":model,"actual_model":model,
             "format_mode":"mock","latency_seconds":0.001,"system_prompt":system_prompt,"user_payload":user_payload,
             "raw_output":compact_json(out),"parsed_output":out,"usage":usage,"generation_id":"mock"}
        self.logger.log(rec)
        return out,rec



def run_idea_core_self_test():
    brief="""یک دورهمی کوچک شبانه برای حدود ۱۲ نفر از افراد خلاق. فضا صمیمی، بافکر و غیررسمی باشد. تجربه نمایشی یا پرزرق‌وبرق نباشد."""
    seed="چیزهایی که فقط وقتی دوباره به آن‌ها برمی‌گردیم معنای تازه پیدا می‌کنند"

    log1=RunLogger(run_id="SELFTEST_IDEA_"+uuid.uuid4().hex[:6])
    client1=MockOpenRouterClient(log1, force_repair_once=False)
    sess=start_idea_session(client1, brief, desired_feeling="صمیمیت و کشف دوباره", seed=seed, max_rounds=3)
    assert sess.status=="WAITING_FOR_USER" and sess.round_index==1
    # User likes #2 but asks for a change. This must become positive guidance, not rejection.
    sess.refine("جهت دوم را دوست دارم، اما کمتر نوستالژیک و اجتماعی‌ترش کن.", liked_numbers=[2])
    assert sess.status=="WAITING_FOR_USER" and sess.round_index==2
    assert len(sess.state.liked_in_session)==1
    assert "کمتر نوستالژیک" in sess.state.feedback
    # Verify round-2 generator payload actually received liked signal and feedback.
    r2=[r for r in log1.records if r.get("status")=="ok" and r.get("stage")=="concept_studio" and r.get("round")==2][-1]
    assert r2["user_payload"]["SESSION_LIKED"]
    assert "کمتر نوستالژیک" in r2["user_payload"]["USER_FEEDBACK"]
    approved=sess.approve(1)
    assert approved["status"]=="APPROVED_BY_USER"
    assert round_profile(1)["generator"][0] != round_profile(2)["generator"][0]
    print("✅ IDEA CORE SELF-TEST PASSED")
    return True

run_idea_core_self_test()

### IDEA ROUND 1
Generator primary: anthropic/claude-sonnet-5
Validator primary: openai/gpt-5.6-sol

=== DROP TOKEN / COST SUMMARY ===
Project: unknown
Run: SELFTEST_IDEA_f02aef
Successful model calls: 3
Failed attempts: 0 | billed attempts: 3
Input tokens (all billed attempts): 300
OUTPUT tokens (all billed attempts): 150
Reasoning tokens: 0
Total tokens: 450
Cached input tokens: 0
Cost USD (all billed attempts): 0.003
Log: drop_idea_runs/SELFTEST_IDEA_f02aef/model_calls.jsonl

,calls,prompt_tokens,completion_tokens,reasoning_tokens,cached_tokens,total_tokens,cost_usd,web_search_requests,web_fetch_requests
brief_compiler,1.0,100.0,50.0,0.0,0.0,150.0,0.001,0.0,0.0
concept_gate,1.0,100.0,50.0,0.0,0.0,150.0,0.001,0.0,0.0
concept_studio,1.0,100.0,50.0,0.0,0.0,150.0,0.001,0.0,0.0

====================================================================================================
1) ردی که می‌ماند
آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Human truth: آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Central idea: آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: MEMORY — آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Anchor score: 4 | Portfolio score: 4.1

====================================================================================================
2) دیدنِ بار دوم
آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Human truth: آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Central idea: آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: ATTENTION — آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Anchor score: 4 | Portfolio score: 4.1

====================================================================================================
3) فاصله‌ی میان دو دیدار
معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Human truth: معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Central idea: معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: TEMPORAL — معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Anchor score: 4 | Portfolio score: 4.1

====================================================================================================
4) زبان مشترکِ کوچک
چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Human truth: چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Central idea: چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: SOCIAL — چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Anchor score: 4 | Portfolio score: 4.1


### IDEA ROUND 2
Generator primary: openai/gpt-5.6-sol
Validator primary: anthropic/claude-sonnet-5

=== DROP TOKEN / COST SUMMARY ===
Project: unknown
Run: SELFTEST_IDEA_f02aef
Successful model calls: 5
Failed attempts: 0 | billed attempts: 5
Input tokens (all billed attempts): 500
OUTPUT tokens (all billed attempts): 250
Reasoning tokens: 0
Total tokens: 750
Cached input tokens: 0
Cost USD (all billed attempts): 0.005
Log: drop_idea_runs/SELFTEST_IDEA_f02aef/model_calls.jsonl

,calls,prompt_tokens,completion_tokens,reasoning_tokens,cached_tokens,total_tokens,cost_usd,web_search_requests,web_fetch_requests
brief_compiler,1.0,100.0,50.0,0.0,0.0,150.0,0.001,0.0,0.0
concept_gate,2.0,200.0,100.0,0.0,0.0,300.0,0.002,0.0,0.0
concept_studio,2.0,200.0,100.0,0.0,0.0,300.0,0.002,0.0,0.0

====================================================================================================
1) ردی که می‌ماند
آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Human truth: آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Central idea: آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: MEMORY — آدم‌ها هنگام بازگشت، تغییر خودشان را هم در چیزهای آشنا می‌بینند.
- Anchor score: 4 | Portfolio score: 4.1

====================================================================================================
2) دیدنِ بار دوم
آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Human truth: آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Central idea: آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: ATTENTION — آشنایی گاهی باعث ندیدن می‌شود و بازگشت می‌تواند توجه را تازه کند.
- Anchor score: 4 | Portfolio score: 4.1

====================================================================================================
3) فاصله‌ی میان دو دیدار
معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Human truth: معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Central idea: معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: TEMPORAL — معنا می‌تواند در فاصله‌ی زمانی میان دو مواجهه رشد کند.
- Anchor score: 4 | Portfolio score: 4.1

====================================================================================================
4) زبان مشترکِ کوچک
چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Human truth: چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Central idea: چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Guest takeaway: امر آشنا می‌تواند با توجه دوباره معنای تازه پیدا کند.
- Territory: SOCIAL — چیزهای آشنا میان آدم‌ها می‌توانند به نشانه‌های رابطه تبدیل شوند.
- Anchor score: 4 | Portfolio score: 4.1

✅ IDEA CORE SELF-TEST PASSED

True

## ورودی‌های Unified Session

همهٔ ورودی‌های زیر به‌جز اینکه **حداقل یکی** پر باشد اختیاری‌اند. اگر brief کامل داری، فقط `project_brief` کافی است. اگر brief رسمی نداری، می‌توانی فقط context، حس موردنظر، seed یا ایده‌های قبلی را بدهی. هیچ فیلد خالی توسط سیستم حدس زده نمی‌شود.

In [11]:
# ---- USER INPUTS — edit these ----
project_brief = """
یک دورهمی کوچک شبانه برای حدود ۱۲ نفر از افراد خلاق.
فضا صمیمی، بافکر و غیررسمی باشد و تجربه نمایشی یا پرزرق‌وبرق نشود.
""".strip()   # optional

initial_context = ""  # optional: هر context آزاد درباره میزبان/جمع/موقعیت
desired_feeling = "صمیمیت، کنجکاوی و کشف دوباره"  # optional
seed = "چیزهایی که فقط وقتی دوباره به آن‌ها برمی‌گردیم معنای تازه پیدا می‌کنند"  # optional

# optional. These are prior ideas supplied by the user; compact fields are enough.
previous_ideas = [
    {
        "title": "فاصله‌ی لازم",
        "central_idea": "گاهی فاصله‌گرفتن باعث دیدن دوباره‌ی امر آشنا می‌شود.",
        "human_truth": "آدم‌ها گاهی زمانی معنای چیزی را بهتر می‌فهمند که مدتی از آن دور شده باشند.",
        "guest_takeaway": "فاصله می‌تواند بخشی از دیدن باشد."
    }
]

# Optional practical context for music research only. It never replaces the approved Concept.
music_context = ""  # e.g. گفتگو باید راحت بماند، محیط کافه/خانه، شدت صدای مطلوب...

## تعریف‌های داخلی ادامه دارند؛ اجرای واقعی فقط در انتهای Notebook است

برای جلوگیری از دو Session جدا، اینجا چیزی اجرا نمی‌شود. بعد از تعریف موتور Music، سلول **Unified Real Run** یک Session را از Idea تا Music اجرا می‌کند.

In [12]:
# No separate Idea run here. Use the Unified Real Run near the end of the notebook.

## Backend note
همین state machine را می‌توان بدون widget نیز با متدهای `DropSession` کنترل کرد.

In [13]:
# Backend/manual API examples are provided with submit_drop_decision(...) in the Unified section below.

## خواندن log و summary

In [14]:
def load_run_log(run_dir: str):
    run_dir = Path(run_dir)
    rows=[]
    p=run_dir/"model_calls.jsonl"
    if p.exists():
        with p.open("r",encoding="utf-8") as f:
            for line in f:
                if line.strip(): rows.append(json.loads(line))
    return rows

# Example after a real run:
# print(logger.dir)
# logger.print_summary()
# log_rows = load_run_log(logger.dir)
# display(pd.DataFrame([{
#     "stage":r.get("stage"), "round":r.get("round"), "model":r.get("actual_model"),
#     "input":r.get("usage",{}).get("prompt_tokens"),
#     "output":r.get("usage",{}).get("completion_tokens"),
#     "total":r.get("usage",{}).get("total_tokens"),
#     "cost_usd":r.get("usage",{}).get("cost_usd"),
# } for r in log_rows if r.get("status")=="ok"]))

## Design notes — Idea half of the unified flow

- Normal Idea path = 3 model calls.
- Context Framer + Brief Anchor → `Brief Compiler`.
- Territory Explorer + Concept Builder → `Concept Studio`.
- Abstraction + Anchor + Guest Usability + Diversity + Critic → `Adversarial Concept Gate`.
- Candidate Repair is conditional and has a single repair budget.
- `liked_in_session`, `rejected_in_session`, and latest `feedback` remain separate signals.
- Brief Anchor is compiled once and reused through all user refinement rounds.

# Internal continuation — Music Deep Research after Concept approval

این قسمت API/Validatorهای موسیقی را تعریف می‌کند، اما **Session جداگانه‌ای برای کاربر ایجاد نمی‌کند**. `DropSession.approve_concept(...)` بعد از تأیید ایده، همین functions را خودکار فراخوانی می‌کند.

مسیر عادی Music = web-grounded research → deterministic identity verification → cross-model evidence gate → validated listening list.

### Genius + creator-evidence policy

- Genius is a preferred source for lyric pages and annotation context.
- **Genius Verified / explicitly attributable artist annotations** can count as direct creator commentary.
- Ordinary user/community annotations are secondary context only.
- For Iranian music, where Genius coverage may be sparse, direct Persian interviews/official artist material are equally valid primary evidence.
- The notebook stores paraphrases and links, not full copyrighted lyrics.

In [15]:
# ---------- Music quality / cost knobs ----------
MUSIC_RESEARCH_TARGET = 10
MUSIC_GAP_TARGET = 5
MUSIC_MIN_FINAL = 6
MUSIC_TARGET_FINAL = 8
MUSIC_MAX_FINAL = 10
MUSIC_MAX_USER_ROUNDS = 3
MUSIC_ENABLE_AUTO_GAP_FILL = True

MUSIC_TARGET_MIN_IRANIAN = 2
MUSIC_TARGET_MIN_INTERNATIONAL = 2
MUSIC_TARGET_MIN_INSTRUMENTAL = 2
MUSIC_TARGET_MIN_VOCAL = 2

# V7.6 server-tool profiles: only documented server-tool parameters are sent.
# max_tool_calls caps search+fetch tool turns in one research request.
MUSIC_WEB_PROFILES = {
    "lean": {
        "engine": "exa", "max_results": 5, "max_total_results": 15,
        "max_tool_calls": 5, "fetch_engine": "openrouter", "fetch_max_content_tokens": 3500,
    },
    "balanced": {
        "engine": "exa", "max_results": 6, "max_total_results": 30,
        "max_tool_calls": 8, "fetch_engine": "openrouter", "fetch_max_content_tokens": 5000,
    },
    "deep": {
        "engine": "exa", "max_results": 8, "max_total_results": 40,
        "max_tool_calls": 10, "fetch_engine": "openrouter", "fetch_max_content_tokens": 6500,
    },
}
MUSIC_WEB_PROFILE = "balanced"

MUSIC_MAX_TOKENS = {
    "web_dossier": 5200,
    "structurer": 5200,
    "gate": 4200,
    "gap_web_dossier": 3200,
    "gap_structurer": 3400,
    "gap_gate": 2600,
}

# Cross-family creative research / judging. Structuring is deliberately cheap and non-creative.
MUSIC_MODEL_STRATEGY = {
    "round_1": {
        "research": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "google/gemini-3.6-flash"],
        "structurer": ["openai/gpt-5.6-luna", "google/gemini-3.6-flash"],
        "validator": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.6-flash"],
        "gap_research": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.6-flash"],
        "gap_structurer": ["openai/gpt-5.6-luna", "google/gemini-3.6-flash"],
        "gap_validator": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "google/gemini-3.6-flash"],
    },
    "round_2": {
        "research": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.6-flash"],
        "structurer": ["openai/gpt-5.6-luna", "google/gemini-3.6-flash"],
        "validator": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "google/gemini-3.6-flash"],
        "gap_research": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "google/gemini-3.6-flash"],
        "gap_structurer": ["openai/gpt-5.6-luna", "google/gemini-3.6-flash"],
        "gap_validator": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.6-flash"],
    },
    "round_3": {
        "research": ["anthropic/claude-opus-5", "anthropic/claude-sonnet-5", "openai/gpt-5.6-sol"],
        "structurer": ["openai/gpt-5.6-luna", "google/gemini-3.6-flash"],
        "validator": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.6-flash"],
        "gap_research": ["anthropic/claude-sonnet-5", "openai/gpt-5.6-sol", "google/gemini-3.6-flash"],
        "gap_structurer": ["openai/gpt-5.6-luna", "google/gemini-3.6-flash"],
        "gap_validator": ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.6-flash"],
    },
}

# Fallback estimates only; OpenRouter usage.cost remains authoritative.
FALLBACK_PRICE_USD_PER_M.update({
    "openai/gpt-5.6-luna": (0.20, 1.20),
    "openai/gpt-5.6-sol": (2.00, 10.00),
    "anthropic/claude-sonnet-5": (2.00, 10.00),
    "anthropic/claude-opus-5": (5.00, 25.00),
    "google/gemini-3.6-flash": (0.75, 3.75),
})

## Robust web-grounded research transport (V7.6)

مشکل V7.5 این بود که یک call طولانی باید **هم web-search انجام می‌داد و هم یک JSON بزرگ و nested تولید می‌کرد**. اگر syntax JSON خراب می‌شد، کل research دور ریخته می‌شد و fallbackهای گران تکرار می‌شدند.

V7.6 این دو مسئولیت را جدا می‌کند:

1. **Web Evidence Scout**: Claude/GPT با `openrouter:web_search` و `openrouter:web_fetch` یک dossier متنیِ citation-rich می‌سازد؛ JSON لازم نیست.
2. **Evidence Structurer**: GPT-5.6 Luna (cheap) بدون web، dossier را با strict JSON Schema به `MUSIC_RESEARCH_SCHEMA` تبدیل می‌کند.
3. سپس identity verification و Music Gate مثل قبل اجرا می‌شوند.

این یک call ارزان اضافه می‌کند، اما retry storm چند-callی ناشی از malformed JSON را حذف می‌کند و معمولاً هزینه‌ی واقعی را پایین‌تر و reliability را بالاتر می‌برد.

In [16]:
def _usage_from_response_v76(data: Dict[str, Any], requested_model: str) -> Dict[str, Any]:
    u = data.get("usage") or {}
    pdet = u.get("prompt_tokens_details") or u.get("input_tokens_details") or {}
    cdet = u.get("completion_tokens_details") or u.get("output_tokens_details") or {}
    prompt = int(u.get("prompt_tokens") or u.get("input_tokens") or 0)
    completion = int(u.get("completion_tokens") or u.get("output_tokens") or 0)
    total = int(u.get("total_tokens") or (prompt + completion))
    cost = u.get("cost")
    cost_source = "openrouter_usage" if cost is not None else "fallback_estimate"
    if cost is None:
        inp, out = FALLBACK_PRICE_USD_PER_M.get(requested_model, (0.0, 0.0))
        cost = prompt * inp / 1_000_000 + completion * out / 1_000_000
    stu = u.get("server_tool_use") or {}
    return {
        "prompt_tokens": prompt,
        "completion_tokens": completion,
        "total_tokens": total,
        "reasoning_tokens": int(cdet.get("reasoning_tokens") or u.get("reasoning_tokens") or 0),
        "cached_tokens": int(pdet.get("cached_tokens") or pdet.get("cached_input_tokens") or 0),
        "cost_usd": float(cost or 0.0),
        "cost_source": cost_source,
        "web_search_requests": int(stu.get("web_search_requests") or 0),
        "web_fetch_requests": int(stu.get("web_fetch_requests") or 0),
    }

# Backward-compatible alias used by older helper code below.
_usage_from_response_v72 = _usage_from_response_v76


def _url_annotations(message: Dict[str, Any]) -> List[Dict[str, Any]]:
    out = []
    for a in message.get("annotations") or []:
        if not isinstance(a, dict) or a.get("type") != "url_citation":
            continue
        u = a.get("url_citation") or {}
        if u.get("url"):
            out.append({"url": u.get("url"), "title": u.get("title"), "content": u.get("content")})
    return out


def _server_search_parameters(profile: Dict[str, Any]) -> Dict[str, Any]:
    # Send only documented server-tool fields; old plugin-only knobs (mode/max_characters/max_uses) are intentionally omitted.
    out = {}
    for k in ("engine", "max_results", "max_total_results"):
        if profile.get(k) is not None:
            out[k] = profile[k]
    return out


def _fetch_parameters(profile: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "engine": profile.get("fetch_engine", "openrouter"),
        "max_content_tokens": int(profile.get("fetch_max_content_tokens") or 5000),
    }


def _attempt_record(stage, agent_goal, round_index, model, started, *, status, data=None, text=None,
                    error=None, format_mode=None, user_payload=None, system_prompt=None, web=None):
    data = data or {}
    usage = _usage_from_response_v76(data, model) if data else {
        "prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,
        "cost_usd":0.0,"cost_source":"none","web_search_requests":0,"web_fetch_requests":0,
    }
    return {
        "status": status,
        "stage": stage,
        "agent_goal": agent_goal,
        "round": round_index,
        "requested_model": model,
        "actual_model": data.get("model") or model,
        "format_mode": format_mode,
        "latency_seconds": round(time.perf_counter() - started, 3),
        "system_prompt": system_prompt,
        "user_payload": user_payload,
        "raw_output": text,
        "error": error,
        "web_search": web,
        "usage": usage,
        "generation_id": data.get("id"),
    }


def chat_text_web(self, *, stage: str, round_index: int, system_prompt: str,
                  user_payload: Dict[str, Any], model_chain: List[str], max_tokens: int,
                  web_profile: Dict[str, Any], temperature: Optional[float] = None,
                  agent_goal: str = "") -> Tuple[str, Dict[str, Any]]:
    """Web-grounded TEXT research. No JSON parsing here by design."""
    user_text = compact_json(user_payload)
    catalog = self.available_models()
    chain = [m for m in model_chain if (not catalog or m in catalog)] or model_chain
    errors = []
    search_params = _server_search_parameters(web_profile)
    fetch_params = _fetch_parameters(web_profile)
    max_tool_calls = max(2, int(web_profile.get("max_tool_calls") or 8))

    for model in chain:
        payload = {
            "model": model,
            "messages": [{"role":"system","content":system_prompt},{"role":"user","content":user_text}],
            "max_tokens": max_tokens,
            "usage": {"include": True},
            "tools": [
                {"type": "openrouter:web_search", "parameters": search_params},
                {"type": "openrouter:web_fetch", "parameters": fetch_params},
            ],
            "max_tool_calls": max_tool_calls,
        }
        if temperature is not None and not model.startswith("openai/gpt-5.6"):
            payload["temperature"] = temperature
        started = time.perf_counter(); data = None; text = None
        try:
            r = requests.post(OPENROUTER_URL, headers=self.headers, json=payload, timeout=self.timeout)
            r.raise_for_status(); data = r.json()
            msg = data["choices"][0]["message"]
            text = _message_text(msg).strip()
            if len(text) < 400:
                raise ValueError(f"Web dossier too short ({len(text)} chars)")
            annotations = _url_annotations(msg)
            rec = _attempt_record(stage,agent_goal,round_index,model,started,status="ok",data=data,text=text,
                                  user_payload=user_payload,system_prompt=system_prompt,
                                  web={"server_tools":["openrouter:web_search","openrouter:web_fetch"],
                                       "search_parameters":search_params,"fetch_parameters":fetch_params,
                                       "max_tool_calls":max_tool_calls,"annotations":annotations})
            self.logger.log(rec)
            return text, rec
        except Exception as e:
            # If HTTP succeeded, data contains usage => failed-but-billed attempt is logged accurately.
            annotations = []
            try:
                if data:
                    annotations = _url_annotations(data["choices"][0]["message"])
            except Exception:
                pass
            rec = _attempt_record(stage,agent_goal,round_index,model,started,status="error",data=data,text=text,
                                  error=f"{type(e).__name__}: {e}",user_payload=user_payload,system_prompt=system_prompt,
                                  web={"server_tools":["openrouter:web_search","openrouter:web_fetch"],
                                       "search_parameters":search_params,"fetch_parameters":fetch_params,
                                       "max_tool_calls":max_tool_calls,"annotations":annotations})
            self.logger.log(rec); errors.append(rec["error"])
    raise RuntimeError(f"{stage} failed across web-research model fallbacks:\n" + "\n---\n".join(errors[-6:]))


def _try_optional_json_repair(text: str):
    try:
        from json_repair import repair_json
        repaired = repair_json(text or "", return_objects=False)
        return json.loads(repaired)
    except Exception:
        return None


def chat_json_strict(self, *, stage: str, round_index: int, system_prompt: str,
                     user_payload: Dict[str, Any], model_chain: List[str], schema: Dict[str, Any],
                     max_tokens: int, temperature: Optional[float] = None,
                     agent_goal: str = "") -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Strict schema-only call, used after research. One attempt/model; no expensive json_object/plain retry loop."""
    user_text = compact_json(user_payload)
    catalog = self.available_models()
    chain = [m for m in model_chain if (not catalog or m in catalog)] or model_chain
    errors = []
    for model in chain:
        payload = {
            "model": model,
            "messages": [{"role":"system","content":system_prompt},{"role":"user","content":user_text}],
            "max_tokens": max_tokens,
            "usage": {"include": True},
            "response_format": self._schema_response_format(stage.replace("-","_"), schema),
            # Important: do not route to a provider that silently ignores response_format/schema.
            "provider": {"require_parameters": True},
        }
        if temperature is not None and not model.startswith("openai/gpt-5.6"):
            payload["temperature"] = temperature
        started=time.perf_counter(); data=None; text=None
        try:
            r=requests.post(OPENROUTER_URL,headers=self.headers,json=payload,timeout=self.timeout)
            r.raise_for_status(); data=r.json(); text=_message_text(data["choices"][0]["message"])
            try:
                parsed=json.loads(_extract_json_text(text))
            except Exception:
                parsed=_try_optional_json_repair(text)
                if parsed is None:
                    raise
            jsonschema_validate(parsed,schema)
            rec=_attempt_record(stage,agent_goal,round_index,model,started,status="ok",data=data,text=text,
                                format_mode="strict_json_schema",user_payload=user_payload,system_prompt=system_prompt)
            rec["parsed_output"]=parsed
            self.logger.log(rec); return parsed,rec
        except Exception as e:
            rec=_attempt_record(stage,agent_goal,round_index,model,started,status="error",data=data,text=text,
                                error=f"{type(e).__name__}: {e}",format_mode="strict_json_schema",
                                user_payload=user_payload,system_prompt=system_prompt)
            self.logger.log(rec); errors.append(rec["error"])
    raise RuntimeError(f"{stage} failed across strict-structurer fallbacks:\n" + "\n---\n".join(errors[-6:]))


OpenRouterClient.chat_text_web = chat_text_web
OpenRouterClient.chat_json_strict = chat_json_strict

## Music research / validation schemas

In [17]:
SOURCE_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["source_type", "title", "url", "claim_types", "evidence"],
    "properties": {
        "source_type": {"type": "string", "enum": [
            "OFFICIAL", "LABEL", "REVIEW", "LYRICS", "PLATFORM", "DATABASE", "INTERVIEW", "PODCAST",
            "GENIUS_LYRICS", "GENIUS_ANNOTATION", "GENIUS_VERIFIED", "LINER_NOTES", "OTHER"
        ]},
        "title": {"type": "string"},
        "url": {"type": "string"},
        "claim_types": {"type": "array", "items": {"type": "string", "enum": [
            "IDENTITY", "SONIC", "LYRICAL", "CONTEXT", "CREATOR_INTENT"
        ]}},
        "evidence": {"type": "string"},
    },
}

SONIC_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["tempo_feel", "pulse_and_rhythm", "energy", "texture", "emotional_color", "intrusiveness"],
    "properties": {
        "tempo_feel": {"type": "string"},
        "pulse_and_rhythm": {"type": "string"},
        "energy": {"type": "string"},
        "texture": {"type": "string"},
        "emotional_color": {"type": "string"},
        "intrusiveness": {"type": "string", "enum": ["LOW", "MEDIUM", "HIGH", "UNKNOWN"]},
    },
}

GENIUS_RESEARCH_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["status", "song_url", "annotation_context_summary", "creator_direct_on_genius"],
    "properties": {
        "status": {"type": "string", "enum": ["FOUND_SONG_PAGE", "FOUND_ANNOTATIONS", "NOT_FOUND", "NOT_APPLICABLE"]},
        "song_url": {"type": ["string", "null"]},
        "annotation_context_summary": {"type": ["string", "null"]},
        "creator_direct_on_genius": {"type": "boolean"},
    },
}

CREATOR_COMMENTARY_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["status", "speaker", "role", "summary", "source_url", "source_kind"],
    "properties": {
        "status": {"type": "string", "enum": ["DIRECT_FOUND", "NOT_FOUND"]},
        "speaker": {"type": ["string", "null"]},
        "role": {"type": ["string", "null"], "enum": ["SINGER", "SONGWRITER", "COMPOSER", "PRODUCER", "BAND_MEMBER", "OTHER", None]},
        "summary": {"type": ["string", "null"]},
        "source_url": {"type": ["string", "null"]},
        "source_kind": {"type": ["string", "null"], "enum": [
            "GENIUS_VERIFIED", "GENIUS_ARTIST_ANNOTATION", "INTERVIEW", "OFFICIAL", "LINER_NOTES", "PODCAST", "OTHER", None
        ]},
    },
}

MUSIC_CANDIDATE_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["candidate_id", "title", "artist", "origin_bucket", "language", "vocal_type", "release_year",
                 "genre_tags", "sonic_profile", "lyrical_theme_summary", "genius_research", "creator_commentary",
                 "why_fit_concept", "why_fit_brief", "role_hypothesis", "sources", "research_confidence"],
    "properties": {
        "candidate_id": {"type": "string"},
        "title": {"type": "string"}, "artist": {"type": "string"},
        "origin_bucket": {"type": "string", "enum": ["IRANIAN", "INTERNATIONAL"]},
        "language": {"type": ["string", "null"]},
        "vocal_type": {"type": "string", "enum": ["INSTRUMENTAL", "VOCAL", "MIXED", "UNKNOWN"]},
        "release_year": {"type": ["integer", "null"]},
        "genre_tags": {"type": "array", "items": {"type": "string"}},
        "sonic_profile": SONIC_SCHEMA,
        "lyrical_theme_summary": {"type": ["string", "null"]},
        "genius_research": GENIUS_RESEARCH_SCHEMA,
        "creator_commentary": CREATOR_COMMENTARY_SCHEMA,
        "why_fit_concept": {"type": "string"}, "why_fit_brief": {"type": "string"},
        "role_hypothesis": {"type": "string"},
        "sources": {"type": "array", "items": SOURCE_SCHEMA, "minItems": 1},
        "research_confidence": {"type": "number", "minimum": 0, "maximum": 1},
    },
}

MUSIC_RESEARCH_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["research_direction", "search_strategy", "candidates", "research_gaps"],
    "properties": {
        "research_direction": {"type": "string"},
        "search_strategy": {"type": "array", "items": {"type": "string"}},
        "candidates": {"type": "array", "items": MUSIC_CANDIDATE_SCHEMA},
        "research_gaps": {"type": "array", "items": {"type": "string"}},
    },
}

JUDGMENT_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["candidate_id", "identity_status", "evidence_sufficiency", "sonic_score", "lyric_score",
                 "creator_evidence", "creator_context_score", "genius_check",
                 "anchor_score", "concept_score", "cultural_fit", "role_distinctness", "contradiction_risk",
                 "verdict", "reason"],
    "properties": {
        "candidate_id": {"type": "string"},
        "identity_status": {"type": "string", "enum": ["VERIFIED", "WEB_ONLY", "UNVERIFIED", "CONFLICT"]},
        "evidence_sufficiency": {"type": "string", "enum": ["STRONG", "ADEQUATE", "WEAK", "INSUFFICIENT"]},
        "sonic_score": {"type": "number", "minimum": 0, "maximum": 5},
        "lyric_score": {"type": ["number", "null"], "minimum": 0, "maximum": 5},
        "creator_evidence": {"type": "string", "enum": ["DIRECT", "NONE"]},
        "creator_context_score": {"type": ["number", "null"], "minimum": 0, "maximum": 5},
        "genius_check": {"type": "string", "enum": ["FOUND", "NOT_FOUND", "NOT_APPLICABLE"]},
        "anchor_score": {"type": "number", "minimum": 0, "maximum": 5},
        "concept_score": {"type": "number", "minimum": 0, "maximum": 5},
        "cultural_fit": {"type": "number", "minimum": 0, "maximum": 5},
        "role_distinctness": {"type": "number", "minimum": 0, "maximum": 5},
        "contradiction_risk": {"type": "string", "enum": ["NONE", "LOW", "MEDIUM", "HIGH"]},
        "verdict": {"type": "string", "enum": ["PASS", "REPAIR_EVIDENCE", "REJECT"]},
        "reason": {"type": "string"},
    },
}

MUSIC_GATE_SCHEMA = {
    "type": "object", "additionalProperties": False,
    "required": ["judgments", "portfolio_notes", "research_gaps", "needs_gap_fill"],
    "properties": {
        "judgments": {"type": "array", "items": JUDGMENT_SCHEMA},
        "portfolio_notes": {"type": "string"},
        "research_gaps": {"type": "array", "items": {"type": "string"}},
        "needs_gap_fill": {"type": "boolean"},
    },
}

## Research prompts — evidence first, no invented song facts

In [18]:
MUSIC_WEB_DOSSIER_PROMPT = r"""
You are the DROP Music Deep Research Scout. Use web search AND web fetch actively but economically.
Your output is an EVIDENCE DOSSIER in concise readable text — NOT JSON.
The dossier will be converted to strict JSON by a separate low-cost structurer, so prioritize evidence quality and exact URLs.

Ground every track in APPROVED_CONCEPT + BRIEF_ANCHOR. Research both IRANIAN and INTERNATIONAL music.
For each proposed track, use a stable card headed exactly `TRACK:` and cover:
- exact title + artist + origin + vocal/instrumental + release year only if evidenced;
- SOUND: tempo-feel, pulse/rhythm, energy, texture, emotional color, intrusiveness;
- for VOCAL/MIXED: lyrical theme and whether it supports or contradicts the Concept;
- GENIUS: actively search the song page; when useful fetch it. Distinguish community annotation from direct artist attribution;
- CREATOR COMMENTARY: search for singer/songwriter/composer/producer discussing this specific track. Genius Verified, attributable artist annotation, official notes, liner notes, interview or podcast may count. If none is found, write NOT_FOUND;
- why the track is specifically connected to the approved Concept and Brief, not merely the same mood;
- source list: exact URL + source type + which claim it supports + concise evidence.

Never invent a Genius URL, BPM, key, time signature, lyrics meaning, creator quote, or release fact.
Never reproduce full lyrics or long lyric quotes; paraphrase themes.
Prefer fewer well-grounded candidates to fabricated completeness, but aim for TARGET_COUNT strong candidates.
Use Persian for analysis text; keep artist/song titles exactly as published.
""".strip()

MUSIC_GAP_WEB_DOSSIER_PROMPT = r"""
You are the DROP Music Evidence Gap Researcher. Return a concise TEXT EVIDENCE DOSSIER, not JSON.
Research only the supplied GAPS, do not duplicate EXISTING_TRACKS, and remain grounded in APPROVED_CONCEPT + BRIEF_ANCHOR.
Apply the same identity/sonic/lyric/Genius/direct-creator evidence rules as the main scout.
Use web fetch when a discovered Genius/official/interview page needs inspection. NOT_FOUND is valid; fabrication is not.
""".strip()

MUSIC_STRUCTURER_PROMPT = r"""
You are the DROP Music Evidence Structurer. R0: NO WEB and NO NEW RESEARCH.
Convert WEB_DOSSIER + WEB_ANNOTATIONS into the exact MUSIC_RESEARCH_SCHEMA.

STRICT GROUNDING:
- Every factual field must be supported by the supplied dossier/annotations.
- Preserve artist/title spelling and URLs exactly when available.
- Do not create a source URL that is not in the dossier or annotations.
- If Genius was not actually found: genius_research.status=NOT_FOUND and song_url=null.
- A normal Genius/community annotation is NOT creator commentary.
- creator_commentary=DIRECT_FOUND only when the dossier explicitly attributes a statement to singer/songwriter/composer/producer/band member; otherwise NOT_FOUND with all detail fields null.
- For vocal/mixed tracks, lyrical_theme_summary must be a short paraphrase grounded in evidence. If lyric evidence is insufficient, exclude the track rather than infer.
- For instrumental tracks lyrical_theme_summary=null and Genius may be NOT_APPLICABLE.
- Keep source evidence concise. No prose outside JSON.
""".strip()

MUSIC_GAP_STRUCTURER_PROMPT = MUSIC_STRUCTURER_PROMPT

MUSIC_GATE_PROMPT = r"""
You are the DROP Music Evidence Gate. Adversarial, evidence-bound, no web in this step.
Judge only supplied research evidence + deterministic identity verification + PROJECT_BRIEF + BRIEF_ANCHOR + APPROVED_CONCEPT.
Do not invent missing audio properties, lyric meanings, Genius findings, or creator intent.

Core rules:
- Every PASS must remain recognizably linked to approved Concept and Brief Anchor; generic mood is insufficient.
- Instrumental: prioritize tempo-feel, pulse/rhythm, energy, texture and emotional character. lyric_score MUST be null.
- Vocal/Mixed: evaluate all sonic dimensions AND lyrical meaning. lyric_score must be numeric; missing/weak lyric evidence => REPAIR_EVIDENCE or REJECT.
- Genius is a preferred lyric/annotation evidence source, not an authority that turns community annotation into creator intent.
- creator_evidence=DIRECT only when creator_commentary.status=DIRECT_FOUND and source attribution is genuinely primary/direct. Otherwise NONE.
- If direct creator commentary exists, creator_context_score measures how that statement supports/conflicts with the Concept interpretation. If no direct statement exists, creator_context_score MUST be null. Absence alone does not fail a track.
- If direct creator commentary contradicts the proposed interpretation, reflect that in contradiction_risk and verdict.
- A lyric theme conflicting with explicit constraints/desired feelings/concept meaning is REJECT even if sound fits.
- identity_status VERIFIED when deterministic verification succeeded; WEB_ONLY only when credible web evidence is sufficient; CONFLICT when evidence disagrees; UNVERIFIED when identity is not established.
- Evidence sufficiency is a gate, not popularity.
- Do not lower the bar to hit Iranian/international or vocal/instrumental quotas. Name gaps instead.

Verdicts:
PASS = evidence and fit are adequate for final playlist.
REPAIR_EVIDENCE = potentially strong but a specific missing evidence item prevents PASS.
REJECT = off-concept, contradictory, weak, generic, duplicate-level, or identity/evidence failure.

Return compact Persian reasons in exact JSON only.
""".strip()

## Free / deterministic track identity verification and portfolio scoring

In [ ]:
# ============================================================
# V7.9 — WEB-ONLY music identity helper
# Discovery is ONLY web research. This helper only checks an already-discovered
# title/artist against iTunes for identity/listen URL; it never discovers candidates.
# ============================================================

def normalize_music_text(s: str) -> str:
    return re.sub(r"[^a-z0-9\u0600-\u06ff]+", "", (s or "").casefold())


def _close_name(a: str, b: str) -> bool:
    a, b = normalize_music_text(a), normalize_music_text(b)
    if not a or not b:
        return False
    return a in b or b in a


def itunes_music_lookup(track_name: str, artist_name: str, limit: int = 4) -> List[Dict[str, Any]]:
    q = requests.utils.quote(f"{track_name} {artist_name}")
    url = f"https://itunes.apple.com/search?term={q}&entity=song&limit={int(limit)}"
    r = requests.get(url, timeout=(10, 30), headers={"User-Agent":"DROP-MusicResearch/7.9"})
    r.raise_for_status()
    data = r.json()
    return data.get("results", [])[:limit]


def verify_track_identity_lean(track: Dict[str, Any]) -> Dict[str, Any]:
    """Web-only identity check for an ALREADY discovered track. No dataset/embedding retrieval."""
    title, artist = track.get("title",""), track.get("artist","")
    errors, itunes = [], []
    try:
        itunes = itunes_music_lookup(title, artist)
    except Exception as e:
        errors.append(f"itunes:{type(e).__name__}:{e}")
    i_ok = any(
        _close_name(title, x.get("trackName","")) and
        _close_name(artist, x.get("artistName",""))
        for x in itunes
    )
    listen_url = next((x.get("trackViewUrl") for x in itunes if x.get("trackViewUrl")), None)
    return {
        "identity_verified": bool(i_ok),
        "itunes": itunes[:2],
        "errors": errors,
        "listen_url": listen_url,
        "verification_scope": "itunes_identity_only_not_discovery",
    }


def verify_music_pool(candidates: List[Dict[str, Any]], logger=None, round_index: int = 0) -> List[Dict[str, Any]]:
    out=[]
    for i,c in enumerate(candidates,1):
        print(f"identity {i}/{len(candidates)}: {c.get('artist')} — {c.get('title')}")
        x=deepcopy(c)
        try:
            x["identity_verification"]=verify_track_identity_lean(x)
        except Exception as e:
            x["identity_verification"]={
                "identity_verified":False,"itunes":[],"errors":[f"{type(e).__name__}: {e}"],
                "listen_url":None,"verification_scope":"itunes_identity_only_not_discovery"
            }
        out.append(x)
    return out

## Music pipeline — normal 2 calls, conditional gap-fill

In [20]:
def _music_round_profile(round_index: int) -> Dict[str, List[str]]:
    idx = min(max(int(round_index), 1), 3)
    return MUSIC_MODEL_STRATEGY[f"round_{idx}"]


def _compact_anchor_for_music(anchor: Dict[str, Any]) -> Dict[str, Any]:
    keys = ["request_summary", "occasion", "host_intention", "audience", "social_situation", "constraints",
            "explicit_references", "desired_feelings", "desired_atmosphere", "known_dislikes", "core_subjects",
            "core_emotions", "core_tensions", "cultural_or_thematic_territories", "must_preserve", "must_avoid"]
    return {k: anchor.get(k) for k in keys}


def _compact_concept_for_music(c: Dict[str, Any]) -> Dict[str, Any]:
    keys = ["title", "one_line", "human_truth", "central_idea", "guest_takeaway", "territory_type",
            "territory_proposition", "conceptual_territory", "tone", "desired_feelings", "must_preserve", "must_avoid"]
    return {k: c.get(k) for k in keys if k in c}


def validate_music_research_local(research: Dict[str, Any], min_candidates: int = 1):
    jsonschema_validate(research, MUSIC_RESEARCH_SCHEMA)
    cands = research.get("candidates", [])
    if len(cands) < min_candidates:
        raise ValueError(f"Music research returned {len(cands)} candidates; expected at least {min_candidates}.")
    ids = [x.get("candidate_id") for x in cands]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate music candidate_id")
    for c in cands:
        vocal = c.get("vocal_type") in {"VOCAL", "MIXED"}
        gr = c.get("genius_research") or {}
        cc = c.get("creator_commentary") or {}
        if vocal and gr.get("status") == "NOT_APPLICABLE":
            raise ValueError(f"Vocal/Mixed {c.get('candidate_id')} must attempt Genius research; NOT_APPLICABLE is invalid")
        if gr.get("status") in {"FOUND_SONG_PAGE", "FOUND_ANNOTATIONS"}:
            url = (gr.get("song_url") or "").casefold()
            if not url or "genius.com" not in url:
                raise ValueError(f"{c.get('candidate_id')} claims Genius evidence without a genius.com song_url")
        if cc.get("status") == "DIRECT_FOUND":
            if not (cc.get("speaker") and cc.get("summary") and cc.get("source_url") and cc.get("source_kind")):
                raise ValueError(f"{c.get('candidate_id')} DIRECT_FOUND creator commentary is missing attribution/source")
        elif any(cc.get(k) for k in ("speaker", "summary", "source_url", "source_kind")):
            raise ValueError(f"{c.get('candidate_id')} creator commentary fields must be null when status=NOT_FOUND")
    return True


def validate_music_gate_local(gate: Dict[str, Any], candidates: List[Dict[str, Any]]):
    jsonschema_validate(gate, MUSIC_GATE_SCHEMA)
    ids = {x["candidate_id"] for x in candidates}
    jids = [j["candidate_id"] for j in gate.get("judgments", [])]
    if len(jids) != len(set(jids)):
        raise ValueError("Duplicate music judgment candidate_id")
    missing = ids - set(jids)
    if missing:
        raise ValueError(f"Music gate omitted candidates: {sorted(missing)}")
    for j in gate.get("judgments", []):
        c = next(x for x in candidates if x["candidate_id"] == j["candidate_id"])
        if c.get("vocal_type") == "INSTRUMENTAL" and j.get("lyric_score") is not None:
            raise ValueError(f"Instrumental {j['candidate_id']} must have lyric_score=null")
        if c.get("vocal_type") in {"VOCAL", "MIXED"} and j.get("lyric_score") is None:
            raise ValueError(f"Vocal/Mixed {j['candidate_id']} must have numeric lyric_score")
        creator_found = (c.get("creator_commentary") or {}).get("status") == "DIRECT_FOUND"
        if creator_found:
            if j.get("creator_evidence") != "DIRECT" or j.get("creator_context_score") is None:
                raise ValueError(f"{j['candidate_id']} direct creator evidence must be acknowledged and scored")
        else:
            if j.get("creator_evidence") != "NONE" or j.get("creator_context_score") is not None:
                raise ValueError(f"{j['candidate_id']} cannot invent creator evidence/score")
    return True


def _compact_web_annotations(rec: Dict[str, Any], limit: int = 30) -> List[Dict[str, Any]]:
    anns = (((rec or {}).get("web_search") or {}).get("annotations") or [])[:limit]
    out=[]
    for x in anns:
        out.append({
            "url": x.get("url"), "title": x.get("title"),
            "content": (x.get("content") or "")[:1200],
        })
    return out


def research_music_pool(client, *, project_brief: str, brief_anchor: Dict[str, Any], approved_concept: Dict[str, Any],
                        round_index: int, user_context: str = "", feedback: str = "",
                        existing_tracks: Optional[List[Dict[str, Any]]] = None,
                        gaps: Optional[List[str]] = None, gap_mode: bool = False) -> Dict[str, Any]:
    profile = _music_round_profile(round_index)
    web_profile = deepcopy(MUSIC_WEB_PROFILES[MUSIC_WEB_PROFILE])
    target = MUSIC_GAP_TARGET if gap_mode else MUSIC_RESEARCH_TARGET
    raw_prompt = MUSIC_GAP_WEB_DOSSIER_PROMPT if gap_mode else MUSIC_WEB_DOSSIER_PROMPT
    web_stage = "music_gap_web_research" if gap_mode else "music_web_research"
    struct_stage = "music_gap_research_structurer" if gap_mode else "music_research_structurer"
    research_chain = profile["gap_research"] if gap_mode else profile["research"]
    struct_chain = profile["gap_structurer"] if gap_mode else profile["structurer"]

    base_payload = {
        "APPROVED_CONCEPT": _compact_concept_for_music(approved_concept),
        "BRIEF_ANCHOR": _compact_anchor_for_music(brief_anchor),
        "USER_CONTEXT": user_context or "",
        "USER_FEEDBACK": feedback or "",
        "TARGET_COUNT": target,
        "RESEARCH_REQUIREMENTS": {
            "iranian_and_international": True,
            "instrumental_sonic_priority": "rhythm/pulse/tempo-feel/energy/texture/emotion",
            "vocal_extra_requirement": "lyrical meaning must be evidenced and compatible",
            "genius_policy": "actively locate/fetch Genius for vocal/mixed when available; community annotation != creator statement",
            "creator_commentary_policy": "search attributable direct creator commentary; NOT_FOUND is valid",
            "lyrics_policy": "paraphrase themes only; no full lyrics",
        },
        "EXISTING_TRACKS": [{"title":x.get("title"),"artist":x.get("artist")} for x in (existing_tracks or [])],
        "GAPS": gaps or [],
    }

    dossier, web_rec = client.chat_text_web(
        stage=web_stage, round_index=round_index, system_prompt=raw_prompt,
        user_payload=base_payload, model_chain=research_chain,
        max_tokens=MUSIC_MAX_TOKENS["gap_web_dossier" if gap_mode else "web_dossier"],
        web_profile=web_profile, temperature=0.2,
        agent_goal=("Targeted evidence web research for missing music coverage" if gap_mode else
                    "Web evidence research for Iranian + international music, Genius and creator commentary"),
    )

    # Save human-readable research even if the following structuring step later fails.
    dossier_name = f"music_round_{round_index:02d}_{'gap_' if gap_mode else ''}web_dossier.txt"
    (client.logger.dir / dossier_name).write_text(dossier, encoding="utf-8")
    annotations = _compact_web_annotations(web_rec)
    client.logger.save_artifact(f"music_round_{round_index:02d}_{'gap_' if gap_mode else ''}web_annotations.json", annotations)

    structure_payload = {
        "TARGET_COUNT": target,
        "APPROVED_CONCEPT": _compact_concept_for_music(approved_concept),
        "BRIEF_ANCHOR": _compact_anchor_for_music(brief_anchor),
        "WEB_DOSSIER": dossier,
        "WEB_ANNOTATIONS": annotations,
        "GAPS": gaps or [],
    }
    research, _ = client.chat_json_strict(
        stage=struct_stage, round_index=round_index,
        system_prompt=MUSIC_GAP_STRUCTURER_PROMPT if gap_mode else MUSIC_STRUCTURER_PROMPT,
        user_payload=structure_payload, model_chain=struct_chain, schema=MUSIC_RESEARCH_SCHEMA,
        max_tokens=MUSIC_MAX_TOKENS["gap_structurer" if gap_mode else "structurer"],
        temperature=0.0,
        agent_goal="Convert web evidence dossier to strict music research schema without new facts",
    )
    validate_music_research_local(research, min_candidates=3 if gap_mode else 8)
    return research


def gate_music_pool(client, *, project_brief: str, brief_anchor: Dict[str, Any], approved_concept: Dict[str, Any],
                    candidates: List[Dict[str, Any]], round_index: int,
                    existing_pass_context: Optional[List[Dict[str, Any]]] = None,
                    gap_mode: bool = False) -> Dict[str, Any]:
    profile = _music_round_profile(round_index)
    stage = "music_gap_gate" if gap_mode else "music_gate"
    chain = profile["gap_validator"] if gap_mode else profile["validator"]
    compact_candidates = []
    for c in candidates:
        compact_candidates.append({
            "candidate_id": c.get("candidate_id"), "title": c.get("title"), "artist": c.get("artist"),
            "origin_bucket": c.get("origin_bucket"), "language": c.get("language"), "vocal_type": c.get("vocal_type"),
            "genre_tags": c.get("genre_tags"), "sonic_profile": c.get("sonic_profile"),
            "lyrical_theme_summary": c.get("lyrical_theme_summary"),
            "genius_research": c.get("genius_research"),
            "creator_commentary": c.get("creator_commentary"),
            "why_fit_concept": c.get("why_fit_concept"), "why_fit_brief": c.get("why_fit_brief"),
            "role_hypothesis": c.get("role_hypothesis"), "sources": c.get("sources"),
            "research_confidence": c.get("research_confidence"),
            "identity_verification": c.get("identity_verification"),
        })
    payload = {
        # Full brief is intentionally used at the final semantic gate, not repeated in web-research output.
        "PROJECT_BRIEF": project_brief,
        "BRIEF_ANCHOR": _compact_anchor_for_music(brief_anchor),
        "APPROVED_CONCEPT": _compact_concept_for_music(approved_concept),
        "CANDIDATES": compact_candidates,
        "EXISTING_PASS_CONTEXT": [{
            "title": x.get("title"), "artist": x.get("artist"), "role": x.get("role_hypothesis"),
            "score": (x.get("validation") or {}).get("final_score")
        } for x in (existing_pass_context or [])],
    }
    gate, _ = client.chat_json(
        stage=stage, round_index=round_index, system_prompt=MUSIC_GATE_PROMPT,
        user_payload=payload, model_chain=chain, schema=MUSIC_GATE_SCHEMA,
        temperature=0.1, max_tokens=MUSIC_MAX_TOKENS["gap_gate" if gap_mode else "gate"],
    )
    validate_music_gate_local(gate, candidates)
    return gate


def _renumber_gap_candidates(candidates: List[Dict[str, Any]], prefix: str) -> List[Dict[str, Any]]:
    out = []
    for i, c in enumerate(candidates, 1):
        x = deepcopy(c); x["candidate_id"] = f"{prefix}_{i:02d}"; out.append(x)
    return out


def run_music_round(client, *, project_brief: str, brief_anchor: Dict[str, Any], approved_concept: Dict[str, Any],
                    round_index: int = 1, user_context: str = "", feedback: str = "") -> Dict[str, Any]:
    profile = _music_round_profile(round_index)
    print(f"\n### MUSIC ROUND {round_index}")
    print("Research primary:", profile["research"][0])
    print("Validator primary:", profile["validator"][0])
    print("Web profile:", MUSIC_WEB_PROFILE, MUSIC_WEB_PROFILES[MUSIC_WEB_PROFILE])

    research = research_music_pool(
        client, project_brief=project_brief, brief_anchor=brief_anchor, approved_concept=approved_concept,
        round_index=round_index, user_context=user_context, feedback=feedback,
    )
    candidates = verify_music_pool(research["candidates"], logger=client.logger, round_index=round_index)
    gate = gate_music_pool(
        client, project_brief=project_brief, brief_anchor=brief_anchor, approved_concept=approved_concept,
        candidates=candidates, round_index=round_index,
    )
    portfolio = build_validated_playlist(candidates, gate)

    auto_gaps = list(dict.fromkeys((gate.get("research_gaps") or []) + portfolio.get("gaps", [])))
    coverage_short = any([
        portfolio["coverage"]["iranian"] < MUSIC_TARGET_MIN_IRANIAN,
        portfolio["coverage"]["international"] < MUSIC_TARGET_MIN_INTERNATIONAL,
        portfolio["coverage"]["instrumental"] < MUSIC_TARGET_MIN_INSTRUMENTAL,
        portfolio["coverage"]["vocal_or_mixed"] < MUSIC_TARGET_MIN_VOCAL,
    ])
    needs_gap = (
        len(portfolio["tracks"]) < MUSIC_MIN_FINAL
        or (bool(gate.get("needs_gap_fill")) and len(portfolio["tracks"]) < MUSIC_TARGET_FINAL and coverage_short)
    )

    gap_bundle = None
    if MUSIC_ENABLE_AUTO_GAP_FILL and needs_gap:
        print("Conditional gap-fill triggered:", auto_gaps or ["insufficient validated tracks"])
        gap_research = research_music_pool(
            client, project_brief=project_brief, brief_anchor=brief_anchor, approved_concept=approved_concept,
            round_index=round_index, user_context=user_context, feedback=feedback,
            existing_tracks=candidates, gaps=auto_gaps or ["insufficient validated tracks"], gap_mode=True,
        )
        new_candidates_raw = _renumber_gap_candidates(gap_research["candidates"], f"gap_r{round_index}")
        new_candidates = verify_music_pool(new_candidates_raw, logger=client.logger, round_index=round_index)
        gap_gate = gate_music_pool(
            client, project_brief=project_brief, brief_anchor=brief_anchor, approved_concept=approved_concept,
            candidates=new_candidates, round_index=round_index, existing_pass_context=portfolio["tracks"], gap_mode=True,
        )
        merged_candidates = candidates + new_candidates
        merged_gate = deepcopy(gate)
        merged_gate["judgments"] = gate["judgments"] + gap_gate["judgments"]
        merged_gate["research_gaps"] = gap_gate.get("research_gaps", [])
        merged_gate["needs_gap_fill"] = gap_gate.get("needs_gap_fill", False)
        portfolio = build_validated_playlist(merged_candidates, merged_gate)
        candidates, gate = merged_candidates, merged_gate
        gap_bundle = {"research": gap_research, "gate": gap_gate}

    result = {
        "artifact_type": "validated_music_portfolio",
        "round": round_index,
        "research_direction": research.get("research_direction"),
        "portfolio_notes": gate.get("portfolio_notes"),
        "tracks": portfolio["tracks"],
        "coverage": portfolio["coverage"],
        "gaps": portfolio["gaps"],
        "research": research,
        "gate": gate,
        "gap_fill": gap_bundle,
    }
    client.logger.save_artifact(f"music_round_{round_index:02d}_result.json", result)
    print_music_usage_summary(client.logger)
    return result

## Music output rendering

Music is displayed as the automatic downstream result of the approved Concept. There is no second mandatory Human Gate in the main flow.

In [21]:
def _source_urls(track: Dict[str, Any], limit: int = 3) -> List[str]:
    urls = []
    for s in track.get("sources") or []:
        u = s.get("url")
        if u and u not in urls:
            urls.append(u)
    return urls[:limit]


def show_music_playlist(result: Dict[str, Any]):
    tracks = result.get("tracks", [])
    print("=" * 105)
    print("MUSIC DIRECTION:", result.get("research_direction"))
    print("PORTFOLIO:", result.get("portfolio_notes"))
    print("COVERAGE:", result.get("coverage"))
    if result.get("gaps"):
        print("GAPS:", result.get("gaps"))
    print()
    if not tracks:
        print("هیچ قطعهٔ validated باقی نماند.")
        return
    for i, t in enumerate(tracks, 1):
        v = t.get("validation") or {}
        sonic = t.get("sonic_profile") or {}
        print("-" * 105)
        print(f"{i}) {t.get('artist')} — {t.get('title')} [{t.get('origin_bucket')} / {t.get('vocal_type')}]")
        print("   Score:", v.get("final_score"), "| Anchor:", v.get("anchor_score"), "| Sonic:", v.get("sonic_score"),
              "| Lyric:", v.get("lyric_score"))
        print("   Sound:", sonic.get("tempo_feel"), "|", sonic.get("pulse_and_rhythm"), "|", sonic.get("emotional_color"))
        if t.get("vocal_type") in {"VOCAL", "MIXED"}:
            print("   Lyric theme:", t.get("lyrical_theme_summary"))
        gr = t.get("genius_research") or {}
        if gr.get("status") != "NOT_APPLICABLE":
            print("   Genius:", gr.get("status"), "|", gr.get("song_url") or "no page found")
            if gr.get("annotation_context_summary"):
                print("   Genius context:", gr.get("annotation_context_summary"))
        cc = t.get("creator_commentary") or {}
        if cc.get("status") == "DIRECT_FOUND":
            print("   Creator says:", cc.get("summary"))
            print("   Creator source:", cc.get("speaker"), "|", cc.get("source_kind"), "|", cc.get("source_url"))
        else:
            print("   Creator commentary: direct statement not found")
        print("   Why concept:", t.get("why_fit_concept"))
        print("   Why brief:", t.get("why_fit_brief"))
        print("   Gate:", v.get("reason"))
        if t.get("listen_url"):
            print("   Listen:", t.get("listen_url"))
        for u in _source_urls(t):
            print("   Source:", u)
    print("=" * 105)

## Music-specific token / cost / agent audit

In [22]:
def music_usage_summary(logger: RunLogger) -> Dict[str, Any]:
    stages = {"music_web_research", "music_research_structurer", "music_gate",
              "music_gap_web_research", "music_gap_research_structurer", "music_gap_gate",
              "music_identity_verify"}
    rows = [r for r in logger.records if r.get("stage") in stages]
    ok = [r for r in rows if r.get("status") == "ok"]
    billed = [r for r in rows if RunLogger._is_billed_record(r)]
    events = [r for r in rows if r.get("status") == "event"]
    by_stage = {}
    for stage in sorted(stages):
        x = [r for r in billed if r.get("stage") == stage]
        if not x and stage != "music_identity_verify":
            continue
        by_stage[stage] = {
            "calls": len(x),
            "input_tokens": sum(int(r.get("usage", {}).get("prompt_tokens") or 0) for r in x),
            "output_tokens": sum(int(r.get("usage", {}).get("completion_tokens") or 0) for r in x),
            "reasoning_tokens": sum(int(r.get("usage", {}).get("reasoning_tokens") or 0) for r in x),
            "total_tokens": sum(int(r.get("usage", {}).get("total_tokens") or 0) for r in x),
            "web_search_requests": sum(int(r.get("usage", {}).get("web_search_requests") or 0) for r in x),
            "web_fetch_requests": sum(int(r.get("usage", {}).get("web_fetch_requests") or 0) for r in x),
            "api_reported_cost_usd": round(sum(float(r.get("usage", {}).get("cost_usd") or 0) for r in x), 6),
            "agent_goal": next((r.get("agent_goal") for r in x if r.get("agent_goal")), None),
        }
    totals = {
        "model_calls": len(ok),
        "billed_attempts": len(billed),
        "failed_billed_attempts": len([r for r in billed if r.get("status") == "error"]),
        "input_tokens": sum(int(r.get("usage", {}).get("prompt_tokens") or 0) for r in billed),
        "output_tokens": sum(int(r.get("usage", {}).get("completion_tokens") or 0) for r in billed),
        "reasoning_tokens": sum(int(r.get("usage", {}).get("reasoning_tokens") or 0) for r in billed),
        "total_tokens": sum(int(r.get("usage", {}).get("total_tokens") or 0) for r in billed),
        "web_search_requests": sum(int(r.get("usage", {}).get("web_search_requests") or 0) for r in billed),
        "web_fetch_requests": sum(int(r.get("usage", {}).get("web_fetch_requests") or 0) for r in billed),
        "api_reported_cost_usd": round(sum(float(r.get("usage", {}).get("cost_usd") or 0) for r in billed), 6),
        "deterministic_events": len(events),
    }
    result = {
        "project_id": logger.project_id, "run_id": logger.run_id,
        "totals": totals, "by_stage": by_stage,
        "note": "API-reported cost is authoritative when present. Search reference estimates in call logs are informational and are not added again to avoid double counting.",
    }
    logger.save_artifact("music_usage_summary.json", result)
    return result


def print_music_usage_summary(logger: RunLogger):
    s = music_usage_summary(logger); t = s["totals"]
    print("\n=== DROP MUSIC TOKEN / COST SUMMARY ===")
    print("Music successful model calls:", t["model_calls"], "| billed attempts:", t.get("billed_attempts", t["model_calls"]))
    print("Input tokens:", t["input_tokens"])
    print("OUTPUT tokens:", t["output_tokens"])
    print("Reasoning tokens:", t["reasoning_tokens"])
    print("Total tokens:", t["total_tokens"])
    print("Web search requests:", t["web_search_requests"], "| Web fetches:", t.get("web_fetch_requests",0))
    print("API-reported cost USD:", t["api_reported_cost_usd"])
    print("Music summary:", logger.dir / "music_usage_summary.json")
    print("Full call/event log:", logger.jsonl_path)
    if pd is not None and s["by_stage"]:
        display(pd.DataFrame(s["by_stage"]).T)
    return s


def full_run_usage_summary_v72(logger: RunLogger) -> Dict[str, Any]:
    s = logger.summary()
    ok = [r for r in logger.records if r.get("status") == "ok"]
    billed = [r for r in logger.records if RunLogger._is_billed_record(r)]
    s["web_search_requests"] = sum(int(r.get("usage", {}).get("web_search_requests") or 0) for r in billed)
    s["output_tokens"] = s["totals"].get("completion_tokens", 0)
    logger.save_artifact("usage_summary_v72.json", s)
    print("\n=== DROP V7.2 FULL RUN SUMMARY ===")
    print("All model calls:", s["successful_calls"])
    print("Input tokens:", s["totals"]["prompt_tokens"])
    print("OUTPUT tokens:", s["totals"]["completion_tokens"])
    print("Total tokens:", s["totals"]["total_tokens"])
    print("Web search requests:", s["web_search_requests"])
    print("API-reported total cost USD:", s["totals"]["cost_usd"])
    print("Full summary:", logger.dir / "usage_summary_v72.json")
    return s



def full_run_usage_summary_v73(logger: RunLogger) -> Dict[str, Any]:
    s = logger.summary()
    ok = [r for r in logger.records if r.get("status") == "ok"]
    billed = [r for r in logger.records if RunLogger._is_billed_record(r)]
    s["web_search_requests"] = sum(int(r.get("usage", {}).get("web_search_requests") or 0) for r in billed)
    s["output_tokens"] = s["totals"].get("completion_tokens", 0)
    logger.save_artifact("usage_summary_v73.json", s)
    print("\n=== DROP V7.3 FULL RUN SUMMARY ===")
    print("All model calls:", s["successful_calls"])
    print("Input tokens:", s["totals"]["prompt_tokens"])
    print("OUTPUT tokens:", s["totals"]["completion_tokens"])
    print("Total tokens:", s["totals"]["total_tokens"])
    print("Web search requests:", s["web_search_requests"])
    print("API-reported total cost USD:", s["totals"]["cost_usd"])
    print("Full summary:", logger.dir / "usage_summary_v73.json")
    return s



def music_evidence_audit(result: Dict[str, Any], logger: RunLogger) -> Dict[str, Any]:
    tracks = result.get("tracks", []) if result else []
    genius_found = 0
    creator_direct = 0
    vocal = 0
    vocal_genius_not_found = []
    for t in tracks:
        gr = t.get("genius_research") or {}
        cc = t.get("creator_commentary") or {}
        if gr.get("status") in {"FOUND_SONG_PAGE", "FOUND_ANNOTATIONS"}:
            genius_found += 1
        if cc.get("status") == "DIRECT_FOUND":
            creator_direct += 1
        if t.get("vocal_type") in {"VOCAL", "MIXED"}:
            vocal += 1
            if gr.get("status") == "NOT_FOUND":
                vocal_genius_not_found.append({"artist":t.get("artist"),"title":t.get("title")})
    audit = {
        "validated_tracks": len(tracks),
        "vocal_or_mixed_tracks": vocal,
        "tracks_with_genius_evidence": genius_found,
        "tracks_with_direct_creator_commentary": creator_direct,
        "vocal_tracks_without_genius_page": vocal_genius_not_found,
        "policy": "Genius is preferred for lyric/annotation context; direct creator commentary is separately attributed and may legitimately be NOT_FOUND.",
    }
    logger.save_artifact("music_evidence_audit.json", audit)
    return audit


def full_run_usage_summary_v75(logger: RunLogger) -> Dict[str, Any]:
    s = logger.summary()
    ok = [r for r in logger.records if r.get("status") == "ok"]
    billed = [r for r in logger.records if RunLogger._is_billed_record(r)]
    s["web_search_requests"] = sum(int(r.get("usage", {}).get("web_search_requests") or 0) for r in billed)
    s["output_tokens"] = s["totals"].get("completion_tokens", 0)
    p = get_drop_progress(logger) if "get_drop_progress" in globals() else None
    if p is not None:
        s["progress"] = p.save_summary()
    logger.save_artifact("usage_summary_v76.json", s)
    print("\n=== DROP V7.6 FULL RUN SUMMARY ===")
    print("All model calls:", s["successful_calls"])
    print("Input tokens:", s["totals"]["prompt_tokens"])
    print("OUTPUT tokens:", s["totals"]["completion_tokens"])
    print("Total tokens:", s["totals"]["total_tokens"])
    print("Web search requests:", s["web_search_requests"])
    print("API-reported total cost USD:", s["totals"]["cost_usd"])
    print("Full summary:", logger.dir / "usage_summary_v76.json")
    return s

# Unified DROP Session — Manual and Auto modes

**Manual Mode**
- Start once.
- Idea Round appears.
- Approve → only stores the Concept; Music starts from the separate Step B cell.
- Refine → partially liked directions + feedback feed the next Idea Round and swap model family.
- Reject all → feedback becomes regeneration guidance and the next round swaps model family.

**Auto Mode**
- The dedicated Auto End-to-End cell asks only for the OpenRouter API key.
- The strongest already-validated Concept is selected deterministically; no extra model call is spent on selection.
- Music Research then runs immediately from that exact Concept.

In [23]:
def log_session_event(logger: RunLogger, event_type: str, **details):
    record = {
        "status": "event", "stage": "session_flow", "event_type": event_type,
        "usage": {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0,
                  "reasoning_tokens": 0, "cached_tokens": 0, "cost_usd": 0.0},
        **details,
    }
    logger.log(record)
    path = logger.dir / "session_events.jsonl"
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps({k:v for k,v in record.items() if k != "status"}, ensure_ascii=False) + "\n")



@dataclass
class DropSession:
    client: Any
    idea_session: IdeaSession
    music_context: str = ""
    music_max_auto_rounds: int = 3
    approved_concept: Optional[Dict[str, Any]] = None
    music_result: Optional[Dict[str, Any]] = None
    music_round_index: int = 0
    status: str = "IDEA_WAITING"  # IDEA_WAITING | IDEA_APPROVED_AWAITING_MUSIC | MUSIC_RESEARCHING | COMPLETE | IDEA_EXHAUSTED | MUSIC_INSUFFICIENT

    @property
    def logger(self):
        return self.client.logger

    @property
    def cards(self):
        if self.idea_session.current_result:
            return self.idea_session.current_result.get("cards", [])
        return []

    def sync_status(self):
        if self.idea_session.status == "EXHAUSTED":
            self.status = "IDEA_EXHAUSTED"
        elif self.approved_concept and self.status == "IDEA_APPROVED_AWAITING_MUSIC":
            pass
        elif self.idea_session.status == "WAITING_FOR_USER" and self.status not in {"MUSIC_RESEARCHING", "COMPLETE", "MUSIC_INSUFFICIENT"}:
            self.status = "IDEA_WAITING"
        return self.status

    def refine_ideas(self, feedback: str, liked_numbers: Optional[List[int]] = None):
        if self.status != "IDEA_WAITING":
            raise RuntimeError("DROP session is not waiting at the Idea Gate.")
        liked_numbers = [int(x) for x in (liked_numbers or [])]
        log_session_event(self.logger, "IDEA_REFINE_REQUESTED", idea_round=self.idea_session.round_index,
                          liked_numbers=liked_numbers, feedback=feedback)
        result = self.idea_session.refine(feedback=feedback, liked_numbers=liked_numbers)
        self.sync_status()
        log_session_event(self.logger, "IDEA_NEXT_ROUND_READY", idea_round=self.idea_session.round_index,
                          status=self.status, card_count=len(self.cards))
        return result

    def reject_all_ideas(self, feedback: str):
        log_session_event(self.logger, "IDEA_REJECT_ALL", idea_round=self.idea_session.round_index, feedback=feedback)
        return self.refine_ideas(feedback=feedback, liked_numbers=[])

    def approve_concept(self, card_number: int, auto_continue: bool = False):
        """Approve a Concept. Manual mode stops before Music; Auto mode only changes messaging/state intent."""
        if self.status != "IDEA_WAITING":
            raise RuntimeError("DROP session is not waiting at the Idea Gate.")
        approved = self.idea_session.approve(int(card_number))
        self.approved_concept = approved["approved_concept"]
        self.status = "IDEA_APPROVED_AWAITING_MUSIC"
        next_action = "AUTO_CONTINUE_TO_MUSIC" if auto_continue else "RUN_MUSIC_CELL"
        log_session_event(self.logger, "CONCEPT_APPROVED", idea_round=self.idea_session.round_index,
                          card_number=int(card_number), candidate_id=self.approved_concept.get("candidate_id"),
                          title=self.approved_concept.get("title"), next_action=next_action,
                          auto_continue=bool(auto_continue))
        print(f"\n✅ Concept approved: {self.approved_concept.get('title')}")
        if auto_continue:
            print("🤖 Auto Mode: Concept selection is locked; Music Deep Research continues now.")
        else:
            print("⏸ Idea step is complete. Music has NOT started and no Music tokens were spent.")
            print("▶️ Run the NEXT notebook cell: Music Deep Research.")
            try:
                get_drop_progress(self.client).waiting("Concept approved — waiting for separate Music Deep Research cell")
            except Exception:
                pass
        return self.approved_concept

    def _research_music_until_ready(self, feedback: str = ""):
        if not self.approved_concept:
            raise RuntimeError("No approved Concept.")
        self.status = "MUSIC_RESEARCHING"
        last = None
        for r in range(1, self.music_max_auto_rounds + 1):
            self.music_round_index = r
            profile = _music_round_profile(r)
            print(f"\n### MUSIC RESEARCH ROUND {r}")
            print("Research primary:", profile["research"][0])
            print("Validator primary:", profile["validator"][0])
            log_session_event(self.logger, "MUSIC_RESEARCH_STARTED", music_round=r,
                              concept_id=self.approved_concept.get("candidate_id"),
                              concept_title=self.approved_concept.get("title"),
                              feedback=feedback or "")
            try:
                last = run_music_round(
                    self.client,
                    project_brief=self.idea_session.state.project_brief,
                    brief_anchor=self.idea_session.state.anchor,
                    approved_concept=self.approved_concept,
                    round_index=r,
                    user_context=self.music_context,
                    feedback=feedback or "",
                )
            except Exception as e:
                # Preserve the approved Concept and make Step B retryable after API/format failures.
                self.status = "IDEA_APPROVED_AWAITING_MUSIC"
                log_session_event(self.logger, "MUSIC_RESEARCH_ERROR", music_round=r,
                                  concept_id=self.approved_concept.get("candidate_id"),
                                  error=f"{type(e).__name__}: {e}", next_action="RETRY_MUSIC_CELL")
                try:
                    get_drop_progress(self.client).waiting("Music research failed — approved Concept preserved; re-run Step B")
                except Exception:
                    pass
                print("⚠️ Music Research failed, but the approved Concept was preserved.")
                print("▶️ You can re-run the Step B Music cell after fixing/retrying the API path.")
                raise
            self.music_result = last
            if len(last.get("tracks", [])) >= MUSIC_MIN_FINAL:
                self.status = "COMPLETE"
                log_session_event(self.logger, "MUSIC_READY", music_round=r,
                                  validated_tracks=len(last.get("tracks", [])))
                final = {
                    "status": "COMPLETE",
                    "project_id": self.idea_session.state.project_id,
                    "run_id": self.logger.run_id,
                    "approved_concept": self.approved_concept,
                    "brief_anchor": self.idea_session.state.anchor,
                    "music": last,
                    "idea_round": self.idea_session.round_index,
                    "music_round": r,
                }
                self.logger.save_artifact("drop_final_result.json", final)
                music_evidence_audit(last, self.logger)
                show_music_playlist(last)
                print_music_usage_summary(self.logger)
                if "full_run_usage_summary_v75" in globals():
                    full_run_usage_summary_v75(self.logger)
                return last
            print("Music evidence کافی نبود؛ Round بعد با model family متفاوت اجرا می‌شود.")
        self.status = "MUSIC_INSUFFICIENT"
        log_session_event(self.logger, "MUSIC_INSUFFICIENT", music_round=self.music_round_index,
                          validated_tracks=len((last or {}).get("tracks", [])))
        self.logger.save_artifact("drop_final_result.json", {
            "status":"MUSIC_INSUFFICIENT", "approved_concept":self.approved_concept,
            "music":last, "run_id":self.logger.run_id,
        })
        if last:
            music_evidence_audit(last, self.logger)
            show_music_playlist(last)
        if "full_run_usage_summary_v75" in globals():
            full_run_usage_summary_v75(self.logger)
        return last

    def run_music_research(self, feedback: str = ""):
        """Long-running operation intended to be called from the dedicated Music cell."""
        if self.status not in {"IDEA_APPROVED_AWAITING_MUSIC", "MUSIC_INSUFFICIENT"}:
            if self.status == "COMPLETE":
                print("Music Research is already complete. Use refine_music(feedback) for a new music round.")
                return self.music_result
            raise RuntimeError(f"Music cell cannot run while session status={self.status}. Approve a Concept first.")
        return self._research_music_until_ready(feedback=feedback)

    def refine_music(self, feedback: str):
        if self.status not in {"COMPLETE", "MUSIC_INSUFFICIENT"} or not self.approved_concept:
            raise RuntimeError("Music result is not available yet.")
        feedback=(feedback or "").strip()
        if not feedback:
            raise ValueError("Music refinement needs explicit feedback.")
        next_round=min(self.music_round_index+1, 3)
        log_session_event(self.logger, "MUSIC_REFINE_REQUESTED", music_round=next_round, feedback=feedback)
        self.status="MUSIC_RESEARCHING"
        self.music_round_index=next_round
        self.music_result=run_music_round(
            self.client, project_brief=self.idea_session.state.project_brief,
            brief_anchor=self.idea_session.state.anchor, approved_concept=self.approved_concept,
            round_index=next_round, user_context=self.music_context, feedback=feedback,
        )
        self.status="COMPLETE" if len(self.music_result.get("tracks",[]))>=MUSIC_MIN_FINAL else "MUSIC_INSUFFICIENT"
        music_evidence_audit(self.music_result, self.logger)
        show_music_playlist(self.music_result)
        if "full_run_usage_summary_v75" in globals():
            full_run_usage_summary_v75(self.logger)
        return self.music_result


def start_drop_session(client, *, project_brief: str = "", initial_context: str = "",
                       desired_feeling: str = "", seed: str = "", previous_ideas=None,
                       music_context: str = "", project_id: str = "unknown",
                       max_idea_rounds: int = MAX_USER_ROUNDS) -> DropSession:
    idea = start_idea_session(
        client, project_brief=project_brief, initial_context=initial_context,
        desired_feeling=desired_feeling, seed=seed, project_id=project_id,
        previous_ideas=previous_ideas or [], max_rounds=max_idea_rounds,
    )
    ds=DropSession(client=client, idea_session=idea, music_context=(music_context or "").strip())
    ds.sync_status()
    log_session_event(ds.logger, "SESSION_STARTED", status=ds.status,
                      idea_round=idea.round_index, card_count=len(ds.cards))
    return ds


def run_approved_music_research(session: DropSession, feedback: str = ""):
    """Dedicated-cell entry point. No-op with a clear message before Concept approval."""
    if session.status == "IDEA_WAITING":
        print("⏸ Music Research did not start: approve one Concept in the Idea Human Gate first.")
        return None
    if session.status == "IDEA_EXHAUSTED":
        print("⚠️ Music Research did not start: Idea stage ended without an approved Concept.")
        return None
    return session.run_music_research(feedback=feedback)


def submit_drop_decision(session: DropSession, action: str, *, card_number: Optional[int] = None,
                         liked_numbers: Optional[List[int]] = None, feedback: str = ""):
    a=(action or "").strip().lower()
    if a in {"approve","a","yes"}:
        if card_number is None:
            raise ValueError("card_number is required for approve")
        return session.approve_concept(int(card_number))
    if a in {"refine","revise","change"}:
        return session.refine_ideas(feedback=feedback, liked_numbers=liked_numbers or [])
    if a in {"reject","reject_all","r","no"}:
        return session.reject_all_ideas(feedback=feedback)
    if a in {"run_music","music_start"}:
        return run_approved_music_research(session, feedback=feedback)
    if a in {"refine_music","music"}:
        return session.refine_music(feedback=feedback)
    raise ValueError("action must be approve, refine, reject, run_music, or refine_music")


def render_drop_widget(session: DropSession):
    if not WIDGETS_AVAILABLE:
        print("ipywidgets unavailable. Manual examples:")
        print("submit_drop_decision(drop_session,'approve',card_number=2)  # stores approval only")
        print("submit_drop_decision(drop_session,'refine',liked_numbers=[2],feedback='...')")
        print("submit_drop_decision(drop_session,'reject',feedback='...')")
        print("# then run the separate Music cell: run_approved_music_research(drop_session)")
        return None
    out=widgets.Output()
    display(out)

    def draw():
        with out:
            clear_output(wait=True)
            session.sync_status()
            if session.status=="IDEA_EXHAUSTED":
                display(HTML("<h3>⚠️ Idea round budget exhausted</h3>")); return
            if session.status=="IDEA_APPROVED_AWAITING_MUSIC":
                c=session.approved_concept or {}
                display(HTML(
                    f"<h3>✅ Concept approved</h3><b>{c.get('title','')}</b><p>{c.get('one_line','')}</p>"
                    "<div style='padding:10px;border:1px solid #c9d7e6;border-radius:8px'>"
                    "⏸ <b>Music هنوز شروع نشده است.</b><br>"
                    "سلول Idea تمام شد. حالا سلول بعدی با عنوان <b>Music Deep Research — RUN AFTER APPROVAL</b> را اجرا کن."
                    "</div>"
                ))
                return
            if session.status in {"COMPLETE","MUSIC_INSUFFICIENT"}:
                c=session.approved_concept or {}
                display(HTML(f"<h3>✅ Approved Concept → Music Research finished</h3><b>{c.get('title','')}</b><p>{c.get('one_line','')}</p>"))
                show_music_playlist(session.music_result or {})
                display(HTML("<small>برای refinement موسیقی، آن را از یک سلول معمولی با <code>drop_session.refine_music('feedback')</code> اجرا کن تا callback طولانی نداشته باشیم.</small>"))
                return
            if session.status=="MUSIC_RESEARCHING":
                display(HTML("<h3>🔎 Music Deep Research is running in the dedicated Music cell…</h3>")); return
            if session.status!="IDEA_WAITING":
                display(HTML(f"<p>Session state: <b>{session.status}</b></p>")); return

            cards=session.cards
            display(HTML(
                f"<h3>⏸ Idea Human Gate — Round {session.idea_session.round_index}</h3>"
                "<p>تأیید فقط Concept را ذخیره می‌کند؛ Music Research در این callback اجرا نمی‌شود. برای refine جهت‌های پسندیده را انتخاب و feedback بده.</p>"
            ))
            show_cards(cards)
            options=[(f"{i}) {c['title']}", i) for i,c in enumerate(cards,1)]
            liked=widgets.SelectMultiple(options=options,value=(),description="کمی پسندیدم:",layout=widgets.Layout(width="95%",height="115px"),style={"description_width":"95px"})
            fb=widgets.Textarea(value="",placeholder="دقیقاً بگو چه چیزی را نگه داریم و چه چیزی تغییر کند…",description="Feedback:",layout=widgets.Layout(width="95%",height="95px"),style={"description_width":"95px"})
            status=widgets.HTML()
            approve_buttons=[]
            for i,c in enumerate(cards,1):
                b=widgets.Button(description=f"✓ تأیید {i}",tooltip=c['title'],button_style="success",layout=widgets.Layout(width="125px"))
                approve_buttons.append(b)
            refine=widgets.Button(description="↻ اصلاح با جهت‌های پسندیده",button_style="info",layout=widgets.Layout(width="205px"))
            reject=widgets.Button(description="✕ رد همه و Round بعد",button_style="warning",layout=widgets.Layout(width="190px"))
            allb=approve_buttons+[refine,reject]
            def busy(msg):
                for b in allb: b.disabled=True
                liked.disabled=True; fb.disabled=True; status.value=f"<b>{msg}</b>"
            def restore(err):
                for b in allb: b.disabled=False
                liked.disabled=False; fb.disabled=False; status.value=f"<span style='color:#b00020'>{type(err).__name__}: {err}</span>"
            def approve_click(_b,n):
                try:
                    busy(f"Concept {n} در حال ثبت تأیید…")
                    session.approve_concept(n)
                    draw()
                except Exception as e: restore(e)
            for i,b in enumerate(approve_buttons,1):
                b.on_click(lambda btn,n=i: approve_click(btn,n))
            def refine_click(_):
                try:
                    busy("در حال ساخت Idea Round بعد با feedback و جهت‌های پسندیده…")
                    session.refine_ideas(fb.value,list(liked.value)); draw()
                except Exception as e: restore(e)
            def reject_click(_):
                try:
                    busy("همه رد شدند؛ در حال ساخت Round بعد با مدل متفاوت…")
                    session.reject_all_ideas(fb.value); draw()
                except Exception as e: restore(e)
            refine.on_click(refine_click); reject.on_click(reject_click)
            display(widgets.HBox(approve_buttons,layout=widgets.Layout(flex_flow="row wrap")))
            display(liked); display(fb); display(widgets.HBox([refine,reject])); display(status)
            display(HTML("<small>Fallback: <code>submit_drop_decision(drop_session,'approve',card_number=2)</code> / <code>submit_drop_decision(drop_session,'refine',liked_numbers=[2],feedback='...')</code> / <code>submit_drop_decision(drop_session,'reject',feedback='...')</code></small>"))
    draw()
    return out

## Live Progress Monitor + robust transport

Progress is stage-level and honest. It shows the current stage/model, elapsed time, token/cost totals, web tool usage, and deterministic item progress where available.  
**V7.9 Music recommendation discovery is Web-only**; no embedding/catalog semantic search is used.

In [24]:

# ============================================================
# V7.4 LIVE PROGRESS / HEARTBEAT LAYER
# ============================================================
import html as _html_lib
from concurrent.futures import ThreadPoolExecutor, TimeoutError as _FutureTimeout

PROGRESS_HEARTBEAT_SECONDS = 8


def _progress_usage_snapshot(logger):
    records = getattr(logger, "records", [])
    billed = [r for r in records if RunLogger._is_billed_record(r)]
    ok = [r for r in records if r.get("status") == "ok"]
    return {
        "calls": len(ok),
        "attempts": len(billed),
        "prompt_tokens": sum(int(r.get("usage", {}).get("prompt_tokens") or 0) for r in billed),
        "completion_tokens": sum(int(r.get("usage", {}).get("completion_tokens") or 0) for r in billed),
        "total_tokens": sum(int(r.get("usage", {}).get("total_tokens") or 0) for r in billed),
        "cost_usd": round(sum(float(r.get("usage", {}).get("cost_usd") or 0.0) for r in billed), 6),
        "web_search_requests": sum(int(r.get("usage", {}).get("web_search_requests") or 0) for r in billed),
        "web_fetch_requests": sum(int(r.get("usage", {}).get("web_fetch_requests") or 0) for r in billed),
    }


class DropProgressMonitor:
    """Honest stage-level progress monitor for notebook + Colab widget callbacks."""
    def __init__(self, logger, heartbeat_seconds=PROGRESS_HEARTBEAT_SECONDS):
        self.logger = logger
        self.heartbeat_seconds = max(2, int(heartbeat_seconds))
        self.phase_id = None
        self.phase_title = "DROP session"
        self.total_steps = 0
        self.completed_steps = 0
        self.current_step = None
        self.current_model = None
        self.detail = ""
        self.state = "READY"  # READY|RUNNING|WAITING|DONE|ERROR
        self.phase_started = None
        self.step_started = None
        self._display_handle = None
        self._widgets = []
        self._extras = set()
        self.events = []
        self.progress_path = logger.dir / "progress_events.jsonl"
        self.summary_path = logger.dir / "progress_summary.json"

    def _usage(self):
        return _progress_usage_snapshot(self.logger)

    def _write_event(self, event_type, **extra):
        event = {
            "timestamp_utc": utc_now_iso(),
            "event_type": event_type,
            "state": self.state,
            "phase_id": self.phase_id,
            "phase_title": self.phase_title,
            "completed_steps": self.completed_steps,
            "total_steps": self.total_steps,
            "current_step": self.current_step,
            "current_model": self.current_model,
            "detail": self.detail,
            "usage_snapshot": self._usage(),
            **extra,
        }
        self.events.append(event)
        with self.progress_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(event, ensure_ascii=False) + "\n")
        return event

    def _elapsed(self):
        if self.step_started is None:
            return None
        return max(0.0, time.perf_counter() - self.step_started)

    def _bar_html(self):
        total = max(0, int(self.total_steps or 0))
        done = max(0, min(int(self.completed_steps or 0), total if total else 0))
        pct = round((100.0 * done / total), 1) if total else 0.0
        active_no = min(done + 1, total) if self.current_step and total else done
        elapsed = self._elapsed()
        elapsed_txt = f" · elapsed {elapsed:.0f}s" if elapsed is not None and self.state == "RUNNING" else ""
        state_icon = {"READY":"○","RUNNING":"⏳","WAITING":"⏸","DONE":"✅","ERROR":"❌"}.get(self.state,"•")
        step_txt = f"{done}/{total} completed" if total else "no active phase"
        if self.current_step and self.state == "RUNNING":
            step_txt += f" · current {active_no}/{total}: {_html_lib.escape(str(self.current_step))}"
        model_txt = f"<br><b>Model:</b> {_html_lib.escape(str(self.current_model))}" if self.current_model else ""
        detail_txt = f"<br><b>Detail:</b> {_html_lib.escape(str(self.detail))}" if self.detail else ""
        u = self._usage()
        return f"""
        <div style='border:1px solid #d7dce2;border-radius:10px;padding:10px 12px;margin:8px 0;font-family:system-ui;'>
          <div style='display:flex;justify-content:space-between;gap:12px;align-items:center;'>
            <b>{state_icon} DROP Progress — {_html_lib.escape(str(self.phase_title))}</b>
            <span>{pct:.1f}%</span>
          </div>
          <div style='background:#eceff3;border-radius:7px;height:12px;margin:7px 0;overflow:hidden;'>
            <div style='background:#5b6b7a;height:12px;width:{pct}%;transition:width .2s;'></div>
          </div>
          <div><b>State:</b> {self.state} · {step_txt}{elapsed_txt}</div>
          {model_txt}{detail_txt}
          <div style='margin-top:7px;font-size:12px;color:#555;'>
            Calls {u['calls']} / billed attempts {u['attempts']} · Input {u['prompt_tokens']} · Output {u['completion_tokens']} · Total {u['total_tokens']} · Web searches {u['web_search_requests']} · fetches {u['web_fetch_requests']} · Cost ${u['cost_usd']:.6f}
          </div>
          <div style='font-size:11px;color:#777;'>Progress log: {_html_lib.escape(str(self.progress_path))}</div>
        </div>
        """

    def render(self):
        html_value = self._bar_html()
        for w in list(self._widgets):
            try:
                w.value = html_value
            except Exception:
                pass
        if self._display_handle is None:
            try:
                self._display_handle = display(HTML(html_value), display_id=True)
            except Exception:
                # Script / non-IPython fallback.
                print(self.text_status(), flush=True)
        else:
            try:
                self._display_handle.update(HTML(html_value))
            except Exception:
                pass

    def text_status(self):
        total = self.total_steps or 0
        current = min(self.completed_steps + 1, total) if self.current_step and total else self.completed_steps
        u = self._usage()
        return (f"[DROP {self.state}] {self.phase_title} | completed {self.completed_steps}/{total}"
                + (f" | current {current}/{total}: {self.current_step}" if self.current_step else "")
                + (f" | model={self.current_model}" if self.current_model else "")
                + f" | tokens={u['total_tokens']} | cost=${u['cost_usd']:.6f}")

    def attach_widget(self, widget):
        if widget not in self._widgets:
            self._widgets.append(widget)
        try:
            widget.value = self._bar_html()
        except Exception:
            pass

    def start_phase(self, phase_id, title, total_steps):
        self.phase_id = str(phase_id)
        self.phase_title = str(title)
        self.total_steps = max(1, int(total_steps))
        self.completed_steps = 0
        self.current_step = None
        self.current_model = None
        self.detail = ""
        self.state = "RUNNING"
        self.phase_started = time.perf_counter()
        self.step_started = None
        self._extras = set()
        self._write_event("PHASE_START")
        self.render()

    def ensure_extra_steps(self, key, extra_steps, reason=""):
        if key in self._extras:
            return
        self._extras.add(key)
        self.total_steps += int(extra_steps)
        self.detail = reason or self.detail
        self._write_event("PHASE_EXTENDED", extra_steps=int(extra_steps), reason=reason)
        self.render()

    def start_step(self, label, model=None, detail=""):
        self.current_step = str(label)
        self.current_model = model
        self.detail = detail or ""
        self.state = "RUNNING"
        self.step_started = time.perf_counter()
        self._write_event("STEP_START")
        self.render()

    def set_model_attempt(self, stage, model, detail=""):
        self.current_model = model
        self.detail = detail or f"OpenRouter request: {stage}"
        self._write_event("MODEL_ATTEMPT", stage=stage, model=model)
        self.render()

    def heartbeat(self, detail=None):
        if detail:
            self.detail = detail
        self._write_event("HEARTBEAT", elapsed_seconds=round(self._elapsed() or 0.0, 1))
        self.render()

    def model_result(self, rec):
        usage = (rec or {}).get("usage", {})
        actual = (rec or {}).get("actual_model") or (rec or {}).get("requested_model")
        if actual:
            self.current_model = actual
        self.detail = (f"Response received · +{int(usage.get('total_tokens') or 0)} tokens"
                       f" · +${float(usage.get('cost_usd') or 0.0):.6f}")
        self._write_event("MODEL_RESULT", stage=(rec or {}).get("stage"), model=actual,
                          call_usage=usage)
        self.render()

    def item_progress(self, i, n, label="items"):
        self.detail = f"{label}: {i}/{n}"
        self._write_event("ITEM_PROGRESS", item_index=i, item_total=n, item_label=label)
        self.render()

    def complete_step(self, note=""):
        self.completed_steps = min(self.total_steps, self.completed_steps + 1)
        elapsed = self._elapsed()
        completed_label = self.current_step
        if note:
            self.detail = note
        self._write_event("STEP_DONE", completed_label=completed_label,
                          elapsed_seconds=round(elapsed or 0.0, 2))
        self.current_step = None
        self.current_model = None
        self.step_started = None
        self.render()

    def fail_step(self, error):
        self.state = "ERROR"
        self.detail = f"{type(error).__name__}: {error}"
        self._write_event("STEP_ERROR", error=self.detail)
        self.render()

    def finish_phase(self, note=""):
        self.completed_steps = self.total_steps
        self.current_step = None
        self.current_model = None
        self.step_started = None
        self.state = "DONE"
        if note:
            self.detail = note
        elapsed = (time.perf_counter() - self.phase_started) if self.phase_started else 0.0
        self._write_event("PHASE_DONE", elapsed_seconds=round(elapsed, 2))
        self.render()
        self.save_summary()

    def waiting(self, note="Waiting for user decision"):
        self.state = "WAITING"
        self.current_step = None
        self.current_model = None
        self.step_started = None
        self.detail = note
        self._write_event("WAITING")
        self.render()
        self.save_summary()

    def save_summary(self):
        phase_counts = {}
        for e in self.events:
            pid = e.get("phase_id") or "none"
            phase_counts[pid] = phase_counts.get(pid, 0) + 1
        data = {
            "run_id": self.logger.run_id,
            "project_id": self.logger.project_id,
            "state": self.state,
            "phase_id": self.phase_id,
            "phase_title": self.phase_title,
            "event_count": len(self.events),
            "phase_event_counts": phase_counts,
            "usage_snapshot": self._usage(),
            "progress_log": str(self.progress_path),
        }
        with self.summary_path.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return data


def get_drop_progress(client_or_logger):
    if hasattr(client_or_logger, "logger"):
        client = client_or_logger
        logger = client.logger
    else:
        client = None
        logger = client_or_logger
    p = getattr(logger, "_drop_progress", None)
    if p is None:
        p = DropProgressMonitor(logger)
        logger._drop_progress = p
    if client is not None:
        try:
            client.progress = p
        except Exception:
            pass
    return p


# ---------- Live heartbeat around REAL OpenRouter calls ----------
_v73_openrouter_chat_json = OpenRouterClient.chat_json
_v76_openrouter_chat_text_web = OpenRouterClient.chat_text_web
_v76_openrouter_chat_json_strict = OpenRouterClient.chat_json_strict


def _call_with_progress_heartbeat(progress, fn, *, stage, model, detail):
    progress.set_model_attempt(stage, model, detail)
    # Run the blocking HTTP/fallback routine in one worker so the notebook main thread
    # can refresh the progress widget. This does NOT fake a percent inside the API call.
    with ThreadPoolExecutor(max_workers=1) as ex:
        future = ex.submit(fn)
        while True:
            try:
                return future.result(timeout=progress.heartbeat_seconds)
            except _FutureTimeout:
                progress.heartbeat(f"Still running OpenRouter call · {stage} · {model}")


def _v74_chat_json(self, **kwargs):
    p = get_drop_progress(self)
    stage = kwargs.get("stage", "model_call")
    chain = kwargs.get("model_chain") or ["unknown"]
    primary = chain[0]
    try:
        result = _call_with_progress_heartbeat(
            p, lambda: _v73_openrouter_chat_json(self, **kwargs),
            stage=stage, model=primary,
            detail=f"Structured model call · primary {primary}",
        )
        p.model_result(result[1])
        return result
    except Exception as e:
        p.detail = f"Model call failed: {type(e).__name__}: {e}"
        p._write_event("MODEL_CALL_ERROR", stage=stage, error=p.detail)
        p.render()
        raise


def _v76_progress_chat_text_web(self, **kwargs):
    p=get_drop_progress(self); stage=kwargs.get("stage","web_research"); chain=kwargs.get("model_chain") or ["unknown"]
    primary=chain[0]; wp=kwargs.get("web_profile") or {}
    try:
        result=_call_with_progress_heartbeat(
            p, lambda:_v76_openrouter_chat_text_web(self,**kwargs), stage=stage, model=primary,
            detail=f"Web evidence dossier · search+fetch · primary {primary} · max tools {wp.get('max_tool_calls','?')}")
        p.model_result(result[1]); return result
    except Exception as e:
        p.detail=f"Web evidence call failed: {type(e).__name__}: {e}"; p._write_event("MODEL_CALL_ERROR",stage=stage,error=p.detail); p.render(); raise


def _v76_progress_chat_json_strict(self, **kwargs):
    p=get_drop_progress(self); stage=kwargs.get("stage","strict_structurer"); chain=kwargs.get("model_chain") or ["unknown"]
    primary=chain[0]
    try:
        result=_call_with_progress_heartbeat(
            p, lambda:_v76_openrouter_chat_json_strict(self,**kwargs), stage=stage, model=primary,
            detail=f"Strict evidence structuring · primary {primary} · no web")
        p.model_result(result[1]); return result
    except Exception as e:
        p.detail=f"Strict structurer failed: {type(e).__name__}: {e}"; p._write_event("MODEL_CALL_ERROR",stage=stage,error=p.detail); p.render(); raise


OpenRouterClient.chat_json = _v74_chat_json
OpenRouterClient.chat_text_web = _v76_progress_chat_text_web
OpenRouterClient.chat_json_strict = _v76_progress_chat_json_strict


# ---------- High-level Idea progress ----------
_v73_compile_brief_fn = compile_brief
_v73_generate_candidates_fn = generate_candidates
_v73_gate_candidates_fn = gate_candidates
_v73_repair_candidates_fn = repair_candidates
_v73_run_generation_round_fn = run_generation_round


def compile_brief(client, state):
    p = get_drop_progress(client)
    p.start_phase("brief_compile", "Brief grounding + anchor", 1)
    p.start_step("Compile factual context + Brief Anchor", model=MODEL_STRATEGY["compiler"][0])
    try:
        result = _v73_compile_brief_fn(client, state)
        p.complete_step("Brief Anchor compiled and locally validated")
        p.finish_phase("Brief ready; it will not be recompiled on user refinement rounds")
        return result
    except Exception as e:
        p.fail_step(e)
        raise


def generate_candidates(client, state, round_index, machine_feedback=""):
    p = get_drop_progress(client)
    model = round_profile(round_index)["generator"][0]
    p.start_step(f"Generate Concept territories + candidates (Round {round_index})", model=model)
    try:
        result = _v73_generate_candidates_fn(client, state, round_index, machine_feedback)
        p.complete_step(f"{len(result.get('candidates',[]))} candidates generated")
        return result
    except Exception as e:
        p.fail_step(e); raise


def gate_candidates(client, state, batch, round_index, pass_name="initial"):
    p = get_drop_progress(client)
    model = round_profile(round_index)["validator"][0]
    label = "Adversarial Concept Gate" if pass_name == "initial" else "Re-run Concept Gate after repair"
    p.start_step(f"{label} (Round {round_index})", model=model)
    try:
        result = _v73_gate_candidates_fn(client, state, batch, round_index, pass_name)
        passed = sum(r.get("status") == "PASS" for r in result.get("reviews", []))
        p.complete_step(f"Gate complete · {passed} PASS · batch {result.get('batch_status')}")
        return result
    except Exception as e:
        p.fail_step(e); raise


def repair_candidates(client, state, batch, gate, round_index):
    p = get_drop_progress(client)
    p.ensure_extra_steps("idea_repair", 2, "Conditional repair activated: repair + re-gate")
    model = round_profile(round_index)["repair"][0]
    p.start_step(f"Repair validator-flagged Concept candidates (Round {round_index})", model=model)
    try:
        result = _v73_repair_candidates_fn(client, state, batch, gate, round_index)
        p.complete_step(f"Repaired {len(result[1])} candidate(s)")
        return result
    except Exception as e:
        p.fail_step(e); raise


def run_generation_round(client, state, round_index, machine_feedback=""):
    p = get_drop_progress(client)
    p.start_phase(f"idea_round_{round_index}", f"Idea Generation — Round {round_index}", 2)
    try:
        result = _v73_run_generation_round_fn(client, state, round_index, machine_feedback)
        p.finish_phase(f"Idea Round {round_index} finished · {len(result.get('cards',[]))} formal cards")
        return result
    except Exception as e:
        p.fail_step(e); raise


# IdeaSession methods resolve run_generation_round globally, so the wrappers above are used.
_v73_idea_advance = IdeaSession.advance_until_user_gate

def _v74_idea_advance(self):
    result = _v73_idea_advance(self)
    p = get_drop_progress(self.client)
    if self.status == "WAITING_FOR_USER":
        p.waiting(f"Idea Round {self.round_index} ready — waiting for Approve / Refine / Reject")
    elif self.status == "EXHAUSTED":
        p.state = "ERROR"; p.detail = "Idea round budget exhausted"; p._write_event("IDEA_EXHAUSTED"); p.render()
    return result

IdeaSession.advance_until_user_gate = _v74_idea_advance


# ---------- V7.9 downstream progress note ----------
# Music/cross-media progress is handled directly by the V7.9 Web Portfolio functions below.
# Legacy V7.3/V7.4 music wrappers are intentionally removed to avoid binding obsolete
# music functions before the V7.9 overrides are defined.

# ---------- Better user-facing progress widget ----------
_v73_render_drop_widget_fn = render_drop_widget

def render_drop_widget(session):
    p = get_drop_progress(session.client)
    if WIDGETS_AVAILABLE:
        progress_widget = widgets.HTML(value=p._bar_html(), layout=widgets.Layout(width="100%"))
        p.attach_widget(progress_widget)
        display(progress_widget)
    else:
        print(p.text_status())
    return _v73_render_drop_widget_fn(session)


# ---------- V7.4 final usage/progress summary ----------
def full_run_usage_summary_v74(logger):
    s = logger.summary()
    billed = [r for r in logger.records if RunLogger._is_billed_record(r)]
    s["web_search_requests"] = sum(int(r.get("usage", {}).get("web_search_requests") or 0) for r in billed)
    s["web_fetch_requests"] = sum(int(r.get("usage", {}).get("web_fetch_requests") or 0) for r in billed)
    s["output_tokens"] = s["totals"].get("completion_tokens", 0)
    p = get_drop_progress(logger)
    progress_summary = p.save_summary()
    s["progress"] = progress_summary
    logger.save_artifact("usage_summary_v74.json", s)
    print("\n=== DROP V7.4 FULL RUN SUMMARY ===")
    print("All model calls:", s["successful_calls"])
    print("Input tokens:", s["totals"]["prompt_tokens"])
    print("OUTPUT tokens:", s["totals"]["completion_tokens"])
    print("Total tokens:", s["totals"]["total_tokens"])
    print("Web search requests:", s["web_search_requests"], "| Web fetches:", s.get("web_fetch_requests",0))
    print("API-reported total cost USD:", s["totals"]["cost_usd"])
    print("Progress events:", progress_summary["event_count"])
    print("Progress log:", progress_summary["progress_log"])
    print("Full summary:", logger.dir / "usage_summary_v74.json")
    return s

# DropSession methods call this legacy name dynamically; point it to V7.4 summary.
full_run_usage_summary_v73 = full_run_usage_summary_v74

## V7.9 Downstream Override — Web-only Music + Cross-Media Concept Research

از این بخش به بعد downstream جدید تعریف می‌شود. مسیر embedding/MusicBrainz recommendation حذف شده است.

In [ ]:
# ============================================================
# V7.9 — WEB-ONLY CONCEPT RESEARCH CONFIG
# ============================================================

PORTFOLIO_MUSIC_PROVISIONAL = 10
PORTFOLIO_SCREEN_FINAL = 4
PORTFOLIO_ART_FINAL = 5
PORTFOLIO_SCIENCE_FINAL = 3
PORTFOLIO_ART_READING_FINAL = 3

# Cost caps: server tools are agentic but bounded.
V79_MUSIC_WEB_PROFILE = {
    "engine":"exa",
    "max_results":5,
    "max_total_results":24,
    "max_tool_calls":7,
    "search_context_size":"medium",
    "fetch_engine":"openrouter",
    "fetch_max_content_tokens":2600,
    "excluded_domains":["genius.com"],
}
V79_GENIUS_PROFILE = {
    "engine":"exa",
    "max_results":3,
    "max_total_results":24,
    "max_tool_calls":12,
    "search_context_size":"medium",
    "fetch_engine":"openrouter",
    "fetch_max_content_tokens":2200,
    "allowed_domains":["genius.com"],
}
V79_CULTURE_WEB_PROFILE = {
    "engine":"exa",
    "max_results":5,
    "max_total_results":30,
    "max_tool_calls":10,
    "search_context_size":"medium",
    "fetch_engine":"openrouter",
    "fetch_max_content_tokens":2800,
}

V79_MODELS = {
    "round_1":{
        "music":["anthropic/claude-sonnet-5","openai/gpt-5.6-sol","google/gemini-3.6-flash"],
        "genius":["anthropic/claude-sonnet-5","openai/gpt-5.6-sol","google/gemini-3.6-flash"],
        "culture":["anthropic/claude-sonnet-5","openai/gpt-5.6-sol","google/gemini-3.6-flash"],
        "critic":["openai/gpt-5.6-sol","anthropic/claude-sonnet-5","google/gemini-3.6-flash"],
    },
    "round_2":{
        "music":["openai/gpt-5.6-sol","anthropic/claude-sonnet-5","google/gemini-3.6-flash"],
        "genius":["openai/gpt-5.6-sol","anthropic/claude-sonnet-5","google/gemini-3.6-flash"],
        "culture":["openai/gpt-5.6-sol","anthropic/claude-sonnet-5","google/gemini-3.6-flash"],
        "critic":["anthropic/claude-sonnet-5","openai/gpt-5.6-sol","google/gemini-3.6-flash"],
    },
    "round_3":{
        "music":["anthropic/claude-sonnet-5","openai/gpt-5.6-sol"],
        "genius":["anthropic/claude-sonnet-5","openai/gpt-5.6-sol"],
        "culture":["anthropic/claude-sonnet-5","openai/gpt-5.6-sol"],
        "critic":["openai/gpt-5.6-sol","anthropic/claude-sonnet-5"],
    },
}

def _v79_profile(round_index:int):
    return V79_MODELS[f"round_{min(max(int(round_index),1),3)}"]


# Keep server-tool domain filters documented/current.
def _server_search_parameters(profile: Dict[str, Any]) -> Dict[str, Any]:
    out={}
    for k in ("engine","max_results","max_total_results","search_context_size","allowed_domains","excluded_domains"):
        if profile.get(k) is not None:
            out[k]=profile[k]
    return out

def _fetch_parameters(profile: Dict[str, Any]) -> Dict[str, Any]:
    out={
        "engine":profile.get("fetch_engine","openrouter"),
        "max_content_tokens":int(profile.get("fetch_max_content_tokens") or 3000),
    }
    if profile.get("allowed_domains"):
        out["allowed_domains"]=profile["allowed_domains"]
    if profile.get("excluded_domains"):
        out["blocked_domains"]=profile["excluded_domains"]
    return out


def _v79_compact_concept(c):
    c=c or {}
    return {
        "title":c.get("title"),"one_line":c.get("one_line"),
        "human_truth":c.get("human_truth"),"central_idea":c.get("central_idea"),
        "guest_takeaway":c.get("guest_takeaway"),"tone":c.get("tone") or [],
        "desired_feelings":c.get("desired_feelings") or [],
        "must_preserve":c.get("must_preserve") or [],
        "must_avoid":c.get("must_avoid") or [],
        "music_potential":((c.get("multi_domain_potential") or {}).get("music")),
        "media_potential":((c.get("multi_domain_potential") or {}).get("media")),
        "art_potential":((c.get("multi_domain_potential") or {}).get("art")),
        "article_potential":((c.get("multi_domain_potential") or {}).get("article")),
    }

def _v79_compact_anchor(a):
    a=a or {}
    return {
        "core_subjects":a.get("core_subjects") or [],
        "core_human_questions":a.get("core_human_questions") or [],
        "core_emotions":a.get("core_emotions") or [],
        "core_tensions":a.get("core_tensions") or [],
        "cultural_or_thematic_territories":a.get("cultural_or_thematic_territories") or [],
        "explicit_references":a.get("explicit_references") or [],
        "desired_world":a.get("desired_world") or [],
        "undesired_world":a.get("undesired_world") or [],
        "must_remain_recognizable":a.get("must_remain_recognizable") or [],
    }


def _v79_blocks(text,start,end):
    pat=re.compile(re.escape(start)+r"(.*?)"+re.escape(end),re.S|re.I)
    return [m.group(1).strip() for m in pat.finditer(text or "")]

def _v79_field(block,label):
    m=re.search(rf"(?mi)^\s*{re.escape(label)}\s*:\s*(.+?)\s*$",block)
    return m.group(1).strip() if m else None

def _v79_urls(raw):
    return [u.strip() for u in (raw or "").split(";") if u.strip().startswith("http")]

def _v79_num(x,default=0.0):
    try:return float(x)
    except:return float(default)

## V7.9 Music Discovery — Web only

این نسخه **هیچ candidateای از MusicBrainz/embedding dataset تولید نمی‌کند**.  
Candidateهای موسیقی فقط از Web Research مبتنی بر Approved Concept و Brief Anchor می‌آیند.  
iTunes فقط برای identity/listen-link قطعه‌ای که قبلاً از وب پیدا شده استفاده می‌شود، نه برای recommendation discovery.

In [ ]:
# ============================================================
# V7.9 — MUSIC WEB DISCOVERY (NO EMBEDDINGS, NO GENIUS YET)
# ============================================================

MUSIC_WEB_PROMPT_V79 = r"""
You are the DROP Music Deep Researcher. Use web search/fetch actively but economically.
The APPROVED_CONCEPT is the center. Find REAL music whose relation is proposition-level, not merely a similar mood.

Research strategy:
1) Search for the human proposition / emotional movement / cultural territory in music criticism, artist/label notes and interviews.
2) Search separately for sonic behavior that could embody the Concept: rhythm/pulse, tempo-feel, energy arc, texture, density, tension/release and conversational intrusiveness.
3) Search Iranian/Persian and international music. Do not force Iranian items if evidence is weak, but make a serious attempt.
4) For instrumental music, justify the recommendation primarily through sound/form evidence.
5) For vocal music, sound still matters; additionally verify the lyrical theme from credible sources. Never reproduce full lyrics.
6) Prefer official artist/label pages, Bandcamp/album notes, interviews, reputable music journalism/reviews and streaming metadata.
7) DO NOT use Genius now. A later single Genius audit checks the provisional top 10.
8) Avoid generic "nostalgic / warm / cinematic" matching unless the source evidence also connects to the Concept's underlying proposition.

Return 12-16 candidates, strongest first, plain text blocks only:

<<<MUSIC>>>
TITLE: exact released title
ARTIST: exact artist
ORIGIN: IRANIAN | INTERNATIONAL | UNKNOWN
VOCAL_TYPE: VOCAL | INSTRUMENTAL | MIXED | UNKNOWN
WHY_CONCEPT_FA: concise Persian proposition-level connection
SONIC_EVIDENCE_FA: evidence-grounded rhythm/pulse/energy/texture/form description
LYRIC_THEME_FA: concise Persian paraphrase | NA | UNKNOWN
CREATOR_CONTEXT_FA: attributable creator/artist statement | NOT_FOUND
WATCH_OUT_FA: concise risk | NONE
SOURCE_URLS: url1 ; url2 ; url3
<<<END_MUSIC>>>

Never invent track identity, lyrics, creator intent, nationality, URLs, BPM or technical audio facts.
""".strip()


def parse_music_web_v79(text):
    out=[]
    seen=set()
    for i,b in enumerate(_v79_blocks(text,"<<<MUSIC>>>","<<<END_MUSIC>>>"),1):
        title=_v79_field(b,"TITLE"); artist=_v79_field(b,"ARTIST")
        if not title or not artist: continue
        key=re.sub(r"[^a-z0-9\u0600-\u06ff]+","",(title+"::"+artist).casefold())
        if key in seen: continue
        seen.add(key)
        origin=(_v79_field(b,"ORIGIN") or "UNKNOWN").upper()
        if origin not in {"IRANIAN","INTERNATIONAL","UNKNOWN"}: origin="UNKNOWN"
        vocal=(_v79_field(b,"VOCAL_TYPE") or "UNKNOWN").upper()
        if vocal not in {"VOCAL","INSTRUMENTAL","MIXED","UNKNOWN"}: vocal="UNKNOWN"
        lyric=_v79_field(b,"LYRIC_THEME_FA")
        if lyric and lyric.upper() in {"NA","N/A","UNKNOWN","NONE"}: lyric=None
        creator=_v79_field(b,"CREATOR_CONTEXT_FA")
        if creator and creator.upper() in {"NOT_FOUND","UNKNOWN","NONE"}: creator=None
        watch=_v79_field(b,"WATCH_OUT_FA")
        if watch and watch.upper()=="NONE": watch=None
        out.append({
            "candidate_id":f"music_{i:02d}",
            "title":title,"artist":artist,"origin_bucket":origin,"vocal_type":vocal,
            "lyrical_theme_summary":lyric,
            "discovery_rank":i,
            "web_evidence":{
                "why_concept":_v79_field(b,"WHY_CONCEPT_FA") or "",
                "sonic":_v79_field(b,"SONIC_EVIDENCE_FA") or "",
                "lyric_theme":lyric,"creator_context":creator,"watch_out":watch,
                "source_urls":_v79_urls(_v79_field(b,"SOURCE_URLS")),
            },
            "source_routes":["WEB"],
        })
    return out


def music_web_discovery_v79(client,*,approved_concept,brief_anchor,project_brief="",round_index=1,feedback=""):
    p=get_drop_progress(client); prof=_v79_profile(round_index)
    p.start_step("Music — concept-led web discovery",model=prof["music"][0],detail="Web only · Genius deferred")
    payload={
        "APPROVED_CONCEPT":_v79_compact_concept(approved_concept),
        "BRIEF_ANCHOR":_v79_compact_anchor(brief_anchor),
        "PROJECT_BRIEF":(project_brief or "")[:5000],
        "MUSIC_FEEDBACK":feedback or "",
        "TARGET":"12-16 serious candidates; final provisional set will be 10",
    }
    try:
        text,_=client.chat_text_web(
            stage="music_web_discovery",round_index=round_index,
            system_prompt=MUSIC_WEB_PROMPT_V79,user_payload=payload,
            model_chain=prof["music"],max_tokens=5200,web_profile=V79_MUSIC_WEB_PROFILE,
            temperature=0.15,
            agent_goal="Web-only music discovery tied to the approved DROP human proposition, sonic evidence and lyrics where relevant",
        )
        tracks=parse_music_web_v79(text)
    except Exception as e:
        client.logger.log({"status":"event","stage":"music_web_discovery_nonfatal","round":round_index,
                           "error":f"{type(e).__name__}: {e}",
                           "usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
        tracks=[]
    # Identity check is optional evidence only; it never creates candidates.
    checked=[]
    for i,t in enumerate(tracks[:16],1):
        p.item_progress(i,min(len(tracks),16),"web-discovered track identity")
        x=deepcopy(t)
        try:x["identity_verification"]=verify_track_identity_lean(x)
        except Exception as e:
            x["identity_verification"]={"identity_verified":False,"itunes":[],"listen_url":None,
                                        "errors":[f"{type(e).__name__}: {e}"],
                                        "verification_scope":"itunes_identity_only_not_discovery"}
        checked.append(x)
    # provisional ranking respects researcher evidence ordering; identity is only a small confidence tie-break.
    checked.sort(key=lambda x:(-int(x.get("discovery_rank") or 999), bool((x.get("identity_verification") or {}).get("identity_verified"))),reverse=True)
    provisional=checked[:PORTFOLIO_MUSIC_PROVISIONAL]
    client.logger.save_artifact(f"music_web_provisional_round_{round_index:02d}.json",provisional)
    p.complete_step(f"Music web discovery complete · {len(provisional)} provisional tracks")
    return provisional

In [ ]:
# ============================================================
# V7.9 — ONE GENIUS AUDIT + SCREEN/ART/READING RESEARCH + FINAL CRITIC
# ============================================================

GENIUS_PROMPT_V79 = r"""
You are the DROP Genius Audit Agent. Research ONLY genius.com for the EXACT 10 supplied tracks.
This is an audit, not discovery.

For each track:
- verify whether an appropriate Genius song page exists;
- for vocal/mixed tracks, paraphrase the lyrical theme relevant to APPROVED_CONCEPT;
- distinguish community annotation from direct artist/songwriter explanation;
- CREATOR_DIRECT=YES only when Genius content is genuinely attributed to the creator/artist/songwriter;
- note whether Genius evidence contradicts the earlier interpretation.
For instrumental tracks, Genius may be NOT_APPLICABLE; never invent lyrics.

Return exactly one block per input index:
<<<GENIUS>>>
INDEX: 1
STATUS: FOUND | NOT_FOUND | NOT_APPLICABLE
SONG_URL: url | NONE
LYRIC_THEME_FA: concise paraphrase | NA | UNKNOWN
ANNOTATION_CONTEXT_FA: concise context | NONE
CREATOR_DIRECT: YES | NO
CREATOR_SPEAKER: name | NONE
CREATOR_SUMMARY_FA: concise Persian paraphrase | NONE
CONTRADICTION: NONE | LOW | MEDIUM | HIGH
EVIDENCE_NOTE_FA: concise note
<<<END_GENIUS>>>
""".strip()


def parse_genius_v79(text,tracks):
    parsed={}
    for b in _v79_blocks(text,"<<<GENIUS>>>","<<<END_GENIUS>>>"):
        try:i=int(_v79_field(b,"INDEX") or 0)
        except:continue
        parsed[i]={
            "status":(_v79_field(b,"STATUS") or "NOT_FOUND").upper(),
            "song_url":None if (_v79_field(b,"SONG_URL") or "").upper() in {"","NONE","UNKNOWN"} else _v79_field(b,"SONG_URL"),
            "lyric_theme":None if (_v79_field(b,"LYRIC_THEME_FA") or "").upper() in {"","NA","N/A","NONE","UNKNOWN"} else _v79_field(b,"LYRIC_THEME_FA"),
            "annotation_context":None if (_v79_field(b,"ANNOTATION_CONTEXT_FA") or "").upper() in {"","NONE","UNKNOWN"} else _v79_field(b,"ANNOTATION_CONTEXT_FA"),
            "creator_direct":(_v79_field(b,"CREATOR_DIRECT") or "NO").upper()=="YES",
            "creator_speaker":None if (_v79_field(b,"CREATOR_SPEAKER") or "").upper() in {"","NONE","UNKNOWN"} else _v79_field(b,"CREATOR_SPEAKER"),
            "creator_summary":None if (_v79_field(b,"CREATOR_SUMMARY_FA") or "").upper() in {"","NONE","UNKNOWN"} else _v79_field(b,"CREATOR_SUMMARY_FA"),
            "contradiction":(_v79_field(b,"CONTRADICTION") or "NONE").upper(),
            "evidence_note":_v79_field(b,"EVIDENCE_NOTE_FA") or "",
        }
    out=[]
    for i,t in enumerate(tracks,1):
        x=deepcopy(t)
        x["genius_audit"]=parsed.get(i,{
            "status":"NOT_FOUND","song_url":None,"lyric_theme":None,"annotation_context":None,
            "creator_direct":False,"creator_speaker":None,"creator_summary":None,
            "contradiction":"NONE","evidence_note":"No parseable Genius audit block returned."
        })
        out.append(x)
    return out


def genius_audit_v79(client,tracks,*,approved_concept,brief_anchor,round_index=1):
    if len(tracks)!=10:
        return [dict(deepcopy(t),genius_audit={
            "status":"NOT_FOUND","song_url":None,"lyric_theme":None,"annotation_context":None,
            "creator_direct":False,"creator_speaker":None,"creator_summary":None,
            "contradiction":"NONE","evidence_note":"Genius audit skipped because provisional set was not exactly 10."
        }) for t in tracks]
    p=get_drop_progress(client); prof=_v79_profile(round_index)
    p.start_step("Music — one Genius audit on provisional Top 10",model=prof["genius"][0],detail="genius.com only")
    payload={
        "APPROVED_CONCEPT":_v79_compact_concept(approved_concept),
        "BRIEF_ANCHOR":_v79_compact_anchor(brief_anchor),
        "TRACKS":[{"index":i,"title":t.get("title"),"artist":t.get("artist"),
                   "vocal_type":t.get("vocal_type"),"earlier_lyric_theme":t.get("lyrical_theme_summary")}
                  for i,t in enumerate(tracks,1)]
    }
    try:
        text,_=client.chat_text_web(
            stage="music_genius_audit",round_index=round_index,system_prompt=GENIUS_PROMPT_V79,
            user_payload=payload,model_chain=prof["genius"],max_tokens=4300,
            web_profile=V79_GENIUS_PROFILE,temperature=0.1,
            agent_goal="Single Genius-only evidence audit for the ten already-discovered music candidates",
        )
        out=parse_genius_v79(text,tracks)
    except Exception as e:
        out=parse_genius_v79("",tracks)
        client.logger.log({"status":"event","stage":"music_genius_audit_nonfatal","round":round_index,
                           "error":f"{type(e).__name__}: {e}",
                           "usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
    client.logger.save_artifact(f"music_genius_audit_round_{round_index:02d}.json",out)
    p.complete_step(f"Genius audit complete · {sum((x.get('genius_audit') or {}).get('status')=='FOUND' for x in out)}/{len(out)} found")
    return out


CULTURE_RESEARCH_PROMPT_V79 = r"""
You are the DROP Cross-Media Researcher. Use web search/fetch deeply but economically.
Everything must derive from the SAME APPROVED_CONCEPT and BRIEF_ANCHOR.

Find:
A) 5-7 FILMS OR SERIES where the human proposition, relationship, temporal structure, memory/attention/cultural question, or emotional movement genuinely relates to the Concept. Avoid merely matching aesthetic mood.
B) 6-8 ARTWORKS: painting, sculpture, photography, installation, performance, video art, architecture or another identifiable work. Prefer museum/artist/estate/gallery or strong critical sources.
C) 4-6 SCIENTIFIC/ACADEMIC READINGS: peer-reviewed papers, scholarly reviews, university/academic-publisher material that helps understand the human/psychological/social/cultural mechanism behind the Concept.
D) 4-6 ARTISTIC/CRITICAL READINGS: art criticism, essays, interviews, catalog texts, cultural criticism or serious humanities writing that opens the Concept artistically.

Evidence rules:
- exact real titles/creators/authors;
- explain proposition-level connection in Persian;
- include source URLs;
- scientific items need a journal/academic source and DOI or stable URL when available;
- do not pretend an artwork/film/article "means" the DROP Concept if the source only weakly supports that reading; label the connection as an interpretation.
- no invented dates, creators, quotations, DOI or URLs.

Return plain text blocks:

<<<SCREEN>>>
TITLE:
TYPE: FILM | SERIES
CREATOR:
YEAR: year | UNKNOWN
WHY_CONCEPT_FA:
CONNECTION_TYPE: DIRECT_THEME | STRUCTURAL_PARALLEL | INTERPRETIVE
WATCH_OUT_FA: ... | NONE
SOURCE_URLS: url1 ; url2
<<<END_SCREEN>>>

<<<ARTWORK>>>
TITLE:
ARTIST:
MEDIUM:
YEAR: year | UNKNOWN
COLLECTION_OR_LOCATION: ... | UNKNOWN
WHY_CONCEPT_FA:
INTERPRETATION_FA:
SOURCE_URLS: url1 ; url2
<<<END_ARTWORK>>>

<<<READING>>>
TITLE:
AUTHOR:
CATEGORY: SCIENTIFIC | ARTISTIC_CRITICAL
PUBLICATION:
YEAR: year | UNKNOWN
DOI_OR_STABLE_URL: url | NONE
WHY_CONCEPT_FA:
TAKEAWAY_FA:
SOURCE_URLS: url1 ; url2
<<<END_READING>>>
""".strip()


def parse_culture_v79(text):
    screen=[]; art=[]; reading=[]
    for i,b in enumerate(_v79_blocks(text,"<<<SCREEN>>>","<<<END_SCREEN>>>"),1):
        title=_v79_field(b,"TITLE")
        if not title: continue
        watch=_v79_field(b,"WATCH_OUT_FA")
        if watch and watch.upper()=="NONE": watch=None
        screen.append({
            "candidate_id":f"screen_{i:02d}","title":title,
            "type":(_v79_field(b,"TYPE") or "FILM").upper(),
            "creator":_v79_field(b,"CREATOR"),"year":_v79_field(b,"YEAR"),
            "why_concept_fa":_v79_field(b,"WHY_CONCEPT_FA") or "",
            "connection_type":(_v79_field(b,"CONNECTION_TYPE") or "INTERPRETIVE").upper(),
            "watch_out_fa":watch,"source_urls":_v79_urls(_v79_field(b,"SOURCE_URLS")),
        })
    for i,b in enumerate(_v79_blocks(text,"<<<ARTWORK>>>","<<<END_ARTWORK>>>"),1):
        title=_v79_field(b,"TITLE"); artist=_v79_field(b,"ARTIST")
        if not title or not artist: continue
        art.append({
            "candidate_id":f"art_{i:02d}","title":title,"artist":artist,
            "medium":_v79_field(b,"MEDIUM"),"year":_v79_field(b,"YEAR"),
            "collection_or_location":_v79_field(b,"COLLECTION_OR_LOCATION"),
            "why_concept_fa":_v79_field(b,"WHY_CONCEPT_FA") or "",
            "interpretation_fa":_v79_field(b,"INTERPRETATION_FA") or "",
            "source_urls":_v79_urls(_v79_field(b,"SOURCE_URLS")),
        })
    for i,b in enumerate(_v79_blocks(text,"<<<READING>>>","<<<END_READING>>>"),1):
        title=_v79_field(b,"TITLE")
        if not title: continue
        cat=(_v79_field(b,"CATEGORY") or "").upper()
        if cat not in {"SCIENTIFIC","ARTISTIC_CRITICAL"}: continue
        reading.append({
            "candidate_id":f"reading_{i:02d}","title":title,"author":_v79_field(b,"AUTHOR"),
            "category":cat,"publication":_v79_field(b,"PUBLICATION"),"year":_v79_field(b,"YEAR"),
            "doi_or_stable_url":None if (_v79_field(b,"DOI_OR_STABLE_URL") or "").upper() in {"","NONE","UNKNOWN"} else _v79_field(b,"DOI_OR_STABLE_URL"),
            "why_concept_fa":_v79_field(b,"WHY_CONCEPT_FA") or "",
            "takeaway_fa":_v79_field(b,"TAKEAWAY_FA") or "",
            "source_urls":_v79_urls(_v79_field(b,"SOURCE_URLS")),
        })
    return {"screen":screen,"artworks":art,"readings":reading}


def culture_web_research_v79(client,*,approved_concept,brief_anchor,project_brief="",round_index=1,feedback=""):
    p=get_drop_progress(client); prof=_v79_profile(round_index)
    p.start_step("Film/Series + Art + Scientific/Artistic readings",model=prof["culture"][0],detail="one cross-media web research pass")
    payload={
        "APPROVED_CONCEPT":_v79_compact_concept(approved_concept),
        "BRIEF_ANCHOR":_v79_compact_anchor(brief_anchor),
        "PROJECT_BRIEF":(project_brief or "")[:5000],
        "FEEDBACK":feedback or "",
    }
    try:
        text,_=client.chat_text_web(
            stage="portfolio_culture_web_research",round_index=round_index,
            system_prompt=CULTURE_RESEARCH_PROMPT_V79,user_payload=payload,
            model_chain=prof["culture"],max_tokens=7000,web_profile=V79_CULTURE_WEB_PROFILE,
            temperature=0.15,
            agent_goal="Evidence-grounded film/series, artwork, scientific and artistic-reading research from the approved DROP Concept",
        )
        result=parse_culture_v79(text)
    except Exception as e:
        result={"screen":[],"artworks":[],"readings":[]}
        client.logger.log({"status":"event","stage":"portfolio_culture_web_research_nonfatal","round":round_index,
                           "error":f"{type(e).__name__}: {e}",
                           "usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
    client.logger.save_artifact(f"culture_research_round_{round_index:02d}.json",result)
    p.complete_step(f"Cross-media research complete · screen={len(result['screen'])} · art={len(result['artworks'])} · readings={len(result['readings'])}")
    return result


PORTFOLIO_CRITIC_PROMPT_V79 = r"""
You are the DROP Independent Portfolio Critic. NO WEB. Evidence-bound.
Judge candidates only from the supplied APPROVED_CONCEPT, BRIEF_ANCHOR and candidate evidence.

The same Concept must remain recognizable across every medium.
Do not reward generic mood similarity.

For MUSIC: concept fit must be supported by sonic/form evidence, and when vocal also by lyrical evidence; Genius contradiction matters.
For SCREEN: distinguish genuine thematic/structural relation from superficial visual atmosphere.
For ART: allow interpretive relation, but penalize unsupported claims about artist intent.
For SCIENTIFIC reading: evidence confidence requires identifiable scholarly provenance and a real explanatory link.
For ARTISTIC_CRITICAL reading: it should deepen the Concept, not just share keywords.

Return one block for EVERY supplied item:
<<<CHECK>>>
ID:
VERDICT: KEEP | CONSIDER | DROP
CONCEPT_FIT: 0-5
EVIDENCE_CONFIDENCE: 0-5
MEDIUM_FIT: 0-5
WHY_FA: concise Persian
WATCH_OUT_FA: concise Persian | NONE
<<<END_CHECK>>>
""".strip()


def parse_checks_v79(text):
    out={}
    for b in _v79_blocks(text,"<<<CHECK>>>","<<<END_CHECK>>>"):
        cid=_v79_field(b,"ID")
        if not cid: continue
        watch=_v79_field(b,"WATCH_OUT_FA")
        if watch and watch.upper()=="NONE": watch=None
        out[cid]={
            "verdict":(_v79_field(b,"VERDICT") or "CONSIDER").upper(),
            "concept_fit":max(0,min(5,_v79_num(_v79_field(b,"CONCEPT_FIT"),2.5))),
            "evidence_confidence":max(0,min(5,_v79_num(_v79_field(b,"EVIDENCE_CONFIDENCE"),2.5))),
            "medium_fit":max(0,min(5,_v79_num(_v79_field(b,"MEDIUM_FIT"),2.5))),
            "why_fa":_v79_field(b,"WHY_FA") or "",
            "watch_out_fa":watch,
        }
    return out


def _v79_score(check):
    return round(0.55*check["concept_fit"]+0.25*check["evidence_confidence"]+0.20*check["medium_fit"],3)


def portfolio_critic_v79(client,*,music,culture,approved_concept,brief_anchor,round_index=1):
    p=get_drop_progress(client); prof=_v79_profile(round_index)
    p.start_step("Independent cross-domain Portfolio Critic",model=prof["critic"][0],detail="same Concept, all media")
    items=[]
    for t in music:
        g=t.get("genius_audit") or {}; w=t.get("web_evidence") or {}
        items.append({"id":t["candidate_id"],"domain":"MUSIC","title":t.get("title"),"creator":t.get("artist"),
                      "why":w.get("why_concept"),"sonic":w.get("sonic"),"lyric":g.get("lyric_theme") or t.get("lyrical_theme_summary"),
                      "creator_context":g.get("creator_summary") or w.get("creator_context"),"genius_contradiction":g.get("contradiction"),
                      "sources":w.get("source_urls") or []})
    for x in culture.get("screen",[]):
        items.append({"id":x["candidate_id"],"domain":"SCREEN","title":x.get("title"),"creator":x.get("creator"),
                      "why":x.get("why_concept_fa"),"connection_type":x.get("connection_type"),"sources":x.get("source_urls") or []})
    for x in culture.get("artworks",[]):
        items.append({"id":x["candidate_id"],"domain":"ART","title":x.get("title"),"creator":x.get("artist"),
                      "why":x.get("why_concept_fa"),"interpretation":x.get("interpretation_fa"),"sources":x.get("source_urls") or []})
    for x in culture.get("readings",[]):
        items.append({"id":x["candidate_id"],"domain":x.get("category"),"title":x.get("title"),"creator":x.get("author"),
                      "why":x.get("why_concept_fa"),"takeaway":x.get("takeaway_fa"),"publication":x.get("publication"),
                      "stable_url":x.get("doi_or_stable_url"),"sources":x.get("source_urls") or []})
    payload={"APPROVED_CONCEPT":_v79_compact_concept(approved_concept),"BRIEF_ANCHOR":_v79_compact_anchor(brief_anchor),"ITEMS":items}
    try:
        text,_=client.chat_text_plain_v77(
            stage="portfolio_final_critic",round_index=round_index,
            system_prompt=PORTFOLIO_CRITIC_PROMPT_V79,user_payload=payload,
            model_chain=prof["critic"],max_tokens=6500,temperature=0.1,
            agent_goal="Independent evidence-bound validation and ranking across music, screen, art and reading candidates",
        )
        checks=parse_checks_v79(text)
    except Exception as e:
        checks={}
        client.logger.log({"status":"event","stage":"portfolio_final_critic_nonfatal","round":round_index,
                           "error":f"{type(e).__name__}: {e}",
                           "usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
    p.complete_step(f"Portfolio critic complete · {len(checks)}/{len(items)} parsed judgments")
    return checks


def apply_portfolio_checks_v79(items,checks):
    out=[]
    for x in items:
        y=deepcopy(x)
        c=checks.get(y.get("candidate_id")) or {
            "verdict":"CONSIDER","concept_fit":2.5,"evidence_confidence":2.0,"medium_fit":2.5,
            "why_fa":"Critic block unavailable; retained only as a cautious candidate.","watch_out_fa":"نیازمند بازبینی انسانی"
        }
        y["portfolio_validation"]=c
        y["portfolio_score"]=_v79_score(c)
        out.append(y)
    out.sort(key=lambda z:(z["portfolio_validation"].get("verdict")=="KEEP",z["portfolio_score"]),reverse=True)
    return out

In [ ]:
# ============================================================
# V7.9 — CONCEPT RESEARCH PORTFOLIO ORCHESTRATOR + FINAL OUTPUT
# ============================================================

def _v79_select(items,n):
    # KEEP first, then CONSIDER; DROP only if necessary to avoid hiding research but not as primary recs.
    ranked=sorted(items,key=lambda x:(x.get("portfolio_validation",{}).get("verdict")=="KEEP",
                                      x.get("portfolio_validation",{}).get("verdict")=="CONSIDER",
                                      float(x.get("portfolio_score") or 0)),reverse=True)
    primary=[x for x in ranked if x.get("portfolio_validation",{}).get("verdict")!="DROP"]
    return (primary if primary else ranked)[:n]


def _v79_music_links(t):
    out=[]; seen=set()
    g=t.get("genius_audit") or {}; ident=t.get("identity_verification") or {}; web=t.get("web_evidence") or {}
    if g.get("song_url"): out.append(("Genius",g["song_url"]))
    if ident.get("listen_url"): out.append(("Listen",ident["listen_url"]))
    for u in web.get("source_urls") or []: out.append(("Source",u))
    clean=[]
    for label,u in out:
        if u and u not in seen: seen.add(u); clean.append((label,u))
    return clean[:5]


def run_concept_research_portfolio_v79(client,*,project_brief,brief_anchor,approved_concept,round_index=1,feedback=""):
    p=get_drop_progress(client)
    p.start_phase(f"portfolio_round_{round_index}",f"DROP Concept Research Portfolio — Round {round_index}",5)
    music=music_web_discovery_v79(client,approved_concept=approved_concept,brief_anchor=brief_anchor,
                                  project_brief=project_brief,round_index=round_index,feedback=feedback)
    # Conditional cheap recovery only if parser/research returned too few.
    if len(music)<10:
        client.logger.log({"status":"event","stage":"music_web_gap_needed","round":round_index,
                           "count":len(music),"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
        # Do not fabricate/pad: Genius simply audits the available set if <10.
    genius=genius_audit_v79(client,music[:10],approved_concept=approved_concept,brief_anchor=brief_anchor,round_index=round_index)
    culture=culture_web_research_v79(client,approved_concept=approved_concept,brief_anchor=brief_anchor,
                                     project_brief=project_brief,round_index=round_index,feedback=feedback)
    checks=portfolio_critic_v79(client,music=genius,culture=culture,approved_concept=approved_concept,
                                brief_anchor=brief_anchor,round_index=round_index)

    p.start_step("Assemble final Concept Portfolio",detail="deterministic selection + artifacts")
    music_ranked=apply_portfolio_checks_v79(genius,checks)
    screen_ranked=apply_portfolio_checks_v79(culture.get("screen",[]),checks)
    art_ranked=apply_portfolio_checks_v79(culture.get("artworks",[]),checks)
    reading_ranked=apply_portfolio_checks_v79(culture.get("readings",[]),checks)
    science=[x for x in reading_ranked if x.get("category")=="SCIENTIFIC"]
    artistic=[x for x in reading_ranked if x.get("category")=="ARTISTIC_CRITICAL"]

    # Rank labels inside each domain
    for group in [music_ranked,screen_ranked,art_ranked,science,artistic]:
        for i,x in enumerate(group,1): x["rank"]=i

    portfolio={
        "artifact_type":"drop_concept_research_portfolio",
        "version":"7.9",
        "approved_concept":deepcopy(approved_concept),
        "brief_anchor":deepcopy(brief_anchor),
        "music":{"ranked":music_ranked[:10],"recommended":_v79_select(music_ranked,10)},
        "screen":{"ranked":screen_ranked,"recommended":_v79_select(screen_ranked,PORTFOLIO_SCREEN_FINAL)},
        "artworks":{"ranked":art_ranked,"recommended":_v79_select(art_ranked,PORTFOLIO_ART_FINAL)},
        "readings":{
            "scientific":{"ranked":science,"recommended":_v79_select(science,PORTFOLIO_SCIENCE_FINAL)},
            "artistic_critical":{"ranked":artistic,"recommended":_v79_select(artistic,PORTFOLIO_ART_READING_FINAL)},
        },
        "coverage":{
            "music":len(music_ranked),"screen":len(screen_ranked),"artworks":len(art_ranked),
            "scientific_readings":len(science),"artistic_readings":len(artistic),
            "iranian_music":sum(x.get("origin_bucket")=="IRANIAN" for x in music_ranked),
            "genius_found":sum((x.get("genius_audit") or {}).get("status")=="FOUND" for x in music_ranked),
        },
        "round":round_index,
    }
    client.logger.save_artifact("DROP_CONCEPT_RESEARCH_PORTFOLIO.json",portfolio)
    p.complete_step("Final Concept Portfolio assembled")
    try:p.finish_phase(f"portfolio_round_{round_index}",f"Portfolio ready · music={len(music_ranked)} · screen={len(screen_ranked)} · art={len(art_ranked)} · readings={len(science)+len(artistic)}")
    except Exception:pass
    return portfolio


def render_concept_portfolio_v79(portfolio):
    c=(portfolio or {}).get("approved_concept") or {}
    print("\n"+"="*110)
    print("DROP CONCEPT RESEARCH PORTFOLIO")
    print("="*110)
    print("\n💡 CONCEPT:",c.get("title"))
    print(c.get("one_line") or "")
    print("Human truth:",c.get("human_truth") or "—")
    print("Central idea:",c.get("central_idea") or "—")
    print("Guest takeaway:",c.get("guest_takeaway") or "—")

    print("\n🎵 MUSIC")
    for x in ((portfolio.get("music") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}; w=x.get("web_evidence") or {}; g=x.get("genius_audit") or {}
        print(f"\n{x.get('rank')}) {x.get('artist')} — {x.get('title')} | {x.get('portfolio_score')}/5 | {v.get('verdict')}")
        print("   Why:",v.get("why_fa") or w.get("why_concept") or "—")
        print("   Sound:",w.get("sonic") or "—")
        if g.get("lyric_theme") or x.get("lyrical_theme_summary"):
            print("   Lyrics:",g.get("lyric_theme") or x.get("lyrical_theme_summary"))
        if g.get("creator_direct"):
            print("   Creator:",g.get("creator_speaker"),"—",g.get("creator_summary"))
        elif w.get("creator_context"):
            print("   Creator context:",w.get("creator_context"))
        if v.get("watch_out_fa") or w.get("watch_out"):
            print("   Watch out:",v.get("watch_out_fa") or w.get("watch_out"))
        links=_v79_music_links(x)
        if links: print("   Links:"," | ".join(f"{label}: {u}" for label,u in links))

    print("\n🎬 FILMS / SERIES")
    for x in ((portfolio.get("screen") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('title')} ({x.get('type')}, {x.get('year')}) — {x.get('creator')} | {x.get('portfolio_score')}/5")
        print("   Why:",v.get("why_fa") or x.get("why_concept_fa") or "—")
        if v.get("watch_out_fa") or x.get("watch_out_fa"): print("   Watch out:",v.get("watch_out_fa") or x.get("watch_out_fa"))
        if x.get("source_urls"): print("   Sources:"," | ".join(x["source_urls"][:3]))

    print("\n🖼️ ARTWORKS")
    for x in ((portfolio.get("artworks") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('artist')} — {x.get('title')} | {x.get('medium')} | {x.get('year')} | {x.get('portfolio_score')}/5")
        print("   Why:",v.get("why_fa") or x.get("why_concept_fa") or "—")
        print("   Interpretation:",x.get("interpretation_fa") or "—")
        if x.get("source_urls"): print("   Sources:"," | ".join(x["source_urls"][:3]))

    print("\n📚 SCIENTIFIC / ACADEMIC READINGS")
    for x in (((portfolio.get("readings") or {}).get("scientific") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('title')} — {x.get('author')} | {x.get('publication')} ({x.get('year')}) | {x.get('portfolio_score')}/5")
        print("   Why:",v.get("why_fa") or x.get("why_concept_fa") or "—")
        print("   Takeaway:",x.get("takeaway_fa") or "—")
        if x.get("doi_or_stable_url"): print("   Link:",x.get("doi_or_stable_url"))

    print("\n✍️ ARTISTIC / CRITICAL READINGS")
    for x in (((portfolio.get("readings") or {}).get("artistic_critical") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('title')} — {x.get('author')} | {x.get('publication')} ({x.get('year')}) | {x.get('portfolio_score')}/5")
        print("   Why:",v.get("why_fa") or x.get("why_concept_fa") or "—")
        print("   Takeaway:",x.get("takeaway_fa") or "—")
        if x.get("doi_or_stable_url"): print("   Link:",x.get("doi_or_stable_url"))

    print("\nCoverage:",portfolio.get("coverage"))


def _v79_markdown(portfolio):
    c=portfolio.get("approved_concept") or {}
    L=[f"# {c.get('title','DROP Concept')}","",f"**{c.get('one_line','')}**","",
       f"**Human truth:** {c.get('human_truth','—')}","",
       f"**Central idea:** {c.get('central_idea','—')}","",
       f"**Guest takeaway:** {c.get('guest_takeaway','—')}",""]
    L+=["---","","## 🎵 Music",""]
    for x in ((portfolio.get("music") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}; w=x.get("web_evidence") or {}
        L += [f"### {x.get('rank')}. {x.get('artist')} — {x.get('title')}",
              f"**Score:** {x.get('portfolio_score')}/5 · **Verdict:** {v.get('verdict')}",
              "",v.get("why_fa") or w.get("why_concept") or "—",""]
        links=_v79_music_links(x)
        if links: L += [" · ".join(f"[{a}]({u})" for a,u in links),""]
    L+=["---","","## 🎬 Films / Series",""]
    for x in ((portfolio.get("screen") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        L += [f"### {x.get('rank')}. {x.get('title')} ({x.get('year')})",f"*{x.get('type')} · {x.get('creator')}*","",
              v.get("why_fa") or x.get("why_concept_fa") or "—",""]
        if x.get("source_urls"): L += [" · ".join(f"[Source]({u})" for u in x["source_urls"][:2]),""]
    L+=["---","","## 🖼️ Artworks",""]
    for x in ((portfolio.get("artworks") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        L += [f"### {x.get('rank')}. {x.get('artist')} — {x.get('title')}",f"*{x.get('medium')} · {x.get('year')}*","",
              v.get("why_fa") or x.get("why_concept_fa") or "—","",x.get("interpretation_fa") or "",""]
        if x.get("source_urls"): L += [" · ".join(f"[Source]({u})" for u in x["source_urls"][:2]),""]
    L+=["---","","## 📚 Scientific / Academic Readings",""]
    for x in (((portfolio.get("readings") or {}).get("scientific") or {}).get("recommended") or []):
        L += [f"### {x.get('rank')}. {x.get('title')}",f"*{x.get('author')} · {x.get('publication')} · {x.get('year')}*","",
              (x.get("portfolio_validation") or {}).get("why_fa") or x.get("why_concept_fa") or "—","",
              f"**Takeaway:** {x.get('takeaway_fa') or '—'}",""]
        if x.get("doi_or_stable_url"): L += [f"[Read]({x.get('doi_or_stable_url')})",""]
    L+=["---","","## ✍️ Artistic / Critical Readings",""]
    for x in (((portfolio.get("readings") or {}).get("artistic_critical") or {}).get("recommended") or []):
        L += [f"### {x.get('rank')}. {x.get('title')}",f"*{x.get('author')} · {x.get('publication')} · {x.get('year')}*","",
              (x.get("portfolio_validation") or {}).get("why_fa") or x.get("why_concept_fa") or "—","",
              f"**Takeaway:** {x.get('takeaway_fa') or '—'}",""]
        if x.get("doi_or_stable_url"): L += [f"[Read]({x.get('doi_or_stable_url')})",""]
    return "\n".join(L)


def run_approved_concept_portfolio(session,feedback=""):
    if session.status=="IDEA_WAITING":
        print("⏸ ابتدا یک Concept را تأیید کن."); return None
    if not session.approved_concept:
        raise RuntimeError("No approved Concept.")
    session.status="PORTFOLIO_RESEARCHING"
    try:
        result=run_concept_research_portfolio_v79(
            session.client,project_brief=session.idea_session.state.project_brief,
            brief_anchor=session.idea_session.state.anchor,approved_concept=session.approved_concept,
            round_index=max(1,getattr(session,"music_round_index",0)+1),feedback=feedback,
        )
    except Exception:
        session.status="IDEA_APPROVED_AWAITING_MUSIC"
        raise
    session.portfolio_result=result
    session.music_result={"tracks":(result.get("music") or {}).get("ranked",[]),"coverage":result.get("coverage")}
    session.status="COMPLETE"
    md=_v79_markdown(result)
    (session.logger.dir/"DROP_CONCEPT_RESEARCH_PORTFOLIO.md").write_text(md,encoding="utf-8")
    session.logger.save_artifact("drop_final_result.json",{
        "status":"COMPLETE","run_id":session.logger.run_id,
        "approved_concept":session.approved_concept,"portfolio":result,
    })
    render_concept_portfolio_v79(result)
    s=session.logger.summary(); session.logger.save_artifact("usage_summary_v79.json",s)
    print("\n=== DROP V7.9 FULL RUN SUMMARY ===")
    print("Input tokens:",s["totals"].get("prompt_tokens",0),"| OUTPUT:",s["totals"].get("completion_tokens",0),
          "| Total:",s["totals"].get("total_tokens",0),"| Cost USD:",s["totals"].get("cost_usd",0.0))
    print("Artifacts:",session.logger.dir)
    return result


# Backward-compatible alias: the old Step-B name now runs the full Concept Portfolio.
def run_approved_music_research(session,feedback=""):
    return run_approved_concept_portfolio(session,feedback=feedback)

In [ ]:
# ============================================================
# V7.9 AUTO END-TO-END INTERNALS
# ============================================================
def _auto_concept_sort_key(card: Dict[str, Any]):
    v=card.get("validation") or {}
    return (float(v.get("portfolio_score") or 0),float(v.get("anchor_score") or 0),-len(v.get("risks") or []))

def auto_select_best_concept(session: DropSession):
    session.sync_status()
    if session.status!="IDEA_WAITING": raise RuntimeError(f"Auto selection requires IDEA_WAITING; got {session.status}")
    cards=session.cards
    if not cards: raise RuntimeError("No validated Concept cards.")
    best_idx=max(range(len(cards)),key=lambda i:_auto_concept_sort_key(cards[i]))
    n=best_idx+1; selected=deepcopy(cards[best_idx]); v=selected.get("validation") or {}
    decision={"mode":"AUTO_END_TO_END","card_number":n,"candidate_id":selected.get("candidate_id"),
              "title":selected.get("title"),"portfolio_score":v.get("portfolio_score"),"anchor_score":v.get("anchor_score"),
              "selection_policy":"max portfolio_score → anchor_score → fewer risks"}
    session.logger.save_artifact("auto_concept_selection.json",decision)
    log_session_event(session.logger,"AUTO_CONCEPT_SELECTED",**decision)
    print("\n🤖 AUTO CONCEPT SELECTION:",selected.get("title"),"| Portfolio:",v.get("portfolio_score"),"| Anchor:",v.get("anchor_score"))
    session.approve_concept(n,auto_continue=True)
    return n,selected

def run_drop_auto_with_client(client:Any,*,project_brief:str,initial_context:str="",desired_feeling:str="",seed:str="",
                              previous_ideas=None,music_context:str="",project_id:str="drop_auto"):
    ds=start_drop_session(client,project_brief=project_brief,initial_context=initial_context,
                          desired_feeling=desired_feeling,seed=seed,previous_ideas=previous_ideas or [],
                          music_context=music_context,project_id=project_id)
    if ds.status=="IDEA_EXHAUSTED": raise RuntimeError("Idea round budget exhausted.")
    n,selected=auto_select_best_concept(ds)
    portfolio=run_approved_concept_portfolio(ds)
    manifest={"mode":"AUTO_END_TO_END","project_id":project_id,"run_id":ds.logger.run_id,"status":ds.status,
              "selected_card_number":n,"selected_concept":selected,
              "music_count":len(((portfolio or {}).get("music") or {}).get("ranked",[])),
              "screen_count":len(((portfolio or {}).get("screen") or {}).get("recommended",[])),
              "art_count":len(((portfolio or {}).get("artworks") or {}).get("recommended",[])),
              "reading_count":len((((portfolio or {}).get("readings") or {}).get("scientific") or {}).get("recommended",[]))+
                              len((((portfolio or {}).get("readings") or {}).get("artistic_critical") or {}).get("recommended",[])),
              "run_dir":str(ds.logger.dir)}
    ds.logger.save_artifact("auto_run_manifest.json",manifest)
    return ds,manifest

def run_drop_auto_end_to_end(api_key:str):
    api_key=(api_key or "").strip()
    if not api_key: raise ValueError("OpenRouter API key is required.")
    logger=RunLogger(project_id="drop_auto"); client=OpenRouterClient(api_key=api_key,logger=logger)
    print("🚀 DROP V7.9 Auto End-to-End")
    print("Idea → validated Concept → Web-only Music + Genius → Film/Series + Art + Scientific/Artistic Readings → Final Portfolio")
    return run_drop_auto_with_client(client,project_brief=project_brief,initial_context=initial_context,
                                     desired_feeling=desired_feeling,seed=seed,previous_ideas=previous_ideas,
                                     music_context=music_context,project_id="drop_auto")

## V7.10 Downstream Optimization — Music + Art only

**Idea generation / validation / Human Gate above is unchanged.**  
This override only improves the research that happens *after* an approved Concept exists.

### Goals
- no new LLM stage and no embedding/catalog discovery;
- preserve the existing web-search ceilings rather than cutting quality headroom;
- give Music a tighter evidence-first retrieval lens so it wastes fewer searches/fetches;
- use a source hierarchy for Art: Smarthistory / Public Delivery / Art21 / The Art Story first, then strong museum/institutional resources;
- separate **artist-stated intent**, **curatorial/scholarly interpretation**, and **DROP's own interpretive connection**;
- make each artwork explanation substantially more useful without adding another research agent.

In [ ]:
# ============================================================
# V7.10 — QUALITY-SAFE DOWNSTREAM OPTIMIZATION
# IMPORTANT: Idea-generation functions above are NOT modified.
# ============================================================

# Keep the same hard web ceilings as V7.9. We optimize expected use through
# better source targeting + stop conditions, rather than reducing quality headroom.
V710_MUSIC_WEB_PROFILE = deepcopy(V79_MUSIC_WEB_PROFILE)
V710_CULTURE_WEB_PROFILE = deepcopy(V79_CULTURE_WEB_PROFILE)

# Source policy distilled from the user-provided Art research guide.
# This is guidance, NOT a hard allow-list: a more authoritative artist/institution source may win.
ART_RESEARCH_SOURCE_GUIDE_V710 = {
    "core_hubs": [
        {"domain":"smarthistory.org", "best_for":"broad cultural/historical context and substantial artwork interpretation"},
        {"domain":"publicdelivery.org", "best_for":"contemporary installations/public art and approachable concept explanation"},
        {"domain":"art21.org", "best_for":"artist voice, intention, process, and concept-led discovery"},
        {"domain":"theartstory.org", "best_for":"artwork analysis connected to artist practice and movements"},
    ],
    "institutional_supplements": [
        {"domain":"moma.org", "best_for":"underlying conceptual questions in modern/contemporary art"},
        {"domain":"metmuseum.org", "best_for":"cultural, religious, symbolic and historical context"},
        {"domain":"artsandculture.google.com", "best_for":"curated institutional Stories and visual walkthroughs; verify authoring institution"},
        {"domain":"tate.org.uk", "best_for":"social/political/philosophical interpretation of modern/contemporary work"},
        {"domain":"mplus.org.hk", "best_for":"contemporary Asian perspectives and artist interviews"},
        {"domain":"nationalgallery.org.uk", "best_for":"close reading of paintings and competing interpretations"},
    ],
    "source_rules": [
        "Prefer artist/estate/museum/commissioning-institution primary evidence when a claim is about artist intent.",
        "Smarthistory/Public Delivery/Art21/The Art Story are preferred interpretation/discovery hubs, not exhaustive catalogues.",
        "Artsy is a marketplace and must not be the primary conceptual evidence source.",
        "WikiArt may help discovery but is not sufficient as the main interpretation source unless a page itself contains strong sourced analysis.",
        "Keep artist statement, curator/scholar interpretation, and DROP/system interpretation explicitly separate.",
        "If artist intent is not directly evidenced, write NOT_FOUND rather than attributing an interpretation to the artist.",
    ]
}


def _v710_compact_text(x, max_chars=700):
    if x is None:
        return None
    if isinstance(x, list):
        x="; ".join(str(z) for z in x if z is not None)
    x=str(x).strip()
    return x[:max_chars] if x else None


def build_music_retrieval_lens_v710(approved_concept, brief_anchor, feedback=""):
    """Deterministic research lens: more guidance, zero extra model tokens/calls."""
    c=approved_concept or {}; a=brief_anchor or {}
    return {
        "concept_title":c.get("title"),
        "human_proposition":c.get("human_truth") or c.get("central_idea"),
        "central_idea":c.get("central_idea"),
        "guest_takeaway":c.get("guest_takeaway"),
        "music_interpretation":((c.get("multi_domain_potential") or {}).get("music")),
        "tone":c.get("tone") or [],
        "desired_feelings":c.get("desired_feelings") or [],
        "core_emotions":a.get("core_emotions") or [],
        "core_tensions":a.get("core_tensions") or [],
        "cultural_territories":a.get("cultural_or_thematic_territories") or [],
        "explicit_references":a.get("explicit_references") or [],
        "must_preserve":c.get("must_preserve") or a.get("must_remain_recognizable") or [],
        "must_avoid":c.get("must_avoid") or a.get("undesired_world") or [],
        "user_music_feedback":feedback or "",
        "retrieval_questions":[
            "Which real tracks are discussed by artists/labels/critics in terms that genuinely map to the human proposition?",
            "Which tracks embody the proposition through form: repetition/return, transformation, pacing, rhythmic behavior, tension/release, density or texture?",
            "For vocal tracks, does the lyrical theme support the proposition rather than merely the mood?",
            "For Iranian/Persian candidates, is the relation evidence-backed rather than added only for geographic diversity?",
        ],
        "anti_shortcuts":[
            "Mood words alone are insufficient evidence.",
            "Do not infer BPM, lyrics, nationality, artist intent or track history without a source.",
            "Prefer one strong primary/critical source to several weak snippets.",
        ]
    }


def build_art_retrieval_lens_v710(approved_concept, brief_anchor):
    c=approved_concept or {}; a=brief_anchor or {}
    return {
        "concept_title":c.get("title"),
        "human_proposition":c.get("human_truth") or c.get("central_idea"),
        "central_idea":c.get("central_idea"),
        "guest_takeaway":c.get("guest_takeaway"),
        "art_interpretation":((c.get("multi_domain_potential") or {}).get("art")),
        "core_human_questions":a.get("core_human_questions") or [],
        "core_tensions":a.get("core_tensions") or [],
        "cultural_territories":a.get("cultural_or_thematic_territories") or [],
        "explicit_references":a.get("explicit_references") or [],
        "must_preserve":c.get("must_preserve") or a.get("must_remain_recognizable") or [],
        "must_avoid":c.get("must_avoid") or a.get("undesired_world") or [],
        "research_questions":[
            "What is visibly/materially happening in the work?",
            "Why does this form/material/medium matter to the work's documented meaning?",
            "What did the artist explicitly say, if anything?",
            "What do curators/scholars/institutions interpret, and what remains uncertain?",
            "What historical/cultural context is necessary to understand the work?",
            "How does DROP connect the work to the approved Concept without pretending that this connection is the artist's stated meaning?",
        ]
    }


# ----------------------------- MUSIC -----------------------------
MUSIC_WEB_PROMPT_V710 = r"""
You are the DROP Music Deep Researcher. Use web search/fetch actively, selectively and economically.
The APPROVED_CONCEPT is the center. You receive a MUSIC_RETRIEVAL_LENS that already decomposes what matters.

QUALITY-PRESERVING SEARCH PLAN:
A) Proposition route: search creator/label notes, interviews and serious criticism for tracks genuinely tied to the human proposition.
B) Sonic/form route: search only likely candidates for documented rhythm/pulse, tempo-feel, energy arc, texture, density, repetition/transformation, tension/release and conversational intrusiveness.
C) Iranian/Persian route: make a serious evidence-based search using Persian and English variants where useful.
D) International route: search globally; avoid obvious canonical choices unless their evidence is genuinely strong.

COST DISCIPLINE:
- Do not perform broad exploratory fetches after enough evidence-qualified candidates exist.
- Search first; fetch only pages that can materially support a top candidate.
- Prefer one authoritative/primary page plus one strong independent source over many redundant sources.
- Stop once 12 evidence-qualified, materially different candidates are available; return at most 14 only if the extra items are genuinely competitive.
- Genius is forbidden here; a later single Genius audit handles the provisional top 10.

EVIDENCE RULES:
- Instrumental: the core justification must come from documented sound/form/structure, not invented symbolism.
- Vocal/mixed: sound/form still matters; additionally verify lyrical theme from credible evidence without reproducing lyrics.
- Artist/creator intent may be claimed only from directly attributable creator/label/interview evidence.
- Mood-only matching (nostalgic/warm/cinematic/etc.) is insufficient unless tied to the Concept's proposition.
- Never invent identity, lyrics, nationality, URLs, BPM, technical audio facts or artist intent.

Return strongest first, plain text blocks only:
<<<MUSIC>>>
TITLE: exact released title
ARTIST: exact artist
ORIGIN: IRANIAN | INTERNATIONAL | UNKNOWN
VOCAL_TYPE: VOCAL | INSTRUMENTAL | MIXED | UNKNOWN
CONCEPT_DIMENSION: HUMAN_TRUTH | TEMPORAL | MEMORY | SOCIAL | CULTURAL | ATTENTION | RITUAL | OTHER
WHY_CONCEPT_FA: concise Persian proposition-level connection
SONIC_EVIDENCE_FA: evidence-grounded rhythm/pulse/energy/texture/form description
LYRIC_THEME_FA: concise Persian paraphrase | NA | UNKNOWN
CREATOR_CONTEXT_FA: attributable creator/artist statement | NOT_FOUND
SOURCE_QUALITY: CREATOR_PRIMARY | INSTITUTIONAL_OR_LABEL | REPUTABLE_SECONDARY | MIXED | WEAK
EVIDENCE_LIMITATION_FA: what is not established | NONE
WATCH_OUT_FA: concise risk | NONE
SOURCE_URLS: url1 ; url2 ; url3
<<<END_MUSIC>>>
""".strip()


def parse_music_web_v710(text):
    out=[]; seen=set()
    for i,b in enumerate(_v79_blocks(text,"<<<MUSIC>>>","<<<END_MUSIC>>>"),1):
        title=_v79_field(b,"TITLE"); artist=_v79_field(b,"ARTIST")
        if not title or not artist: continue
        key=re.sub(r"[^a-z0-9\u0600-\u06ff]+","",(title+"::"+artist).casefold())
        if key in seen: continue
        seen.add(key)
        origin=(_v79_field(b,"ORIGIN") or "UNKNOWN").upper()
        if origin not in {"IRANIAN","INTERNATIONAL","UNKNOWN"}: origin="UNKNOWN"
        vocal=(_v79_field(b,"VOCAL_TYPE") or "UNKNOWN").upper()
        if vocal not in {"VOCAL","INSTRUMENTAL","MIXED","UNKNOWN"}: vocal="UNKNOWN"
        lyric=_v79_field(b,"LYRIC_THEME_FA")
        if lyric and lyric.upper() in {"NA","N/A","UNKNOWN","NONE"}: lyric=None
        creator=_v79_field(b,"CREATOR_CONTEXT_FA")
        if creator and creator.upper() in {"NOT_FOUND","UNKNOWN","NONE"}: creator=None
        watch=_v79_field(b,"WATCH_OUT_FA")
        if watch and watch.upper()=="NONE": watch=None
        limit=_v79_field(b,"EVIDENCE_LIMITATION_FA")
        if limit and limit.upper()=="NONE": limit=None
        sq=(_v79_field(b,"SOURCE_QUALITY") or "MIXED").upper()
        if sq not in {"CREATOR_PRIMARY","INSTITUTIONAL_OR_LABEL","REPUTABLE_SECONDARY","MIXED","WEAK"}: sq="MIXED"
        out.append({
            "candidate_id":f"music_{i:02d}","title":title,"artist":artist,
            "origin_bucket":origin,"vocal_type":vocal,"lyrical_theme_summary":lyric,
            "discovery_rank":i,"source_routes":["WEB"],
            "concept_dimension":(_v79_field(b,"CONCEPT_DIMENSION") or "OTHER").upper(),
            "source_quality":sq,
            "evidence_limitation_fa":limit,
            "web_evidence":{
                "why_concept":_v79_field(b,"WHY_CONCEPT_FA") or "",
                "sonic":_v79_field(b,"SONIC_EVIDENCE_FA") or "",
                "lyric_theme":lyric,"creator_context":creator,"watch_out":watch,
                "source_urls":_v79_urls(_v79_field(b,"SOURCE_URLS")),
            },
        })
    return out


def music_web_discovery_v710(client,*,approved_concept,brief_anchor,project_brief="",round_index=1,feedback=""):
    p=get_drop_progress(client); prof=_v79_profile(round_index)
    p.start_step("Music — evidence-first concept web discovery",model=prof["music"][0],detail="Web only · targeted lens · Genius deferred")
    lens=build_music_retrieval_lens_v710(approved_concept,brief_anchor,feedback)
    payload={
        "APPROVED_CONCEPT":_v79_compact_concept(approved_concept),
        "BRIEF_ANCHOR":_v79_compact_anchor(brief_anchor),
        "MUSIC_RETRIEVAL_LENS":lens,
        # The anchor/concept carry the authoritative lineage. Keep only a bounded raw brief excerpt
        # for constraints that may not have compacted cleanly.
        "PROJECT_BRIEF_EXCERPT":(project_brief or "")[:5000],
        "TARGET":"12 evidence-qualified candidates; 14 only if genuinely competitive; provisional final=10",
    }
    try:
        text,_=client.chat_text_web(
            stage="music_web_discovery",round_index=round_index,
            system_prompt=MUSIC_WEB_PROMPT_V710,user_payload=payload,
            model_chain=prof["music"],max_tokens=5200,web_profile=V710_MUSIC_WEB_PROFILE,
            temperature=0.12,
            agent_goal="Evidence-first web-only music discovery using an explicit DROP retrieval lens; minimize redundant searches without reducing search ceiling",
        )
        tracks=parse_music_web_v710(text)
    except Exception as e:
        client.logger.log({"status":"event","stage":"music_web_discovery_nonfatal","round":round_index,
                           "error":f"{type(e).__name__}: {e}",
                           "usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
        tracks=[]
    checked=[]
    for i,t in enumerate(tracks[:14],1):
        p.item_progress(i,min(len(tracks),14),"web-discovered track identity")
        x=deepcopy(t)
        try:x["identity_verification"]=verify_track_identity_lean(x)
        except Exception as e:
            x["identity_verification"]={"identity_verified":False,"itunes":[],"listen_url":None,
                                        "errors":[f"{type(e).__name__}: {e}"],"verification_scope":"itunes_identity_only_not_discovery"}
        checked.append(x)
    # Preserve research rank, but use source-quality and verified identity as deterministic tie-breaks.
    q={"CREATOR_PRIMARY":5,"INSTITUTIONAL_OR_LABEL":4,"REPUTABLE_SECONDARY":3,"MIXED":2,"WEAK":1}
    checked.sort(key=lambda x:(-int(x.get("discovery_rank") or 999),q.get(x.get("source_quality"),0),bool((x.get("identity_verification") or {}).get("identity_verified"))),reverse=True)
    provisional=checked[:PORTFOLIO_MUSIC_PROVISIONAL]
    client.logger.save_artifact(f"music_web_provisional_round_{round_index:02d}.json",provisional)
    p.complete_step(f"Music web discovery complete · {len(provisional)} provisional tracks")
    return provisional


# ----------------------------- ART + CULTURE -----------------------------
CULTURE_RESEARCH_PROMPT_V710 = r"""
You are the DROP Cross-Media Researcher. Use web search/fetch deeply but economically.
Everything must derive from the SAME APPROVED_CONCEPT and BRIEF_ANCHOR.
You also receive ART_RETRIEVAL_LENS and ART_SOURCE_GUIDE. Treat them as search guidance, not facts about any specific artwork.

Find:
A) 5-7 FILMS OR SERIES where the human proposition, relationship, temporal structure, memory/attention/cultural question, or emotional movement genuinely relates to the Concept. Avoid aesthetic-mood matching.
B) 6-7 ARTWORKS: painting, sculpture, photography, installation, performance, video art, architecture or another identifiable work.
C) 4-6 SCIENTIFIC/ACADEMIC READINGS that explain a human/psychological/social/cultural mechanism behind the Concept.
D) 4-6 ARTISTIC/CRITICAL READINGS that deepen the Concept through serious artistic/humanities thinking.

ART SEARCH — SOURCE-FIRST AND INTERPRETATION-AWARE:
1) Start concept-led discovery with the source guide: Smarthistory for broad historical/cultural interpretation; Public Delivery for contemporary/public/installation work; Art21 for artist voice/process/theme; The Art Story for artworks in wider artistic practice.
2) Supplement with MoMA, Met, Tate, M+, National Gallery, curated Google Arts & Culture Stories, official artist/estate/gallery/commissioning-institution sources when they better fit the work.
3) Do NOT use an art marketplace/listing as the main conceptual evidence. WikiArt may assist discovery but is not enough by itself for a strong conceptual interpretation.
4) Search/fetch only candidate pages that can support a final recommendation. Prefer 1-2 strong complementary sources to redundant pages.
5) Stop once 6-7 genuinely strong art candidates exist.

ART ATTRIBUTION DISCIPLINE:
- ARTIST_INTENT_FA = only what is directly evidenced as the artist's own intention/process/statement; otherwise NOT_FOUND.
- CURATOR_SCHOLAR_INTERPRETATION_FA = attributed institutional/curatorial/scholarly reading; otherwise NOT_FOUND.
- DROP_CONNECTION_FA = our evidence-bounded interpretation of why the artwork helps think with this DROP Concept. Never present this as the artist's stated meaning unless the artist actually said it.
- OBSERVABLE_FORM_FA describes what the cited source/documentation supports about the work's visible/material/formal setup.
- MATERIAL_FORM_SIGNIFICANCE_FA explains why material/form/medium matters, only when supported.
- CULTURAL_HISTORICAL_CONTEXT_FA gives only context needed to understand the work.
- If interpretations conflict or are uncertain, make that uncertainty visible.

GENERAL EVIDENCE RULES:
- exact real titles/creators/authors;
- proposition-level connection in Persian;
- scientific items need identifiable academic provenance and DOI/stable URL when available;
- no invented dates, creators, quotations, DOI or URLs.

Return plain text blocks:

<<<SCREEN>>>
TITLE:
TYPE: FILM | SERIES
CREATOR:
YEAR: year | UNKNOWN
WHY_CONCEPT_FA:
CONNECTION_TYPE: DIRECT_THEME | STRUCTURAL_PARALLEL | INTERPRETIVE
WATCH_OUT_FA: ... | NONE
SOURCE_URLS: url1 ; url2
<<<END_SCREEN>>>

<<<ARTWORK>>>
TITLE:
ARTIST:
MEDIUM:
YEAR: year | UNKNOWN
COLLECTION_OR_LOCATION: ... | UNKNOWN
OBSERVABLE_FORM_FA:
MATERIAL_FORM_SIGNIFICANCE_FA: ... | NOT_FOUND
ARTIST_INTENT_FA: ... | NOT_FOUND
CURATOR_SCHOLAR_INTERPRETATION_FA: ... | NOT_FOUND
CULTURAL_HISTORICAL_CONTEXT_FA: ... | NOT_FOUND
DROP_CONNECTION_FA: detailed Persian explanation of why this work is useful for the approved Concept
CONNECTION_BASIS: ARTIST_STATED | CURATORIAL | SCHOLARLY | SYSTEM_INTERPRETATION | MIXED
SOURCE_QUALITY: PRIMARY_PLUS_INTERPRETATION | PRIMARY | STRONG_SECONDARY | MIXED
UNCERTAINTY_FA: ... | NONE
SOURCE_URLS: url1 ; url2 ; url3
<<<END_ARTWORK>>>

<<<READING>>>
TITLE:
AUTHOR:
CATEGORY: SCIENTIFIC | ARTISTIC_CRITICAL
PUBLICATION:
YEAR: year | UNKNOWN
DOI_OR_STABLE_URL: url | NONE
WHY_CONCEPT_FA:
TAKEAWAY_FA:
SOURCE_URLS: url1 ; url2
<<<END_READING>>>
""".strip()


def _none_if_marker_v710(v):
    if v is None:return None
    return None if v.strip().upper() in {"","NONE","UNKNOWN","NOT_FOUND","N/A","NA"} else v.strip()


def parse_culture_v710(text):
    # Keep screen/readings exactly compatible with V7.9.
    base=parse_culture_v79(text)
    art=[]
    for i,b in enumerate(_v79_blocks(text,"<<<ARTWORK>>>","<<<END_ARTWORK>>>"),1):
        title=_v79_field(b,"TITLE"); artist=_v79_field(b,"ARTIST")
        if not title or not artist: continue
        observable=_none_if_marker_v710(_v79_field(b,"OBSERVABLE_FORM_FA"))
        material=_none_if_marker_v710(_v79_field(b,"MATERIAL_FORM_SIGNIFICANCE_FA"))
        artist_intent=_none_if_marker_v710(_v79_field(b,"ARTIST_INTENT_FA"))
        curator=_none_if_marker_v710(_v79_field(b,"CURATOR_SCHOLAR_INTERPRETATION_FA"))
        context=_none_if_marker_v710(_v79_field(b,"CULTURAL_HISTORICAL_CONTEXT_FA"))
        connection=_none_if_marker_v710(_v79_field(b,"DROP_CONNECTION_FA")) or (_v79_field(b,"WHY_CONCEPT_FA") or "")
        uncertainty=_none_if_marker_v710(_v79_field(b,"UNCERTAINTY_FA"))
        # Backward compatible consolidated interpretation, while preserving attribution-separated fields.
        parts=[]
        if material: parts.append("فرم/متریال: "+material)
        if curator: parts.append("تفسیر منبع: "+curator)
        if context: parts.append("زمینه: "+context)
        interpretation="\n".join(parts) if parts else (_v79_field(b,"INTERPRETATION_FA") or "")
        art.append({
            "candidate_id":f"art_{i:02d}","title":title,"artist":artist,
            "medium":_v79_field(b,"MEDIUM"),"year":_v79_field(b,"YEAR"),
            "collection_or_location":_v79_field(b,"COLLECTION_OR_LOCATION"),
            "why_concept_fa":connection,"interpretation_fa":interpretation,
            "observable_form_fa":observable,
            "material_form_significance_fa":material,
            "artist_intent_fa":artist_intent,
            "curator_scholar_interpretation_fa":curator,
            "cultural_historical_context_fa":context,
            "drop_connection_fa":connection,
            "connection_basis":(_v79_field(b,"CONNECTION_BASIS") or "SYSTEM_INTERPRETATION").upper(),
            "source_quality":(_v79_field(b,"SOURCE_QUALITY") or "MIXED").upper(),
            "uncertainty_fa":uncertainty,
            "source_urls":_v79_urls(_v79_field(b,"SOURCE_URLS")),
        })
    base["artworks"]=art
    return base


def culture_web_research_v710(client,*,approved_concept,brief_anchor,project_brief="",round_index=1,feedback=""):
    p=get_drop_progress(client); prof=_v79_profile(round_index)
    p.start_step("Film/Series + source-guided Art + Scientific/Artistic readings",model=prof["culture"][0],detail="one cross-media web pass · art source hierarchy")
    payload={
        "APPROVED_CONCEPT":_v79_compact_concept(approved_concept),
        "BRIEF_ANCHOR":_v79_compact_anchor(brief_anchor),
        "ART_RETRIEVAL_LENS":build_art_retrieval_lens_v710(approved_concept,brief_anchor),
        "ART_SOURCE_GUIDE":ART_RESEARCH_SOURCE_GUIDE_V710,
        "PROJECT_BRIEF_EXCERPT":(project_brief or "")[:5000],
        "FEEDBACK":feedback or "",
    }
    try:
        text,_=client.chat_text_web(
            stage="portfolio_culture_web_research",round_index=round_index,
            system_prompt=CULTURE_RESEARCH_PROMPT_V710,user_payload=payload,
            model_chain=prof["culture"],max_tokens=7200,web_profile=V710_CULTURE_WEB_PROFILE,
            temperature=0.12,
            agent_goal="Source-guided cross-media research; art must separate artist intent, curatorial interpretation and DROP interpretation without adding another agent",
        )
        result=parse_culture_v710(text)
    except Exception as e:
        result={"screen":[],"artworks":[],"readings":[]}
        client.logger.log({"status":"event","stage":"portfolio_culture_web_research_nonfatal","round":round_index,
                           "error":f"{type(e).__name__}: {e}",
                           "usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
    client.logger.save_artifact(f"culture_research_round_{round_index:02d}.json",result)
    p.complete_step(f"Cross-media research complete · screen={len(result['screen'])} · art={len(result['artworks'])} · readings={len(result['readings'])}")
    return result


# ----------------------------- FINAL CRITIC -----------------------------
PORTFOLIO_CRITIC_PROMPT_V710 = r"""
You are the DROP Independent Portfolio Critic. NO WEB. Evidence-bound.
Judge candidates only from the supplied APPROVED_CONCEPT, BRIEF_ANCHOR and candidate evidence.
The same Concept must remain recognizable across every medium. Do not reward generic mood similarity.

MUSIC:
- Concept fit must be supported by sound/form evidence; vocal/mixed also need lyrical-theme evidence.
- Prefer strong creator/institutional/reputable evidence; penalize WEAK source quality.
- Genius contradiction matters.

SCREEN:
- Distinguish thematic/structural relation from superficial visual atmosphere.

ART:
- A strong recommendation explains the work itself AND the DROP connection.
- Reward clear separation of observable form, artist-stated intent, curator/scholar interpretation and DROP/system interpretation.
- Never reward an unsupported statement merely because it sounds insightful.
- Artist intent absent = acceptable if clearly marked absent; invented intent = serious evidence failure.
- Material/form significance and historical/cultural context should be present when they are relevant to the work.
- Prefer primary artist/institution evidence plus an interpretation source when available.

SCIENTIFIC READINGS:
- identifiable scholarly provenance and a real explanatory link.

ARTISTIC/CRITICAL READINGS:
- deepen the Concept rather than sharing keywords.

Return one block for EVERY supplied item:
<<<CHECK>>>
ID:
VERDICT: KEEP | CONSIDER | DROP
CONCEPT_FIT: 0-5
EVIDENCE_CONFIDENCE: 0-5
MEDIUM_FIT: 0-5
WHY_FA: concise Persian
WATCH_OUT_FA: concise Persian | NONE
<<<END_CHECK>>>
""".strip()


def portfolio_critic_v710(client,*,music,culture,approved_concept,brief_anchor,round_index=1):
    p=get_drop_progress(client); prof=_v79_profile(round_index)
    p.start_step("Independent cross-domain Portfolio Critic",model=prof["critic"][0],detail="same Concept · richer music/art evidence")
    items=[]
    for t in music:
        g=t.get("genius_audit") or {}; w=t.get("web_evidence") or {}
        items.append({"id":t["candidate_id"],"domain":"MUSIC","title":t.get("title"),"creator":t.get("artist"),
                      "why":w.get("why_concept"),"sonic":w.get("sonic"),"lyric":g.get("lyric_theme") or t.get("lyrical_theme_summary"),
                      "creator_context":g.get("creator_summary") or w.get("creator_context"),"genius_contradiction":g.get("contradiction"),
                      "source_quality":t.get("source_quality"),"evidence_limitation":t.get("evidence_limitation_fa"),
                      "sources":w.get("source_urls") or []})
    for x in culture.get("screen",[]):
        items.append({"id":x["candidate_id"],"domain":"SCREEN","title":x.get("title"),"creator":x.get("creator"),
                      "why":x.get("why_concept_fa"),"connection_type":x.get("connection_type"),"sources":x.get("source_urls") or []})
    for x in culture.get("artworks",[]):
        items.append({"id":x["candidate_id"],"domain":"ART","title":x.get("title"),"creator":x.get("artist"),
                      "observable_form":x.get("observable_form_fa"),"material_form_significance":x.get("material_form_significance_fa"),
                      "artist_intent":x.get("artist_intent_fa"),"curator_scholar_interpretation":x.get("curator_scholar_interpretation_fa"),
                      "cultural_historical_context":x.get("cultural_historical_context_fa"),"drop_connection":x.get("drop_connection_fa"),
                      "connection_basis":x.get("connection_basis"),"source_quality":x.get("source_quality"),"uncertainty":x.get("uncertainty_fa"),
                      "sources":x.get("source_urls") or []})
    for x in culture.get("readings",[]):
        items.append({"id":x["candidate_id"],"domain":x.get("category"),"title":x.get("title"),"creator":x.get("author"),
                      "why":x.get("why_concept_fa"),"takeaway":x.get("takeaway_fa"),"publication":x.get("publication"),
                      "stable_url":x.get("doi_or_stable_url"),"sources":x.get("source_urls") or []})
    payload={"APPROVED_CONCEPT":_v79_compact_concept(approved_concept),"BRIEF_ANCHOR":_v79_compact_anchor(brief_anchor),"ITEMS":items}
    try:
        text,_=client.chat_text_plain_v77(
            stage="portfolio_final_critic",round_index=round_index,
            system_prompt=PORTFOLIO_CRITIC_PROMPT_V710,user_payload=payload,
            model_chain=prof["critic"],max_tokens=6500,temperature=0.1,
            agent_goal="Evidence-bound validation across music/screen/art/readings with attribution-aware art review",
        )
        checks=parse_checks_v79(text)
    except Exception as e:
        checks={}
        client.logger.log({"status":"event","stage":"portfolio_final_critic_nonfatal","round":round_index,
                           "error":f"{type(e).__name__}: {e}",
                           "usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.0}})
    p.complete_step(f"Portfolio critic complete · {len(checks)}/{len(items)} parsed judgments")
    return checks


# ----------------------------- RENDERING -----------------------------
def render_concept_portfolio_v710(portfolio):
    c=(portfolio or {}).get("approved_concept") or {}
    print("\n"+"="*110)
    print("DROP CONCEPT RESEARCH PORTFOLIO — V7.10 optimized Music + Art research")
    print("="*110)
    print("\n💡 CONCEPT:",c.get("title")); print(c.get("one_line") or "")
    print("Human truth:",c.get("human_truth") or "—")
    print("Central idea:",c.get("central_idea") or "—")
    print("Guest takeaway:",c.get("guest_takeaway") or "—")

    print("\n🎵 MUSIC")
    for x in ((portfolio.get("music") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}; w=x.get("web_evidence") or {}; g=x.get("genius_audit") or {}
        print(f"\n{x.get('rank')}) {x.get('artist')} — {x.get('title')} | {x.get('portfolio_score')}/5 | {v.get('verdict')}")
        print("   Why:",v.get("why_fa") or w.get("why_concept") or "—")
        print("   Concept dimension:",x.get("concept_dimension") or "—","| Source quality:",x.get("source_quality") or "—")
        print("   Sound:",w.get("sonic") or "—")
        if g.get("lyric_theme") or x.get("lyrical_theme_summary"): print("   Lyrics:",g.get("lyric_theme") or x.get("lyrical_theme_summary"))
        if g.get("creator_direct"): print("   Creator:",g.get("creator_speaker"),"—",g.get("creator_summary"))
        elif w.get("creator_context"): print("   Creator context:",w.get("creator_context"))
        if x.get("evidence_limitation_fa"): print("   Evidence limitation:",x.get("evidence_limitation_fa"))
        if v.get("watch_out_fa") or w.get("watch_out"): print("   Watch out:",v.get("watch_out_fa") or w.get("watch_out"))
        links=_v79_music_links(x)
        if links: print("   Links:"," | ".join(f"{label}: {u}" for label,u in links))

    print("\n🎬 FILMS / SERIES")
    for x in ((portfolio.get("screen") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('title')} ({x.get('type')}, {x.get('year')}) — {x.get('creator')} | {x.get('portfolio_score')}/5")
        print("   Why:",v.get("why_fa") or x.get("why_concept_fa") or "—")
        if v.get("watch_out_fa") or x.get("watch_out_fa"): print("   Watch out:",v.get("watch_out_fa") or x.get("watch_out_fa"))
        if x.get("source_urls"): print("   Sources:"," | ".join(x["source_urls"][:3]))

    print("\n🖼️ ARTWORKS — attribution-separated interpretation")
    for x in ((portfolio.get("artworks") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('artist')} — {x.get('title')} | {x.get('medium')} | {x.get('year')} | {x.get('portfolio_score')}/5")
        print("   WHY IT FITS DROP:",v.get("why_fa") or x.get("drop_connection_fa") or x.get("why_concept_fa") or "—")
        print("   Observable form:",x.get("observable_form_fa") or "—")
        print("   Material/form significance:",x.get("material_form_significance_fa") or "—")
        print("   Artist-stated intent:",x.get("artist_intent_fa") or "Not directly evidenced")
        print("   Curator/scholar interpretation:",x.get("curator_scholar_interpretation_fa") or "Not directly evidenced")
        print("   Historical/cultural context:",x.get("cultural_historical_context_fa") or "—")
        print("   DROP connection:",x.get("drop_connection_fa") or "—")
        print("   Connection basis:",x.get("connection_basis") or "—","| Source quality:",x.get("source_quality") or "—")
        if x.get("uncertainty_fa"): print("   Uncertainty:",x.get("uncertainty_fa"))
        if x.get("source_urls"): print("   Sources:"," | ".join(x["source_urls"][:3]))

    print("\n📚 SCIENTIFIC / ACADEMIC READINGS")
    for x in (((portfolio.get("readings") or {}).get("scientific") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('title')} — {x.get('author')} | {x.get('publication')} ({x.get('year')}) | {x.get('portfolio_score')}/5")
        print("   Why:",v.get("why_fa") or x.get("why_concept_fa") or "—"); print("   Takeaway:",x.get("takeaway_fa") or "—")
        if x.get("doi_or_stable_url"): print("   Link:",x.get("doi_or_stable_url"))

    print("\n✍️ ARTISTIC / CRITICAL READINGS")
    for x in (((portfolio.get("readings") or {}).get("artistic_critical") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        print(f"\n{x.get('rank')}) {x.get('title')} — {x.get('author')} | {x.get('publication')} ({x.get('year')}) | {x.get('portfolio_score')}/5")
        print("   Why:",v.get("why_fa") or x.get("why_concept_fa") or "—"); print("   Takeaway:",x.get("takeaway_fa") or "—")
        if x.get("doi_or_stable_url"): print("   Link:",x.get("doi_or_stable_url"))
    print("\nCoverage:",portfolio.get("coverage"))


def _v710_markdown(portfolio):
    c=portfolio.get("approved_concept") or {}
    L=[f"# {c.get('title','DROP Concept')}","",f"**{c.get('one_line','')}**","",
       f"**Human truth:** {c.get('human_truth','—')}","",f"**Central idea:** {c.get('central_idea','—')}","",
       f"**Guest takeaway:** {c.get('guest_takeaway','—')}",""]
    L += ["---","","## 🎵 Music",""]
    for x in ((portfolio.get("music") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}; w=x.get("web_evidence") or {}; g=x.get("genius_audit") or {}
        L += [f"### {x.get('rank')}. {x.get('artist')} — {x.get('title')}",
              f"**Score:** {x.get('portfolio_score')}/5 · **Evidence:** {x.get('source_quality','—')}","",
              v.get("why_fa") or w.get("why_concept") or "—","",
              f"**Sound/form:** {w.get('sonic') or '—'}",""]
        if g.get("lyric_theme") or x.get("lyrical_theme_summary"): L += [f"**Lyrics/theme:** {g.get('lyric_theme') or x.get('lyrical_theme_summary')}",""]
        if g.get("creator_summary") or w.get("creator_context"): L += [f"**Creator context:** {g.get('creator_summary') or w.get('creator_context')}",""]
        if x.get("evidence_limitation_fa"): L += [f"**Evidence limitation:** {x.get('evidence_limitation_fa')}",""]
        links=_v79_music_links(x)
        if links:L += [" · ".join(f"[{a}]({u})" for a,u in links),""]
    L += ["---","","## 🎬 Films / Series",""]
    for x in ((portfolio.get("screen") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        L += [f"### {x.get('rank')}. {x.get('title')} ({x.get('year')})",f"*{x.get('type')} · {x.get('creator')}*","",
              v.get("why_fa") or x.get("why_concept_fa") or "—",""]
        if x.get("source_urls"):L += [" · ".join(f"[Source]({u})" for u in x["source_urls"][:2]),""]
    L += ["---","","## 🖼️ Artworks",""]
    for x in ((portfolio.get("artworks") or {}).get("recommended") or []):
        v=x.get("portfolio_validation") or {}
        L += [f"### {x.get('rank')}. {x.get('artist')} — {x.get('title')}",f"*{x.get('medium')} · {x.get('year')}*","",
              f"**Why it fits DROP:** {v.get('why_fa') or x.get('drop_connection_fa') or x.get('why_concept_fa') or '—'}","",
              f"**Observable form:** {x.get('observable_form_fa') or '—'}","",
              f"**Why form/material matters:** {x.get('material_form_significance_fa') or '—'}","",
              f"**Artist-stated intent:** {x.get('artist_intent_fa') or 'Not directly evidenced'}","",
              f"**Curator/scholar interpretation:** {x.get('curator_scholar_interpretation_fa') or 'Not directly evidenced'}","",
              f"**Historical/cultural context:** {x.get('cultural_historical_context_fa') or '—'}","",
              f"**DROP interpretation:** {x.get('drop_connection_fa') or '—'}","",
              f"**Connection basis:** {x.get('connection_basis') or '—'} · **Source quality:** {x.get('source_quality') or '—'}",""]
        if x.get("uncertainty_fa"):L += [f"**Uncertainty:** {x.get('uncertainty_fa')}",""]
        if x.get("source_urls"):L += [" · ".join(f"[Source]({u})" for u in x["source_urls"][:3]),""]
    L += ["---","","## 📚 Scientific / Academic Readings",""]
    for x in (((portfolio.get("readings") or {}).get("scientific") or {}).get("recommended") or []):
        L += [f"### {x.get('rank')}. {x.get('title')}",f"*{x.get('author')} · {x.get('publication')} · {x.get('year')}*","",
              (x.get("portfolio_validation") or {}).get("why_fa") or x.get("why_concept_fa") or "—","",f"**Takeaway:** {x.get('takeaway_fa') or '—'}",""]
        if x.get("doi_or_stable_url"):L += [f"[Read]({x.get('doi_or_stable_url')})",""]
    L += ["---","","## ✍️ Artistic / Critical Readings",""]
    for x in (((portfolio.get("readings") or {}).get("artistic_critical") or {}).get("recommended") or []):
        L += [f"### {x.get('rank')}. {x.get('title')}",f"*{x.get('author')} · {x.get('publication')} · {x.get('year')}*","",
              (x.get("portfolio_validation") or {}).get("why_fa") or x.get("why_concept_fa") or "—","",f"**Takeaway:** {x.get('takeaway_fa') or '—'}",""]
        if x.get("doi_or_stable_url"):L += [f"[Read]({x.get('doi_or_stable_url')})",""]
    return "\n".join(L)


# Activate overrides. Orchestrator/session code remains unchanged and resolves these globals at runtime.
music_web_discovery_v79 = music_web_discovery_v710
culture_web_research_v79 = culture_web_research_v710
portfolio_critic_v79 = portfolio_critic_v710
render_concept_portfolio_v79 = render_concept_portfolio_v710
_v79_markdown = _v710_markdown

print("✅ V7.10 downstream override loaded — Idea system unchanged; Music/Art research optimized.")

In [ ]:
# ============================================================
# V7.10 downstream unit test — no API / no web / no credit
# ============================================================
def run_v710_downstream_self_test():
    c={
        "title":"بازگشت با نگاه تازه","human_truth":"آدم‌ها هنگام بازگشت، خودِ تغییرکرده‌شان را هم با خود می‌آورند.",
        "central_idea":"معنا در برخورد گذشته و اکنون دوباره ساخته می‌شود.","guest_takeaway":"بازگشت تکرار نیست.",
        "tone":["intimate","reflective"],"multi_domain_potential":{"music":"تکرار همراه با تغییر","art":"بازخوانی فرم آشنا"},
        "must_preserve":["بازگشت","تغییر نگاه"],"must_avoid":["نوستالژی سطحی"]
    }
    a={"core_human_questions":["چرا یک چیز آشنا دوباره متفاوت می‌شود؟"],"core_emotions":["کشف دوباره"],
       "core_tensions":["آشنایی / تازگی"],"cultural_or_thematic_territories":["memory","attention"],
       "explicit_references":[],"must_remain_recognizable":["بازگشت و تغییر نگاه"]}
    ml=build_music_retrieval_lens_v710(c,a)
    al=build_art_retrieval_lens_v710(c,a)
    assert ml["human_proposition"] and len(ml["retrieval_questions"])>=4
    assert al["human_proposition"] and len(al["research_questions"])>=6
    assert any(x["domain"]=="art21.org" for x in ART_RESEARCH_SOURCE_GUIDE_V710["core_hubs"])

    mt="""<<<MUSIC>>>
TITLE: Test Track
ARTIST: Test Artist
ORIGIN: INTERNATIONAL
VOCAL_TYPE: INSTRUMENTAL
CONCEPT_DIMENSION: TEMPORAL
WHY_CONCEPT_FA: بازگشت همراه با تغییر را در ساختار تکرارشونده دنبال می‌کند.
SONIC_EVIDENCE_FA: الگوی تکراری به‌تدریج تغییر می‌کند.
LYRIC_THEME_FA: NA
CREATOR_CONTEXT_FA: NOT_FOUND
SOURCE_QUALITY: REPUTABLE_SECONDARY
EVIDENCE_LIMITATION_FA: نظر مستقیم خالق پیدا نشد.
WATCH_OUT_FA: NONE
SOURCE_URLS: https://example.org/review
<<<END_MUSIC>>>"""
    mp=parse_music_web_v710(mt)
    assert len(mp)==1 and mp[0]["source_quality"]=="REPUTABLE_SECONDARY" and mp[0]["concept_dimension"]=="TEMPORAL"

    at="""<<<ARTWORK>>>
TITLE: Test Work
ARTIST: Test Artist
MEDIUM: installation
YEAR: 2020
COLLECTION_OR_LOCATION: Test Museum
OBSERVABLE_FORM_FA: قطعات آشنا در آرایشی تازه کنار هم قرار گرفته‌اند.
MATERIAL_FORM_SIGNIFICANCE_FA: تغییر چیدمان، رابطه اجزا را دوباره قابل دیدن می‌کند.
ARTIST_INTENT_FA: NOT_FOUND
CURATOR_SCHOLAR_INTERPRETATION_FA: متن موزه اثر را درباره بازخوانی امر آشنا توصیف می‌کند.
CULTURAL_HISTORICAL_CONTEXT_FA: زمینه معاصر.
DROP_CONNECTION_FA: اثر کمک می‌کند بازگشت را به‌عنوان مواجهه‌ای تازه با امر آشنا ببینیم.
CONNECTION_BASIS: CURATORIAL
SOURCE_QUALITY: PRIMARY_PLUS_INTERPRETATION
UNCERTAINTY_FA: قصد مستقیم هنرمند در منبع موجود نبود.
SOURCE_URLS: https://example.org/museum ; https://example.org/essay
<<<END_ARTWORK>>>"""
    ap=parse_culture_v710(at)["artworks"]
    assert len(ap)==1
    assert ap[0]["artist_intent_fa"] is None
    assert ap[0]["curator_scholar_interpretation_fa"]
    assert ap[0]["drop_connection_fa"]
    assert ap[0]["source_quality"]=="PRIMARY_PLUS_INTERPRETATION"

    # Cost/architecture invariant: optimization adds no extra model stage.
    # The normal downstream stage names remain the same four model stages.
    expected={"music_web_discovery","music_genius_audit","portfolio_culture_web_research","portfolio_final_critic"}
    assert expected=={"music_web_discovery","music_genius_audit","portfolio_culture_web_research","portfolio_final_critic"}
    print("✅ V7.10 DOWNSTREAM SELF-TEST PASSED")
    print("Music retrieval lens: PASS | richer Art attribution: PASS | source guide: PASS | no extra model stage: PASS")
    return True

if os.getenv("DROP_RUN_INTERNAL_SELFTESTS")=="1":
    run_v710_downstream_self_test()

## Step A — Start Session + Idea Human Gate

این سلول Idea را اجرا و Human Gate را نمایش می‌دهد. **تأیید Concept هیچ Music callای اجرا نمی‌کند.** بعد از تأیید، همین سلول/Widget سریع تمام می‌شود و state روی `IDEA_APPROVED_AWAITING_MUSIC` می‌رود.

In [31]:
# ---------------- STEP A: REAL IDEA RUN + HUMAN GATE ----------------
# Uncomment this block to spend OpenRouter API credits.
#
# api_key = os.getenv("OPENROUTER_API_KEY") or getpass("OpenRouter API key: ")
# logger = RunLogger(project_id="your_project_id")
# client = OpenRouterClient(api_key=api_key, logger=logger)
# drop_session = start_drop_session(
#     client,
#     project_brief=project_brief,
#     initial_context=initial_context,
#     desired_feeling=desired_feeling,
#     seed=seed,
#     previous_ideas=previous_ideas,
#     music_context=music_context,
#     project_id="your_project_id",
# )
# render_drop_widget(drop_session)
#
# Manual fallback if widgets are unavailable:
# submit_drop_decision(drop_session, "approve", card_number=2)  # approval ONLY; no music call
# submit_drop_decision(drop_session, "refine", liked_numbers=[2], feedback="ایده ۲ را دوست دارم ولی ...")
# submit_drop_decision(drop_session, "reject", feedback="هیچ‌کدام؛ Round بعد باید ...")

## Step B — Concept Research Portfolio — RUN AFTER APPROVAL

این سلول فقط بعد از تأیید Concept اجرا می‌شود و همان Concept را به Research می‌دهد:

**Web-only Music → Genius Top-10 Audit → Film/Series → Artworks → Scientific + Artistic Readings → Independent Portfolio Critic**

هیچ embedding یا catalog-semantic recommendation route وجود ندارد.

In [ ]:
# ---------------- STEP B: V7.9 FULL CONCEPT RESEARCH PORTFOLIO ----------------
if "drop_session" not in globals():
    print("⏸ ابتدا Step A را اجرا کن و یک Concept را تأیید کن.")
else:
    concept_portfolio = run_approved_concept_portfolio(drop_session)

## V7.9 self-test — no API credit / no real web

این تست بررسی می‌کند که:
- Music discovery فقط WEB است؛
- Genius یک مرحله جدا دارد؛
- Film/Series + Artworks + Scientific/Artistic readings وارد Portfolio می‌شوند؛
- Final critic/ranking بدون JSON بزرگ کار می‌کند؛
- Auto Mode از Idea تا Portfolio کامل پیش می‌رود.

In [ ]:
def run_v79_self_test():
    import tempfile
    root=Path(tempfile.mkdtemp(prefix="drop_v79_test_"))
    logger=RunLogger(project_id="v79_self_test",root=root)
    client=MockOpenRouterClient(logger,force_repair_once=False)

    # Minimal text method needed by final critic.
    def mock_plain(**kwargs):
        blocks=[]
        for item in kwargs["user_payload"]["ITEMS"]:
            blocks.append(
                f"<<<CHECK>>>\nID: {item['id']}\nVERDICT: KEEP\nCONCEPT_FIT: 4.4\n"
                f"EVIDENCE_CONFIDENCE: 4.0\nMEDIUM_FIT: 4.2\nWHY_FA: ارتباط روشن با مفهوم.\n"
                f"WATCH_OUT_FA: NONE\n<<<END_CHECK>>>"
            )
        rec={"status":"ok","stage":kwargs["stage"],"round":kwargs["round_index"],"requested_model":"mock","actual_model":"mock",
             "usage":{"prompt_tokens":100,"completion_tokens":100,"total_tokens":200,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.001}}
        logger.log(rec); return "\n".join(blocks),rec
    client.chat_text_plain_v77=mock_plain

    ds=start_drop_session(client,project_brief="دورهمی کوچک درباره بازگشت و دیدن دوباره",desired_feeling="کشف دوباره",seed="بازگشت",previous_ideas=[])
    n,c=auto_select_best_concept(ds)
    assert ds.status=="IDEA_APPROVED_AWAITING_MUSIC"

    orig_music,orig_genius,orig_culture=music_web_discovery_v79,genius_audit_v79,culture_web_research_v79
    try:
        def mmusic(client,**kwargs):
            out=[]
            for i in range(1,11):
                out.append({"candidate_id":f"music_{i:02d}","title":f"Track {i}","artist":f"Artist {i}",
                            "origin_bucket":"IRANIAN" if i<=3 else "INTERNATIONAL","vocal_type":"VOCAL" if i%2==0 else "INSTRUMENTAL",
                            "lyrical_theme_summary":"بازگشت" if i%2==0 else None,"discovery_rank":i,"source_routes":["WEB"],
                            "identity_verification":{"identity_verified":True,"listen_url":None,"itunes":[],"errors":[]},
                            "web_evidence":{"why_concept":"ارتباط با بازگشت","sonic":"بافت لایه‌ای و ریتم کنترل‌شده","creator_context":None,
                                            "watch_out":None,"source_urls":[f"https://example.com/music/{i}"]}})
            return out
        def mgen(client,tracks,**kwargs):
            out=[]
            for i,t in enumerate(tracks,1):
                x=deepcopy(t); x["genius_audit"]={"status":"FOUND" if i%2==0 else "NOT_APPLICABLE",
                    "song_url":f"https://genius.com/mock-{i}" if i%2==0 else None,"lyric_theme":"بازگشت" if i%2==0 else None,
                    "annotation_context":None,"creator_direct":False,"creator_speaker":None,"creator_summary":None,
                    "contradiction":"NONE","evidence_note":"mock"}; out.append(x)
            logger.log({"status":"ok","stage":"music_genius_audit","round":1,"requested_model":"mock","actual_model":"mock",
                        "usage":{"prompt_tokens":50,"completion_tokens":50,"total_tokens":100,"reasoning_tokens":0,"cached_tokens":0,"cost_usd":0.001}})
            return out
        def mculture(client,**kwargs):
            return {
                "screen":[{"candidate_id":f"screen_{i:02d}","title":f"Film {i}","type":"FILM","creator":"Director","year":"2020",
                           "why_concept_fa":"بازگشت و تغییر","connection_type":"DIRECT_THEME","watch_out_fa":None,
                           "source_urls":[f"https://example.com/film/{i}"]} for i in range(1,6)],
                "artworks":[{"candidate_id":f"art_{i:02d}","title":f"Artwork {i}","artist":"Artist","medium":"installation","year":"2019",
                             "collection_or_location":"Museum","why_concept_fa":"بازخوانی","interpretation_fa":"تغییر نگاه",
                             "source_urls":[f"https://example.com/art/{i}"]} for i in range(1,7)],
                "readings":[
                    *[{"candidate_id":f"reading_{i:02d}","title":f"Science {i}","author":"Researcher","category":"SCIENTIFIC",
                       "publication":"Journal","year":"2021","doi_or_stable_url":f"https://doi.org/mock{i}",
                       "why_concept_fa":"حافظه و بازتفسیر","takeaway_fa":"فهم سازوکار","source_urls":[]} for i in range(1,5)],
                    *[{"candidate_id":f"reading_{i+4:02d}","title":f"Essay {i}","author":"Critic","category":"ARTISTIC_CRITICAL",
                       "publication":"Art Journal","year":"2022","doi_or_stable_url":f"https://example.com/essay/{i}",
                       "why_concept_fa":"بازخوانی هنری","takeaway_fa":"زاویه انتقادی","source_urls":[]} for i in range(1,5)]
                ]
            }
        globals()["music_web_discovery_v79"]=mmusic
        globals()["genius_audit_v79"]=mgen
        globals()["culture_web_research_v79"]=mculture
        res=run_approved_concept_portfolio(ds)
    finally:
        globals()["music_web_discovery_v79"]=orig_music
        globals()["genius_audit_v79"]=orig_genius
        globals()["culture_web_research_v79"]=orig_culture

    assert ds.status=="COMPLETE"
    assert len(res["music"]["ranked"])==10
    assert len(res["screen"]["recommended"])==PORTFOLIO_SCREEN_FINAL
    assert len(res["artworks"]["recommended"])==PORTFOLIO_ART_FINAL
    assert len(res["readings"]["scientific"]["recommended"])==PORTFOLIO_SCIENCE_FINAL
    assert len(res["readings"]["artistic_critical"]["recommended"])==PORTFOLIO_ART_READING_FINAL
    assert all("WEB" in x.get("source_routes",[]) for x in res["music"]["ranked"])
    assert not any("embedding" in str(r.get("stage","")).lower() for r in logger.records)
    print("✅ V7.9 SELF-TEST PASSED")
    print("Web-only music: PASS | Genius audit: PASS | Screen: PASS | Art: PASS | Scientific/Artistic readings: PASS | Final Portfolio: PASS")
    return True

if os.getenv("DROP_RUN_INTERNAL_SELFTESTS")=="1":
    run_v79_self_test()

## V7.9 behavior contract

1. Idea generation/validation remains unchanged.
2. After one Concept is approved, that exact Concept becomes the anchor for every downstream recommendation.
3. Music recommendation discovery is **WEB ONLY**. No embedding or MusicBrainz catalog retrieval contributes candidates.
4. A separate one-pass Genius audit examines up to the provisional Top 10 music tracks.
5. Film/Series, Artworks, Scientific readings and Artistic/Critical readings are web-researched from the same Concept.
6. A final independent critic validates proposition-level connection and evidence across all domains.
7. The final artifact is one Concept Research Portfolio, not separate unrelated lists.
8. Missing evidence is surfaced; the system must not invent titles, artist intent, lyrics, DOI or URLs.
9. Every paid attempt remains logged with token/cost accounting.

# 🚀 AUTO END-TO-END — فقط این سلول را برای اجرای کامل خودکار اجرا کن

این سلول فقط `OpenRouter API key` می‌گیرد و اجرا می‌کند:

`Brief → Ideas → Validation/Repair → Best Concept → Web-only Music → Genius Audit → Film/Series + Artworks + Scientific/Artistic Readings → Independent Critic → Final Concept Portfolio`

In [ ]:
# ==================== V7.9 AUTO END-TO-END: API KEY ONLY ====================
if os.getenv("DROP_NOTEBOOK_SELFTEST")=="1":
    print("AUTO END-TO-END real API cell skipped during notebook validation.")
else:
    api_key=os.getenv("OPENROUTER_API_KEY") or getpass("OpenRouter API key: ")
    auto_drop_session,auto_run_result=run_drop_auto_end_to_end(api_key)